/* ---------- Elements cache ---------- */
const E = {};

const ModalScrollLock = (() => {
  const OPEN_SELECTOR = [
    '.modal[aria-hidden="false"]',
    '.modal.show',
    '.modal.open',
    '.modal-overlay.show',
    '[class*="modal-overlay"].show'
  ].join(', ');

  function lock() {
    document.body?.classList.add('modal-open');
    return true;
  }

  function unlock() {
    const stillOpen = document.querySelector(OPEN_SELECTOR);
    if (!stillOpen) document.body?.classList.remove('modal-open');
    return true;
  }

  return { lock, unlock, OPEN_SELECTOR };
})();
window.ModalScrollLock = ModalScrollLock;

function cacheEls() {
  [
    'issuesTable',
    'issuesTbody',
    'tbodySkeleton',
    'columnToggleBtn',
    'bulkEditBtn',
    'bulkEditModal',
    'bulkEditForm',
    'bulkEditClose',
    'bulkEditCancel',
    'bulkIssueIds',
    'bulkPriority',
    'bulkStatus',
    'bulkDevTeamStatus',
    'bulkNotes',
    'columnPanel',
    'columnList',
    'rowCount',
    'moduleFilter',
    'categoryFilter',
    'priorityFilter',
    'statusFilter',
    'devTeamStatusFilter',
    'devTeamStatusFilterRow',
    'issueRelatedFilter',
    'issueRelatedFilterRow',
    'resetBtn',
    'refreshNow',
    'exportCsv',
    'kpis',
    'ticketInternalWidgets',
    'issueModal',
    'modalBody',
    'modalTitle',
    'replyRecipientLabel',
    'replyEmailBtn',
    'exportIssuePdf',
    'exportIssueExcel',
    'copyLink',
    'editIssueBtn',
    'deleteIssueBtn',
    'modalClose',
    'editIssueModal',
    'editIssueForm',
    'editIssueClose',
    'editIssueCancel',
    'editIssueTitleInput',
    'editIssueDesc',
    'editIssueModule',
    'editIssuePriority',
    'editIssueStatus',
    'editIssueType',
    'editIssueDepartment',
    'editIssueName',
    'editIssueEmail',
    'editIssueYoutrackReference',
    'editIssueDevTeamStatus',
    'editIssueRelated',
    'editIssueFile',
    'editIssueDate',
    'drawerBtn',
    'drawerBtn',
    'sidebar',
    'mainFiltersPanel',
    'leadsFiltersPanel',
    'dealsFiltersPanel',
     'app',
    'spinner',
    'toast',
    'searchInput',
    'loginForm',
    'loginIdentifier',
    'loginPasscode',
    'loginBtn',
    'loginHint',
    'logoutBtn',
    'notificationBellBtn',
    'notificationUnreadBadge',
    'notificationPreviewPanel',
    'notificationPreviewState',
    'notificationPreviewList',
    'notificationOpenHubBtn',
    'notificationSoundToggleBtn',
     'savedViews',
    'saveViewBtn',
    'deleteViewBtn',
    'themeSelect',
    'firstPage',
    'prevPage',
    'nextPage',
    'lastPage',
    'pageInfo',
    'pageSize',
    'createTicketBtn',
    'createTicketModal',
    'createTicketForm',
    'createTicketClose',
    'createTicketCancel',
    'createTicketName',
    'createTicketDepartment',
    'createTicketModule',
    'createTicketSubject',
    'createTicketDesc',
    'createTicketFile',
    'createTicketAttachmentRow',
    'createTicketAttachments',
    'createTicketAttachmentError',
    'createTicketAttachmentList',
    'createTicketEmail',
    'createTicketPriority',
    'createTicketType',
    'createTicketSubmit',
    'startDateFilter',
    'endDateFilter',
    'issuesTab',
    'calendarTab',
    'csmTab',
    'clientSuccessTab',
    'companyTab',
    'contactsTab',
    'leadsTab',
    'dealsTab',
    'proposalsTab',
    'agreementsTab',
    'commissionTrackerTab',
    'invoicesTab',
    'receiptsTab',
    'creditNotesTab',
    'paymentForecastTab',
    'renewalForecastTab',
    'binersTab',
    'hrTab',
    'accountingTab',
    'backupCenterTab',
    'lifecycleAnalyticsTab',
    'clientsTab',
    'proposalCatalogTab',
    'communicationCentreTab',
    'notificationsTab',
    'issuesView',
    'calendarView',
    'csmView',
    'clientSuccessView',
    'companyView',
    'contactsView',
    'leadsView',
    'dealsView',
    'proposalsView',
    'agreementsView',
    'commissionTrackerView',
    'invoicesView',
    'receiptsView',
    'creditNotesView',
    'paymentForecastView',
    'renewalForecastView',
    'binersView',
    'hrView',
    'accountingView',
    'backupCenterView',
    'lifecycleAnalyticsView',
    'clientsView',
    'proposalCatalogView',
    'communicationCentreView',
    'notificationsView',
    'addEventBtn',
    'eventsExportBtn',
    'eventModal',
    'eventModalTitle',
    'eventDetailTitle',
    'eventModalClose',
    'eventForm',
    'eventTitle',
    'eventType',
    'eventIssueSearch',
    'eventIssueId',
    'eventIssueSelectedChips',
    'eventIssueClearBtn',
    'eventIssueEmptyState',
    'eventIssueShowAllBtn',
    'eventStart',
    'eventEnd',
    'eventDescription',
    'eventSave',
    'eventCancel',
    'eventDelete',
    'eventIssueLinkedInfo',
    'eventChecklistStatus',
   'aiClustersList',
    'syncIssuesText',
    'syncIssuesDot',
    'syncEventsText',
    'syncEventsDot',
    'eventFilterDeployment',
    'eventFilterMaintenance',
    'eventFilterRelease',
    'eventFilterOther',
    'loadingStatus',
    'issuesSummaryText',
    'issuesLastUpdated',
    'activeFiltersChips',
    'calendarTz',
    'onlineStatusChip',
    'currentUserChip',
    'currentUserAvatar',
    'currentRoleChip',
    'usersTab',
    'rolePermissionsTab',
    'notificationSetupTab',
    'workflowTab',
    'usersView',
    'rolePermissionsView',
    'notificationSetupView',
    'workflowView',
    'workflowRulesTbody',
    'workflowRuleForm',
    'workflowRuleId',
    'workflowResource',
    'workflowCurrentStatus',
    'workflowNextStatus',
    'workflowAllowedRoles',
    'workflowRequiresApproval',
    'workflowApprovalRoles',
    'workflowGenericDiscountFields',
    'workflowMaxDiscount',
    'workflowHardStopDiscount',
    'workflowCategoryDiscountFields',
    'workflowAnnualSaasNoApproval',
    'workflowAnnualSaasHardStop',
    'workflowOneTimeFeeNoApproval',
    'workflowOneTimeFeeHardStop',
    'workflowHardwareNoApproval',
    'workflowHardwareHardStop',
    'workflowEditableFields',
    'workflowRequiredFields',
    'workflowRequireComment',
    'workflowRequireAttachment',
    'workflowIsActive',
    'workflowRuleSaveBtn',
    'workflowRuleResetBtn',
    'workflowApprovalsTbody',
    'workflowApprovalPreviewModal',
    'workflowApprovalPreviewTitle',
    'workflowApprovalPreviewBody',
    'workflowApprovalPreviewCloseBtn',
    'workflowApprovalPreviewFooterCloseBtn',
    'workflowApprovalPreviewApproveBtn',
    'workflowApprovalPreviewRejectBtn',
    'workflowAuditTbody',
    'workflowAuditSearch',
    'workflowAuditResourceFilter',
    'workflowAuditAllowedFilter',
    'workflowResourceFilter',
    'workflowRefreshBtn',
    'workflowMatrixResource',
    'workflowMatrixContainer',
    'workflowDiscountPolicyTbody',
    'notificationsSummaryTotalUnread',
    'notificationsSummaryHighUnread',
    'notificationsSummaryApprovalsUnread',
    'notificationsSummaryOperationsUnread',
    'notificationsFilterButtons',
    'notificationsSearchInput',
    'notificationsRefreshBtn',
    'notificationsMarkAllBtn',
    'notificationsState',
    'notificationsTbody',
    'csmSearchInput',
    'csmNameFilter',
    'csmClientFilter',
    'csmSupportTypeFilter',
    'csmEffortFilter',
    'csmChannelFilter',
    'csmMinMinutesFilter',
    'csmMaxMinutesFilter',
    'csmStartDateFilter',
    'csmEndDateFilter',
    'csmKpiActivities',
    'csmKpiActivitiesSub',
    'csmKpiMinutes',
    'csmKpiMinutesSub',
    'csmKpiAvg',
    'csmKpiAvgSub',
    'csmKpiActiveClients',
    'csmKpiActiveClientsSub',
    'csmKpiWeightedLoad',
    'csmKpiWeightedLoadSub',
    'csmKpiHighEffortShare',
    'csmKpiHighEffortShareSub',
    'csmWeekdayWorkloadChart',
    'csmWeeklyTrendChart',
    'csmEffortMixByCsmChart',
    'csmClientConcentrationChart',
    'csmWorkloadBalanceChart',
    'csmMinutesByClientChart',
    'csmTypeOfSupportChart',
    'csmEffortRequirementChart',
    'csmSupportChannelsChart',
    'csmInsightList',
    'csmTopSnapshotBody',
    'csmAddActivityBtn',
    'csmAddActivityWithoutAgreementBtn',
    'csmExportCsvBtn',
    'csmRowCount',
    'csmTableBody',
    'csmInlineCreateForm',
    'csmInlineTimestamp',
    'csmInlineMinutes',
    'csmInlineCsmName',
    'csmInlineClient',
    'csmInlineSupportType',
    'csmInlineEffort',
    'csmInlineChannel',
    'csmInlineNotes',
    'csmInlineSubmitBtn',
    'csmDetailsModal',
    'csmDetailsCloseBtn',
    'csmDetailsBody',
    'csmFormModal',
    'csmForm',
    'csmFormTitle',
    'csmFormCloseBtn',
    'csmFormCancelBtn',
    'csmFormSaveBtn',
    'csmFormDeleteBtn',
    'csmFormCsmName',
    'csmFormAgreementClientFields',
    'csmFormSpecialClientFields',
    'csmFormSpecialClientSearch',
    'csmFormSpecialClient',
    'csmFormSpecialClientState',
    'csmFormManualClientFields',
    'csmFormManualClientName',
    'csmFormManualLocationName',
    'csmFormClientSearch',
    'csmFormClient',
    'csmFormClientState',
    'csmFormCompanyName',
    'csmFormGroupState',
    'csmFormGroup',
    'csmFormGroupFields',
    'csmFormActivityScope',
    'csmFormMinutes',
    'csmFormSupportType',
    'csmFormEffort',
    'csmFormChannel',
    'csmFormNotes',
    'receiptSummary',
    'receiptsSearchInput',
    'receiptsInvoiceFilter',
    'receiptsCustomerFilter',
    'receiptsStatusFilter',
    'receiptsRefreshBtn',
    'receiptsCreateBtn',
    'receiptsExportCsvBtn',
    'receiptsClearFiltersBtn',
    'receiptsStatusDistribution',
    'receiptsTypeDistribution',
    'receiptsState',
    'receiptsTbody',
    'creditNotesSummary',
    'creditNotesSearchInput',
    'creditNotesStatusFilter',
    'creditNotesRefreshBtn',
    'creditNotesCreateBtn',
    'creditNotesState',
    'creditNotesTbody',
    'creditNoteFormModal',
    'creditNoteForm',
    'creditNoteFormTitle',
    'creditNoteFormCloseBtn',
    'creditNoteFormInvoiceSelect',
    'creditNoteFormDate',
    'creditNoteFormDescription',
    'creditNoteFormAmount',
    'creditNoteInvoiceInfo',
    'creditNoteFormPreviewBtn',
    'creditNoteFormCancelBtn',
    'creditNoteFormSaveBtn',
    'creditNotePreviewModal',
    'creditNotePreviewTitle',
    'creditNotePreviewFrame',
    'creditNotePreviewCloseBtn',
    'creditNotePreviewExportPdfBtn',
    'paymentForecastSummary',
    'paymentForecastAnalytics',
    'paymentForecastSearchInput',
    'paymentForecastStatusFilter',
    'paymentForecastClientFilter',
    'paymentForecastDateFrom',
    'paymentForecastDateTo',
    'paymentForecastOnlyUnpaid',
    'paymentForecastRefreshBtn',
    'paymentForecastExportBtn',
    'paymentForecastState',
    'paymentForecastTbody',
    'lifecycleSearchInput',
    'lifecycleSearchBtn',
    'lifecycleDateFrom',
    'lifecycleDateTo',
    'lifecycleStageFilter',
    'lifecycleOwnerFilter',
    'lifecycleExportBtn',
    'lifecycleState',
    'lifecycleResultBody',
    'receiptFormModal',
    'receiptForm',
    'receiptFormTitle',
    'receiptFormCloseBtn',
    'receiptFormCancelBtn',
    'receiptFormSaveBtn',
    'receiptFormDeleteBtn',
    'receiptFormPreviewBtn',
    'receiptFormIdBadge',
    'receiptFormReceiptId',
    'receiptFormReceiptNumber',
    'receiptFormInvoiceId',
    'receiptFormInvoiceNumber',
    'receiptFormAgreementUuid',
    'receiptFormAgreementId',
    'receiptFormAgreementNumber',
    'receiptFormReceiptDate',
    'receiptFormDueDateDisplay',
    'receiptFormCustomerName',
    'receiptFormCustomerLegalName',
    'receiptFormCustomerAddress',
    'receiptFormCurrency',
    'receiptFormStatus',
    'receiptFormAmountInWords',
    'receiptFormInvoiceGrandTotal',
    'receiptFormCreditNoteAmount',
    'receiptFormOldPaidTotal',
    'receiptFormPaidNow',
    'receiptFormNewPaidTotal',
    'receiptFormReceivedAmount',
    'receiptFormPendingAmount',
    'receiptFormPaymentState',
    'receiptFormPaymentConclusion',
    'receiptFormPaymentNotes',
    'receiptFormSupportEmail',
    'receiptFormContactPhoneDisplay',
    'receiptFormPaymentMethodDisplay',
    'receiptFormPaymentReferenceDisplay',
    'receiptLocationSubtotal',
    'receiptOneTimeSubtotal',
    'receiptHardwareSubtotal',
    'receiptLocationItemsTbody',
    'receiptOneTimeItemsTbody',
    'receiptHardwareItemsTbody',
    'receiptPreviewModal',
    'receiptPreviewTitle',
    'receiptPreviewExportPdfBtn',
    'receiptPreviewFrame',
    'receiptPreviewCloseBtn',
    'usersRefreshBtn',
    'usersState',
    'usersTbody',
    'leadsRefreshBtn',
    'leadsExportCsvBtn',
    'leadsCreateBtn',
    'leadsSearchInput',
    'leadsStatusFilter',
    'leadsServiceInterestFilter',
    'leadsAssignedToFilter',
    'leadsStartDateFilter',
    'leadsEndDateFilter',
    'leadsResetBtn',
    'leadsState',
    'leadsKpiTotal',
    'leadsKpiNew',
    'leadsKpiQualified',
    'leadsKpiProposalSent',
    'leadsKpiWon',
    'leadsKpiLost',
    'leadsKpiHighPriority',
    'leadsKpiPipelineValue',
    'leadsKpiPipelineSub',
    'leadsKpiConversionRate',
    'leadsStatusDistribution',
    'leadsTable',
    'leadsTbody',
    'dealsSearchInput',
    'dealsSidebarSearchInput',
    'dealsStageFilter',
    'dealsStatusFilter',
    'dealsPriorityFilter',
    'dealsServiceInterestFilter',
    'dealsLeadSourceFilter',
    'dealsAssignedToFilter',
    'dealsStartDateFilter',
    'dealsEndDateFilter',
    'dealsResetBtn',
    'dealsCreateBtn',
    'dealsRefreshBtn',
    'dealsExportCsvBtn',
    'clientsRefreshBtn',
    'clientsCreateBtn',
    'clientsSearchInput',
    'clientsStatusFilter',
    'clientsSortSelect',
    'clientsState',
    'clientsGlobalRenewals',
    'clientsTbody',
    'clientsDetailEmpty',
    'clientsDetailPanel',
    'clientDetailName',
    'clientDetailMeta',
    'clientDetailStatus',
    'clientDetailOverview',
    'clientAnalyticsCards',
    'clientRelatedAgreementsTbody',
    'clientRelatedInvoicesTbody',
    'clientRelatedReceiptsTbody',
    'clientTimeline',
    'clientDetailTabButtons',
    'clientOverviewSection',
    'clientStatementSection',
    'clientRenewalsSection',
    'clientStatementCards',
    'clientStatementFiltersStatus',
    'clientStatementDateFrom',
    'clientStatementDateTo',
    'clientStatementSearchDoc',
    'clientStatementApplyFiltersBtn',
    'clientStatementResetFiltersBtn',
    'clientStatementExportPdfBtn',
    'clientStatementTbody',
    'clientStatementPreviewModal',
    'clientStatementPreviewTitle',
    'clientStatementPreviewExportPdfBtn',
    'clientStatementPreviewCloseBtn',
    'clientStatementPreviewFrame',
    'clientRenewalBuckets',
    'clientScheduledPaymentsSection',
    'clientScheduledPaymentCards',
    'clientScheduledPaymentFilters',
    'clientScheduledPaymentsTbody',
    'clientRenewalsDateFrom',
    'clientRenewalsDateTo',
    'clientRenewalsApplyFiltersBtn',
    'clientRenewalsResetFiltersBtn',
    'clientRenewalsTbody',
    'clientRenewalEvents',
    'clientActionProposalBtn',
    'clientActionAgreementBtn',
    'clientActionInvoiceBtn',
    'clientActionCloneBtn',
    'newClientModal',
    'newClientForm',
    'newClientCloseBtn',
    'newClientCancelBtn',
    'newClientSaveBtn',
    'importOldClientBtn',
    'importOldClientModal',
    'importOldClientForm',
    'importOldClientCloseBtn',
    'importOldClientCancelBtn',
    'dealsAnalytics',
    'dealsAnalyticsGrid',
    'dealsKpiTotal',
    'dealsKpiOpen',
    'dealsKpiWon',
    'dealsKpiLost',
    'dealsKpiHighPriority',
    'dealsKpiPipelineValue',
    'dealsKpiPipelineSub',
    'dealsKpiWeightedPipelineValue',
    'dealsKpiWeightedPipelineSub',
    'dealsKpiWinRate',
    'dealsKpiAverageDealSize',
    'dealsKpiAverageWonDealSize',
    'dealsKpiConvertedFromLeads',
    'dealsKpiUniqueCompanies',
    'dealsKpiUniqueAssignees',
    'dealsStageDistribution',
    'dealsStatusDistribution',
    'dealsAssigneeBreakdown',
    'dealsServiceBreakdown',
    'dealsSourceBreakdown',
    'dealsState',
    'dealsTable',
    'dealsTbody',
    'dealFormModal',
    'dealForm',
    'dealFormTitle',
    'dealFormCloseBtn',
    'dealFormCancelBtn',
    'dealFormSaveBtn',
    'dealFormDeleteBtn',
    'dealFormDealId',
    'dealFormLeadId',
    'dealFormLeadSelector',
    'dealFormCompanySelector',
    'dealFormContactSelector',
    'dealFormCompanyId',
    'dealFormContactId',
    'dealCompanyIdDisplay',
    'dealCompanyNameDisplay',
    'dealCompanyLegalNameDisplay',
    'dealCompanyTypeDisplay',
    'dealCompanyIndustryDisplay',
    'dealCompanyWebsiteDisplay',
    'dealCompanyMainEmailDisplay',
    'dealCompanyMainPhoneDisplay',
    'dealCompanyCountryDisplay',
    'dealCompanyCityDisplay',
    'dealCompanyAddressDisplay',
    'dealCompanyTaxNumberDisplay',
    'dealCompanyStatusDisplay',
    'dealContactIdDisplay',
    'dealContactFirstNameDisplay',
    'dealContactLastNameDisplay',
    'dealContactJobTitleDisplay',
    'dealContactDepartmentDisplay',
    'dealContactEmailDisplay',
    'dealContactPhoneDisplay',
    'dealContactMobileDisplay',
    'dealContactDecisionRoleDisplay',
    'dealContactPrimaryDisplay',
    'dealContactStatusDisplay',
    'dealFormCompanyName',
    'dealFormPhone',
    'dealFormEmail',
    'dealFormCountry',
    'dealFormLeadSource',
    'dealFormServiceInterest',
    'dealFormStage',
    'dealNextFollowUpAtInput',
    'dealLastContactedDateInput',
    'dealFormPriority',
    'dealFormEstimatedValue',
    'dealFormCurrency',
    'dealFormAssignedTo',
    'dealFormConvertedBy',
    'dealFormConvertedAt',
    'dealFormNotes',
    'dealNotesHistoryList',
    'proposalsSearchInput',
    'proposalsStatusFilter',
    'proposalsCustomerFilter',
    'proposalsExportCsvBtn',
    'proposalsRefreshBtn',
    'proposalsCreateBtn',
    'proposalsAnalytics',
    'proposalsAnalyticsGrid',
    'proposalsKpiTotal',
    'proposalsKpiDraft',
    'proposalsKpiSent',
    'proposalsKpiApproved',
    'proposalsKpiRejected',
    'proposalsKpiExpired',
    'proposalsKpiUniqueCustomers',
    'proposalsKpiLinkedDeals',
    'proposalsKpiAvgGrandTotal',
    'proposalsKpiGrandTotal',
    'proposalsKpiGrandTotalSub',
    'proposalsKpiSaasTotal',
    'proposalsKpiSaasTotalSub',
    'proposalsKpiOneTimeTotal',
    'proposalsKpiOneTimeTotalSub',
    'proposalsStatusDistribution',
    'proposalsCurrencyDistribution',
    'proposalsGeneratedByDistribution',
    'proposalCatalogSearchInput',
    'proposalCatalogSectionFilter',
    'proposalCatalogActiveFilter',
    'proposalCatalogSortFilter',
    'proposalCatalogRefreshBtn',
    'proposalCatalogCreateBtn',
    'proposalCatalogState',
    'proposalCatalogSummary',
    'proposalCatalogTable',
    'proposalCatalogTbody',
    'proposalCatalogFormModal',
    'proposalCatalogForm',
    'proposalCatalogFormTitle',
    'proposalCatalogFormCloseBtn',
    'proposalCatalogFormCancelBtn',
    'proposalCatalogFormSaveBtn',
    'proposalCatalogFormDeleteBtn',
    'proposalCatalogFormItemId',
    'proposalCatalogFormIsActive',
    'proposalCatalogFormSection',
    'proposalCatalogFormCategory',
    'proposalCatalogFormItemName',
    'proposalCatalogFormLocation',
    'proposalCatalogFormUnitPrice',
    'proposalCatalogFormDiscountPercent',
    'proposalCatalogFormQuantity',
    'proposalCatalogFormCapabilityName',
    'proposalCatalogFormCapabilityValue',
    'proposalCatalogFormSortOrder',
    'proposalCatalogFormNotes',
    'proposalsState',
    'proposalsTable',
    'proposalsTbody',
    'proposalFormModal',
    'proposalForm',
    'proposalFormTitle',
    'proposalFormCloseBtn',
    'proposalFormCancelBtn',
    'proposalFormSaveBtn',
    'proposalFormDeleteBtn',
    'proposalFormPreviewBtn',
    'proposalFormProposalId',
    'proposalFormTitleField',
    'proposalFormDealId',
    'proposalFormProposalDate',
    'proposalFormValidUntil',
    'proposalFormStatus',
    'proposalFormCurrency',
    'proposalSignedDocumentSection',
    'proposalSignedDocumentState',
    'proposalSignedDocumentFile',
    'proposalSignedDocumentUploadBtn',
    'proposalSignedDocumentOpenBtn',
    'proposalFormCustomerName',
    'proposalFormCustomerAddress',
    'proposalFormCustomerContactName',
    'proposalFormCustomerContactMobile',
    'proposalFormCustomerContactEmail',
    'proposalFormProviderContactName',
    'proposalFormProviderContactMobile',
    'proposalFormProviderContactEmail',
    'proposalFormServiceStartDate',
    'proposalFormContractTerm',
    'proposalFormAccountNumber',
    'proposalFormBillingFrequency',
    'proposalFormPaymentTerm',
    'proposalFormPoNumber',
    'proposalFormIsPoc',
    'proposalPocDetails',
    'proposalFormPocLocationCount',
    'proposalFormPocLicenseCount',
    'proposalFormPocLicenseMonths',
    'proposalFormPocServiceStartDate',
    'proposalFormPocServiceEndDate',
    'proposalFormPocSuccessKpis',
    'proposalFormPocConversionCommitment',
    'proposalFormCustomerSignatoryName',
    'proposalFormCustomerSignatoryTitle',
    'proposalFormProviderSignatoryName',
    'proposalFormProviderSignatoryTitle',
    'proposalFormProviderSignDate',
    'proposalFormInternalNotes',
    'proposalFormTerms',
    'proposalResetTermsBtn',
    'proposalAnnualItemsTbody',
    'proposalOneTimeItemsTbody',
    'proposalHardwareItemsTbody',
    'proposalCapabilityItemsTbody',
    'proposalAddAnnualRowBtn',
    'proposalAddOneTimeRowBtn',
    'proposalAddHardwareRowBtn',
    'proposalAddCapabilityRowBtn',
    'proposalSaasTotal',
    'proposalOneTimeTotal',
    'proposalHardwareTotal',
    'proposalGrandTotal',
    'proposalPreviewModal',
    'proposalPreviewTitle',
    'proposalPreviewExportPdfBtn',
    'proposalPreviewCloseBtn',
    'proposalPreviewFrame',
    'agreementsSummary',
    'agreementsSearchInput',
    'agreementsStatusFilter',
    'agreementsProposalDealFilter',
    'agreementsCreateFromProposalInput',
    'agreementsExportCsvBtn',
    'agreementsRefreshBtn',
    'agreementsCreateBtn',
    'agreementsImportOldClientBtn',
    'agreementsState',
    'agreementsTable',
    'agreementsTbody',
    'agreementFormIsPoc',
    'agreementFormIsPocToggle',
    'agreementPocDetails',
    'agreementFormPocLocationCount',
    'agreementFormPocLicenseMonths',
    'agreementFormPocServiceStartDate',
    'agreementFormPocServiceEndDate',
    'agreementFormPocSuccessKpis',
    'agreementFormPocConversionCommitment',


    'agreementOperationsCard',
    'agreementOperationsSummary',
    'agreementOperationsSendBtn',

    'agreementOperationsAssignCsmBtn',
    'agreementOperationsUpdateStatusBtn',
    'agreementFormModal',
    'agreementForm',
    'agreementFormTitle',
    'agreementFormCloseBtn',
    'agreementFormCancelBtn',
    'agreementFormSaveBtn',
    'agreementFormDeleteBtn',
    'agreementFormPreviewBtn',
    'agreementSignedLockMessage',
    'agreementSignedDocumentSection',
    'agreementSignedDocumentState',
    'agreementSignedDocumentFile',
    'agreementSignedDocumentUploadBtn',
    'agreementSignedDocumentOpenBtn',
    'agreementFormAgreementId',
    'agreementFormAgreementNumber',
    'agreementFormProposalId',
    'agreementFormDealId',
    'agreementFormLeadId',
    'agreementFormAgreementTitle',
    'agreementFormAgreementDate',
    'agreementFormEffectiveDate',
    'agreementFormServiceStartDate',
    'agreementFormAgreementLength',
    'agreementFormAccountNumber',
    'agreementFormBillingFrequency',
    'agreementFormPaymentTerm',
    'agreementFormPoNumber',
    'agreementFormCurrency',
    'agreementFormCustomerName',
    'agreementFormCustomerLegalName',
    'agreementFormCustomerAddress',
    'agreementFormCustomerContactName',
    'agreementFormCustomerContactMobile',
    'agreementFormCustomerContactEmail',
    'agreementFormProviderName',
    'agreementFormProviderLegalName',
    'agreementFormProviderAddress',
    'agreementFormProviderContactName',
    'agreementFormProviderContactMobile',
    'agreementFormProviderContactEmail',
    'agreementFormStatus',
    'agreementFormTermsConditions',
    'agreementFormCustomerOfficialSignatoryName',
    'agreementFormCustomerOfficialSignatoryTitle',
    'agreementFormCustomerOfficialSignDate',
    'agreementFormCustomerSignatoryName',
    'agreementFormCustomerSignatoryTitle',
    'agreementFormProviderOfficialSignatory1Name',
    'agreementFormProviderOfficialSignatory1Title',
    'agreementFormProviderOfficialSignatory1SignDate',
    'agreementFormProviderOfficialSignatory2Name',
    'agreementFormProviderOfficialSignatory2Title',
    'agreementFormProviderOfficialSignatory2SignDate',
    'agreementFormProviderSignatoryNamePrimary',
    'agreementFormProviderSignatoryTitlePrimary',
    'agreementFormProviderSignatoryNameSecondary',
    'agreementFormProviderSignatoryTitleSecondary',
    'agreementFormProviderSignDate',
    'agreementFormCustomerSignDate',
    'agreementFormGeneratedBy',
    'agreementFormNotes',
    'agreementAnnualItemsTbody',
    'agreementOneTimeItemsTbody',
    'agreementHardwareItemsTbody',
    'agreementCapabilityItemsTbody',
    'agreementAddAnnualRowBtn',
    'agreementAddOneTimeRowBtn',
    'agreementAddHardwareRowBtn',
    'agreementAddCapabilityRowBtn',
    'agreementSaasTotal',
    'agreementOneTimeTotal',
    'agreementHardwareTotal',
    'agreementGrandTotal',
    'agreementPreviewModal',
    'agreementPreviewTitle',
    'agreementPreviewExportPdfBtn',
    'agreementPreviewCloseBtn',
    'agreementPreviewFrame',
    'invoiceSummary',
    'invoicesSearchInput',
    'invoicesStatusFilter',
    'invoicesRefreshBtn',
    'invoicesCreateBtn',
    'invoicesState',
    'invoicesTable',
    'invoicesTbody',
    'invoiceFormModal',
    'invoiceForm',
    'invoiceFormTitle',
    'invoiceFormCloseBtn',
    'invoiceFormCancelBtn',
    'invoiceFormSaveBtn',
    'invoiceFormDeleteBtn',
    'invoiceFormPreviewBtn',
    'invoiceFormInvoiceId',
    'invoiceFormInvoiceNumber',
    'invoiceFormAgreementUuid',
    'invoiceFormAgreementId',
    'invoiceFormAgreementNumber',
    'invoiceFormInvoiceDate',
    'invoiceFormDueDate',
    'invoiceFormCustomerName',
    'invoiceFormCustomerLegalName',
    'invoiceFormCustomerAddress',
    'invoiceFormCustomerContactName',
    'invoiceFormCustomerContactEmail',
    'invoiceFormPaymentTerm',
    'invoiceFormPaymentTermsCustomWrap',
    'invoiceFormPaymentTermsCustom',
    'invoiceFormCurrency',
    'invoiceFormStatus',
    'invoiceFormSubtotalSubscription',
    'invoiceFormSubtotalOneTime',
    'invoiceFormGrandTotal',
    'invoiceFormOldPaidTotal',
    'invoiceFormPaidNow',
    'invoiceFormAmountPaidWrap',
    'invoiceFormAmountPaid',
    'invoiceFormPendingAmountWrap',
    'invoiceFormPendingAmount',
    'invoiceFormPaymentState',
    'invoicePaymentConclusion',
    'invoiceAgreementLocationSelectionSection',
    'invoiceAgreementLocationSelectionBody',
    'invoiceAccountSetupBillingOptions',
    'invoiceAccountSetupBillingPerSelected',
    'invoiceAccountSetupBillingFullFirst',
    'invoiceAccountSetupBillingNote',
    'invoiceFormPaymentScheduleMode',
    'invoicePaymentScheduleAddRowBtn',
    'invoicePaymentScheduleState',
    'invoicePaymentScheduleTbody',
    'invoiceReceiptsState',
    'invoiceReceiptsTbody',
    'invoiceFormAmountInWords',
    'invoiceFormNotes',
    'invoiceAnnualItemsTbody',
    'invoiceOneTimeItemsTbody',
    'invoiceHardwareItemsTbody',
    'invoiceCapabilityItemsTbody',
    'invoiceAddAnnualRowBtn',
    'invoiceAddOneTimeRowBtn',
    'invoiceAddHardwareRowBtn',
    'invoiceAddCapabilityRowBtn',
    'invoicePreviewModal',
    'invoicePreviewTitle',
    'invoicePreviewExportPdfBtn',
    'invoicePreviewCloseBtn',
    'invoicePreviewFrame',
    'leadFormModal',
    'leadForm',
    'leadFormTitle',
    'leadFormCloseBtn',
    'leadFormCancelBtn',
    'leadFormSaveBtn',
    'leadFormDeleteBtn',
    'leadFormLeadId',
    'leadFormCreatedAt',
    'leadFormCompanyId',
    'leadFormCompanyName',
    'leadFormContactId',
    'leadFormContactName',
    'leadFormContactEmail',
    'leadFormContactPhone',
    'leadFormPhone',
    'leadFormEmail',
    'leadFormCountry',
    'leadCompanyLegalName',
    'leadCompanyType',
    'leadCompanyIndustry',
    'leadCompanyWebsite',
    'leadCompanyMainEmail',
    'leadCompanyMainPhone',
    'leadCompanyCountry',
    'leadCompanyCity',
    'leadCompanyAddress',
    'leadCompanyTaxNumber',
    'leadCompanyStatus',
    'leadCompanySource',
    'leadCompanyOwnerName',
    'leadCompanyOwnerEmail',
    'leadContactFirstName',
    'leadContactLastName',
    'leadContactJobTitle',
    'leadContactDepartment',
    'leadContactMobile',
    'leadContactDecisionRole',
    'leadContactPrimary',
    'leadContactStatus',
    'leadFormLeadSource',
    'leadFormServiceInterest',
    'leadFormStatus',
    'leadFormPriority',
    'leadFormEstimatedValue',
    'leadFormCurrency',
    'leadFormAssignedTo',
    'leadNextFollowUpAtInput',
    'leadFormLastContactDate',
    'leadFormNotes',
    'leadNotesHistoryList',
    'leadFormUpdatedAt',
    'userCreateForm',
    'userCreateName',
    'userCreateUsername',
    'userCreateEmail',
    'userCreateRole',
    'userCreatePassword',
    'userCreateSubmit',
    'userEditModal',
    'userEditForm',
    'userEditClose',
    'userEditCancel',
    'userEditName',
    'userEditUsername',
    'userEditEmail',
    'userEditRole',
    'userEditSubmit',
    'userResetPwdModal',
    'userResetPwdForm',
    'userResetPwdClose',
    'userResetPwdCancel',
    'userResetPwdPassword',
    'userResetPwdConfirmPassword',
    'userResetPwdSubmit',
    'rolePermissionsRefreshBtn',
    'rolePermissionsFiltersForm',
    'rolePermissionsSearchResource',
    'rolePermissionsSearchAction',
    'rolePermissionsSearchAllowedRoles',
    'rolePermissionsSearchText',
    'rolePermissionsState',
    'rpTotalRoles',
    'rpTotalRows',
    'rpTotalGrouped',
    'rpQuickNewRoleBtn',
    'rpQuickNewRuleBtn',
    'rpRoleCreateInlineBtn',
    'rpPermissionCreateInlineBtn',
    'rpRoleCreateForm',
    'rpRoleCreateKey',
    'rpRoleCreateDisplayName',
    'rpRoleCreateDescription',
    'rpRoleCreateIsActive',
    'rpRoleCreateSubmit',
    'rpRolesState',
    'rpRolesTable',
    'rpRolesTbody',
    'rolePermissionsTbody',
    'rolePermissionCreateForm',
    'rolePermissionCreateResource',
    'rolePermissionCreateAction',
    'rolePermissionCreateAllowedRoles',
    'rolePermissionCreateDescription',
    'tabPermissionBulkForm',
    'tabPermissionRole',
    'tabPermissionTarget',
    'tabPermissionExtraActions',
    'tabPermissionActionView',
    'tabPermissionActionGet',
    'tabPermissionActionList',
    'tabPermissionActionCreate',
    'tabPermissionActionSave',
    'tabPermissionActionUpdate',
    'tabPermissionActionDelete',
    'tabPermissionActionCancel',
    'tabPermissionActionPrint',
    'tabPermissionActionExport',
    'accentColor',
    'heroTriagePct',
    'heroHighImpactCount',
    'heroChangeReadiness',
    'shortcutsHelp',
    'eventAllDay',
    'eventEnv',
    'eventOwner',
    'eventStatus',
    'eventModules',
    'eventImpactType',
    // Release Planner IDs
    'plannerRegion',
    'plannerEnv',
    'plannerModules',
    'plannerHorizon',
    'plannerReleaseType',
    'plannerRun',
    'plannerResults',
    'plannerDescription',
    'plannerSlotsPerDay',
    'plannerReleasePlan',
    'plannerTickets',
    'plannerAssignBtn',
    'plannerAddEvent',
    'plannerExportScorecard',
    'releasePlannerCard',
    'freezeWindowsCard',
    'freezeManageBtn',
    'freezeManageBtnSecondary',
    'freezeWindowsList',
    'freezeModal',
    'freezeModalClose',
    'freezeModalList',
    'freezeForm',
    'freezeStart',
    'freezeEnd',
    'freezeReset'
    ,
  ].forEach(id => (E[id] = document.getElementById(id)));
}

/** UI helpers */


function canAnyPermission(pairs = []) {
  if (!window.Permissions || typeof Permissions.can !== 'function') return false;
  return (Array.isArray(pairs) ? pairs : []).some(([resource, action]) => Permissions.can(resource, action) === true);
}

function requireAnyPermission(pairs = [], message = 'You do not have permission for this action.') {
  if (canAnyPermission(pairs)) return true;
  if (window.UI?.toast) UI.toast(message);
  return false;
}

function canShowAction(resource, action) {
  if (!window.Permissions || typeof Permissions.can !== 'function') return false;
  return Permissions.can(resource, action) === true;
}

function setActionVisibility(element, resource, action) {
  if (!element) return;
  const allowed = canShowAction(resource, action);
  element.hidden = !allowed;
  element.disabled = !allowed;
  element.setAttribute('aria-hidden', String(!allowed));
  element.classList.toggle('is-permission-hidden', !allowed);
  element.style.display = allowed ? '' : 'none';
}

function applyPermissionVisibility(root = document) {
  const nodes = root.querySelectorAll('[data-permission-resource][data-permission-action]');
  nodes.forEach(node => {
    const resource = node.getAttribute('data-permission-resource');
    const action = node.getAttribute('data-permission-action');
    setActionVisibility(node, resource, action);
  });
}

const UI = {
  tabRegistry() {
    return [
      { key: 'issues', tabEl: E.issuesTab, viewEl: E.issuesView },
      { key: 'calendar', tabEl: E.calendarTab, viewEl: E.calendarView },
      { key: 'csm', tabEl: E.csmTab, viewEl: E.csmView },
      { key: 'clientSuccess', tabEl: E.clientSuccessTab, viewEl: E.clientSuccessView },
      { key: 'company', tabEl: E.companyTab, viewEl: E.companyView },
      { key: 'contacts', tabEl: E.contactsTab, viewEl: E.contactsView },
      { key: 'leads', tabEl: E.leadsTab, viewEl: E.leadsView },
      { key: 'deals', tabEl: E.dealsTab, viewEl: E.dealsView },
      { key: 'proposals', tabEl: E.proposalsTab, viewEl: E.proposalsView },
      { key: 'agreements', tabEl: E.agreementsTab, viewEl: E.agreementsView },
      { key: 'commissionTracker', tabEl: E.commissionTrackerTab, viewEl: E.commissionTrackerView },
      { key: 'invoices', tabEl: E.invoicesTab, viewEl: E.invoicesView },
      { key: 'receipts', tabEl: E.receiptsTab, viewEl: E.receiptsView },
      { key: 'creditNotes', tabEl: E.creditNotesTab, viewEl: E.creditNotesView },
      { key: 'paymentForecast', tabEl: E.paymentForecastTab, viewEl: E.paymentForecastView },
      { key: 'renewalForecast', tabEl: E.renewalForecastTab, viewEl: E.renewalForecastView },
      { key: 'hr', tabEl: E.hrTab, viewEl: E.hrView },
      { key: 'accounting', tabEl: E.accountingTab, viewEl: E.accountingView },
      { key: 'backupCenter', tabEl: E.backupCenterTab, viewEl: E.backupCenterView },
      { key: 'lifecycleAnalytics', tabEl: E.lifecycleAnalyticsTab, viewEl: E.lifecycleAnalyticsView },
      { key: 'clients', tabEl: E.clientsTab, viewEl: E.clientsView },
      { key: 'proposalCatalog', tabEl: E.proposalCatalogTab, viewEl: E.proposalCatalogView },
      { key: 'communicationCentre', tabEl: E.communicationCentreTab, viewEl: E.communicationCentreView },
      { key: 'notifications', tabEl: E.notificationsTab, viewEl: E.notificationsView },
      { key: 'notificationSetup', tabEl: E.notificationSetupTab, viewEl: E.notificationSetupView },
      { key: 'workflow', tabEl: E.workflowTab, viewEl: E.workflowView },
      { key: 'users', tabEl: E.usersTab, viewEl: E.usersView },
      { key: 'rolePermissions', tabEl: E.rolePermissionsTab, viewEl: E.rolePermissionsView }
    ];
  },
  toast(msg, ms = 3500) {
    if (!E.toast) return;
    const normalizedMsg = String(msg ?? '')
      .replace(/\\n/g, ' ')
      .replace(/\s*\n\s*/g, ' ')
      .trim();
    E.toast.textContent = normalizedMsg;
    E.toast.style.display = 'block';
    setTimeout(() => {
      if (E.toast) E.toast.style.display = 'none';
    }, ms);
  },
  spinner(v = true) {
    if (E.spinner) E.spinner.style.display = v ? 'flex' : 'none';
    if (E.loadingStatus) E.loadingStatus.textContent = v ? 'Loading…' : '';
  },
  setSync(which, ok, when) {
    const txt = which === 'issues' ? E.syncIssuesText : E.syncEventsText;
    const dot = which === 'issues' ? E.syncIssuesDot : E.syncEventsDot;
    if (!txt || !dot) return;
    const rawTimestamp = when == null ? '' : String(when).replace(/\s*\n\s*/g, ' ').trim();
    const formattedTimestamp = rawTimestamp ? U.fmtTS(rawTimestamp) : '';
    const syncTimestamp = formattedTimestamp && formattedTimestamp !== '—' ? formattedTimestamp : 'never';
    txt.textContent = `${which === 'issues' ? 'Tickets' : 'Events'}: ${syncTimestamp}`;
    dot.className = 'dot ' + (ok ? 'ok' : 'err');
  },
  applyRolePermissions() {
    const role = Session.role() || Session.authContext?.().profile?.role_key || 'guest';
    const displayName = Session.displayName() || Session.username() || 'guest';
    const canUseInternalIssueFilters = Permissions.canUseInternalIssueFilters();
    const canManageFreezeWindows = Permissions.canManageFreezeWindows();
    const canChangePlanner = Permissions.canChangePlanner();

    if (!canUseInternalIssueFilters) {
      Filters.state.devTeamStatus = 'All';
      Filters.state.issueRelated = 'All';
      Filters.save();
      setIfOptionExists(E.devTeamStatusFilter, 'All');
      setIfOptionExists(E.issueRelatedFilter, 'All');
    }

    if (E.currentUserChip) E.currentUserChip.textContent = displayName;
    if (E.currentRoleChip) E.currentRoleChip.textContent = String(role || 'guest').replace(/_/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
    if (E.currentUserAvatar) {
      const initials = String(displayName || 'Guest')
        .split(/\s+/)
        .filter(Boolean)
        .slice(0, 2)
        .map(part => part[0])
        .join('')
        .toUpperCase() || 'GU';
      E.currentUserAvatar.textContent = initials;
    }
    const tabRegistry = this.tabRegistry();
    console.info(
      '[Tabs] full registry before filtering',
      tabRegistry.map(rule => ({
        key: rule.key,
        tabFound: Boolean(rule.tabEl),
        viewFound: Boolean(rule.viewEl),
        currentDisplay: rule.tabEl?.style?.display ?? null
      }))
    );
    console.info('[Tabs] role used for filtering', { role });
    const visibleTabs = [];
    tabRegistry.forEach(rule => {
      let allowed = true;
      try {
        if (!rule.alwaysVisible) {
          allowed = Permissions.canAccessTab(rule.key);
        }
      } catch (error) {
        console.error(`[Tabs] permission check failed for "${rule.key}"`, error);
        allowed = rule.alwaysVisible || rule.key === 'issues';
      }
      if (rule.tabEl) rule.tabEl.style.display = allowed ? '' : 'none';
      if (allowed) visibleTabs.push(rule.key);
      if (!allowed && rule.viewEl?.classList.contains('active')) {
        const fallback = tabRegistry.find(candidate => candidate.key !== rule.key && Permissions.canAccessTab(candidate.key));
        if (fallback?.key) setActiveView(fallback.key);
        else rule.viewEl.classList.remove('active');
      }
    });
    console.log('[tabs] permission-aware filtering result', visibleTabs);
    if (['hoo', 'head_of_operations'].includes(Permissions.normalizeRole?.(role))) {
      const tabs = visibleTabs.map(key => ({ key }));
      const permissionMatrix = Permissions.state?.rows || [];
      console.log('[HOO ACCESS DEBUG]', {
        role,
        visibleTabs: tabs.map(t => t.key),
        activePermissions: permissionMatrix.filter(p =>
          ['hoo', 'head_of_operations'].includes(String(p.role_key || '').toLowerCase()) &&
          p.is_allowed === true &&
          p.is_active === true
        )
      });
    }
    if (E.addEventBtn) E.addEventBtn.style.display = Permissions.canManageEvents() ? '' : 'none';
    if (E.freezeManageBtn) E.freezeManageBtn.style.display = canManageFreezeWindows ? '' : 'none';
    if (E.freezeManageBtnSecondary) E.freezeManageBtnSecondary.style.display = canManageFreezeWindows ? '' : 'none';
    if (E.freezeWindowsCard) E.freezeWindowsCard.style.display = canManageFreezeWindows ? '' : 'none';
    if (E.plannerAddEvent) E.plannerAddEvent.style.display = canChangePlanner ? '' : 'none';
    if (E.plannerAssignBtn) E.plannerAssignBtn.style.display = canChangePlanner ? '' : 'none';
    if (E.releasePlannerCard) E.releasePlannerCard.style.display = canChangePlanner ? '' : 'none';
    if (E.editIssueBtn) E.editIssueBtn.style.display = Permissions.canEditTicket() ? '' : 'none';
    if (E.bulkEditBtn) E.bulkEditBtn.style.display = Permissions.canEditTicket() ? '' : 'none';
    applyPermissionVisibility(document);
    if (E.exportCsv) {
      const canExportTickets = Permissions.canExport('tickets');
      E.exportCsv.style.display = canExportTickets ? '' : 'none';
      E.exportCsv.disabled = !canExportTickets;
      if (!canExportTickets) {
        E.exportCsv.title = 'You do not have permission to export this data.';
      } else {
        E.exportCsv.removeAttribute('title');
      }
    }
    if (E.devTeamStatusFilterRow)
      E.devTeamStatusFilterRow.style.display = canUseInternalIssueFilters ? '' : 'none';
    if (E.issueRelatedFilterRow)
      E.issueRelatedFilterRow.style.display = canUseInternalIssueFilters ? '' : 'none';
    // Re-apply role-scoped column visibility immediately after login/logout
    // so viewer-restricted columns are hidden without requiring refresh.
    ColumnManager.renderPanel();
    ColumnManager.apply();
  },
  updateHeroMetrics(rows) {
    if (!E.heroTriagePct && !E.heroHighImpactCount && !E.heroChangeReadiness) return;
    const safeRows = Array.isArray(rows) ? rows : [];
    const parseDate = value => {
      if (!value) return null;
      const d = new Date(value);
      return isNaN(d) ? null : d;
    };

    const triageDurations = safeRows
      .map(r => {
        const created = parseDate(r.date);
        const triaged = parseDate(r.updatedAt || r.createdAt || r.date);
        if (!created || !triaged) return null;
        return (triaged - created) / 3600000;
      })
      .filter(v => v != null && v >= 0);

    const triageUnderTwo = triageDurations.filter(v => v <= 2).length;
    const triagePct = triageDurations.length
      ? Math.round((triageUnderTwo / triageDurations.length) * 100)
      : 0;
    if (E.heroTriagePct) E.heroTriagePct.textContent = `${triagePct}%`;

    const dailyHighImpact = safeRows.filter(r => {
      const created = parseDate(r.date);
      if (!created) return false;
      if (!U.isBetween(created, U.daysAgo(1), null)) return false;
      const meta = DataStore.computed.get(r.id);
      const impactScore = meta?.risk?.impact ?? 0;
      return impactScore >= 4 || r.priority === 'High';
    }).length;
    if (E.heroHighImpactCount) E.heroHighImpactCount.textContent = String(dailyHighImpact);

    const reviewDurations = safeRows
      .map(r => {
        const created = parseDate(r.date);
        const reviewed = parseDate(r.updatedAt || r.createdAt || r.date);
        if (!created || !reviewed) return null;
        return (reviewed - created) / 3600000;
      })
      .filter(v => v != null && v >= 0);
    const avgReviewHours = reviewDurations.length
      ? reviewDurations.reduce((a, b) => a + b, 0) / reviewDurations.length
      : 0;
    const baselineHours = 24;
    const speed = avgReviewHours ? baselineHours / avgReviewHours : 0;
    if (E.heroChangeReadiness) {
      E.heroChangeReadiness.textContent = `${speed ? speed.toFixed(1) : '0'}x`;
    }
  },
  skeleton(show) {
    if (!E.issuesTbody || !E.tbodySkeleton) return;
    E.tbodySkeleton.style.display = show ? '' : 'none';
    E.issuesTbody.style.display = show ? 'none' : '';
  }
};

const GridState = {
  sortKey: 'date',
  sortAsc: false,
  page: 1,
  pageSize: +(localStorage.getItem(LS_KEYS.pageSize) || 50)
};

function buildIssueCategoryOptions(extra = []) {
  const allowedCategories = ['Bug', 'Enhancement', 'New Features'];
  const selectedExtras = extra
    .filter(Boolean)
    .map(v => String(v).trim().toLowerCase())
    .filter(v => allowedCategories.includes(v));
  return [...new Set([...allowedCategories, ...selectedExtras])];
}

window.canShowAction = canShowAction;
window.setActionVisibility = setActionVisibility;
window.applyPermissionVisibility = applyPermissionVisibility;
window.canAnyPermission = canAnyPermission;
window.requireAnyPermission = requireAnyPermission;
