(function installCrmMultiContact(global){
'use strict';
const VERSION='20260912-crm-multi-contact1';
const ROLES=['Decision Maker','Influencer','Technical','Finance','Operations','Quality','Procurement','Other'];
const CFG={lead:{ctl:'Leads',table:'lead_contacts',parent:'lead_id',form:'leadForm',modal:'leadFormModal',field:'leadAdditionalContactsField',search:'leadAdditionalContactsSearch',list:'leadAdditionalContactsList',count:'leadAdditionalContactsCount'},deal:{ctl:'Deals',table:'deal_contacts',parent:'deal_id',form:'dealForm',modal:'dealFormModal',field:'dealAdditionalContactsField',search:'dealAdditionalContactsSearch',list:'dealAdditionalContactsList',count:'dealAdditionalContactsCount'}};
const S={lead:state(),deal:state()}; let tries=0;
function state(){return {id:'',companyId:'',companyName:'',primary:'',contacts:[],selected:new Map(),loading:false,token:0};}
const clean=v=>String(v??'').replace(/\s+/g,' ').trim(); const norm=v=>clean(v).toLowerCase();
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clean(v));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
function db(){try{return global.SupabaseClient?.getClient?.()||null}catch{return null}}
function ctl(m){return global[CFG[m].ctl]||null}
function open(m){const f=document.getElementById(CFG[m].form);if(!f)return false;const modal=document.getElementById(CFG[m].modal);return !modal||(modal.getAttribute('aria-hidden')!=='true'&&modal.style.display!=='none')}
function firstUuid(values){return clean(values.find(uuid)||'')}
function primary(m,row){const c=ctl(m);return m==='lead'?firstUuid([c?.state?.selectedContact?.contact_uuid,c?.state?.selectedContact?.id,document.getElementById('leadFormContactId')?.value,row?.contact_uuid,row?.contact_id]):firstUuid([c?.state?.selectedContact?.id,c?.state?.selectedContact?.contact_uuid,row?.contact_id,document.getElementById('dealContactIdDisplay')?.value])}
function company(m,row){const c=ctl(m),x=c?.state?.selectedCompany||{};return m==='lead'?{id:firstUuid([x.company_uuid,x.id,document.getElementById('leadFormCompanyId')?.value,row?.company_uuid,row?.company_id]),name:clean(x.company_name||x.legal_name||document.getElementById('leadFormCompanyName')?.value||row?.company_name||row?.customer_legal_name)}:{id:firstUuid([x.company_uuid,x.id,row?.company_id,document.getElementById('dealCompanyIdDisplay')?.value]),name:clean(x.company_name||x.legal_name||row?.company_name||row?.customer_legal_name||document.getElementById('dealCompanyNameDisplay')?.value)}}
function parentId(m,row){const c=ctl(m);return firstUuid([row?.id,m==='lead'?c?.state?.currentLead?.id:c?.state?.currentDeal?.id,m==='lead'?c?.state?.selectedLeadId:c?.state?.selectedDealId])}
function styles(){if(document.getElementById('crmMultiContactStyles'))return;const s=document.createElement('style');s.id='crmMultiContactStyles';s.textContent='.crm-multi-contact{grid-column:1/-1;border:1px solid var(--border,#d8dee9);border-radius:12px;padding:12px;margin-top:4px;background:var(--surface,#fff)}.crm-multi-head{display:flex;justify-content:space-between;gap:10px;margin-bottom:7px}.crm-multi-help,.crm-multi-count{font-size:12px;opacity:.72}.crm-multi-search{width:100%;margin:7px 0}.crm-multi-list{display:grid;gap:6px;max-height:240px;overflow:auto}.crm-multi-row{display:grid;grid-template-columns:auto minmax(0,1fr) minmax(130px,180px);gap:8px;align-items:center;padding:8px;border:1px solid var(--border,#e1e6ef);border-radius:9px;background:var(--surface-2,#fafbfc)}.crm-multi-person{min-width:0}.crm-multi-person strong,.crm-multi-person span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.crm-multi-person span{font-size:11px;opacity:.72}.crm-multi-primary,.crm-contact-count-chip{font-size:10px;font-weight:700;padding:2px 6px;border:1px solid currentColor;border-radius:999px;margin-left:6px}.crm-contact-count-chip{font-size:11px;display:inline-flex;white-space:nowrap}body.dark-mode .crm-multi-contact,.dark .crm-multi-contact{background:var(--surface,#111827)}body.dark-mode .crm-multi-row,.dark .crm-multi-row{background:var(--surface-2,#172033)}@media(max-width:720px){.crm-multi-row{grid-template-columns:auto minmax(0,1fr)}.crm-multi-role{grid-column:2}}';document.head.appendChild(s)}
function anchor(m){const ids=m==='lead'?['leadFormContactPhone','leadContactPrimary','leadFormContactName','leadFormStatus']:['dealContactPhoneDisplay','dealContactIdDisplay','dealFormStage'];for(const id of ids){const n=document.getElementById(id);if(n)return n.closest('.form-field,.field,.form-group,.input-group,label')||n}return document.getElementById(CFG[m].form)}
function field(m){styles();const c=CFG[m];let f=document.getElementById(c.field);if(f)return f;const form=document.getElementById(c.form);if(!form)return null;f=document.createElement('section');f.id=c.field;f.className='crm-multi-contact';f.innerHTML=`<div class="crm-multi-head"><strong>Linked Contacts</strong><span id="${c.count}" class="crm-multi-count">0 linked</span></div><div class="crm-multi-help">Primary Contact stays the main contact. Select additional contacts from the same company and optionally assign an opportunity role.</div><input id="${c.search}" class="input crm-multi-search" type="search" placeholder="Search company contacts…"><div id="${c.list}" class="crm-multi-list"><span class="muted">Select a company to load contacts.</span></div>`;const a=anchor(m);if(a?.parentNode&&a!==form)a.parentNode.insertBefore(f,a.nextSibling);else form.appendChild(f);return f}
function label(c){return clean(c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' '))||clean(c.contact_id)||'Unnamed contact'}
function meta(c){return [c.job_title,c.department,c.email,c.mobile||c.phone].map(clean).filter(Boolean).join(' · ')}
function roleOptions(selected){return [''].concat(ROLES).map(r=>`<option value="${esc(r)}"${r===selected?' selected':''}>${esc(r||'Opportunity role — optional')}</option>`).join('')}
function filter(m){const c=CFG[m],q=norm(document.getElementById(c.search)?.value);document.querySelectorAll(`#${c.list} [data-multi-row]`).forEach(r=>r.hidden=!!(q&&!norm(r.dataset.search).includes(q)))}
function render(m){const c=CFG[m],s=S[m];field(m);const list=document.getElementById(c.list),count=document.getElementById(c.count);if(!list)return;const ids=new Set(s.selected.keys());if(s.primary)ids.add(s.primary);const add=[...ids].filter(id=>id!==s.primary).length;if(count)count.textContent=`${ids.size} linked${add?` · +${add} additional`:''}`;if(s.loading){list.innerHTML='<span class="muted">Loading company contacts…</span>';return}if(!s.companyId&&!s.companyName){list.innerHTML='<span class="muted">Select a company to load contacts.</span>';return}if(!s.contacts.length){list.innerHTML='<span class="muted">No contacts found for this company.</span>';return}const rows=s.contacts.slice().sort((a,b)=>(a.id===s.primary?0:s.selected.has(a.id)?1:2)-(b.id===s.primary?0:s.selected.has(b.id)?1:2)||label(a).localeCompare(label(b)));list.innerHTML=rows.map(x=>{const id=clean(x.id),p=id===s.primary,on=p||s.selected.has(id),role=s.selected.get(id)?.role||'';return `<label class="crm-multi-row" data-multi-row data-search="${esc(norm(`${label(x)} ${meta(x)} ${x.contact_id||''}`))}"><input type="checkbox" data-multi-check="${esc(id)}"${on?' checked':''}${p?' disabled':''}><span class="crm-multi-person"><strong>${esc(label(x))}${p?'<span class="crm-multi-primary">Primary</span>':''}</strong><span>${esc(meta(x)||x.contact_id||'')}</span></span><select class="input crm-multi-role" data-multi-role="${esc(id)}"${on?'':' disabled'}>${roleOptions(role)}</select></label>`}).join('');filter(m)}
async function links(m,id){if(!uuid(id))return[];const c=CFG[m],x=db();if(!x)return[];const {data,error}=await x.from(c.table).select('contact_id,is_primary,opportunity_role').eq(c.parent,id);if(error)throw error;return data||[]}
async function contacts(companyId,companyName,linked=[]){const x=db();if(!x)return[];const cols='id,contact_id,company_id,company_ids,company_name,full_name,first_name,last_name,job_title,department,email,phone,mobile,decision_role,is_primary_contact,contact_status',found=new Map();async function merge(q){const {data,error}=await q;if(error)throw error;(data||[]).forEach(r=>{if(uuid(r.id))found.set(r.id,r)})}if(uuid(companyId))await Promise.all([merge(x.from('contacts').select(cols).eq('company_id',companyId).order('full_name')),merge(x.from('contacts').select(cols).contains('company_ids',[companyId]).order('full_name'))]);else if(companyName)await merge(x.from('contacts').select(cols).ilike('company_name',companyName).order('full_name'));const missing=linked.filter(id=>uuid(id)&&!found.has(id));if(missing.length)await merge(x.from('contacts').select(cols).in('id',missing));return [...found.values()]}
async function load(m,row=null){if(!open(m))return;field(m);const s=S[m],t=++s.token,co=company(m,row);s.id=parentId(m,row);s.companyId=co.id;s.companyName=co.name;s.primary=primary(m,row);s.loading=true;s.selected=new Map();render(m);try{const ls=await links(m,s.id);if(t!==s.token)return;ls.forEach(l=>{if(uuid(l.contact_id)){s.selected.set(l.contact_id,{role:clean(l.opportunity_role),primary:!!l.is_primary});if(l.is_primary&&!s.primary)s.primary=l.contact_id}});if(s.primary&&!s.selected.has(s.primary))s.selected.set(s.primary,{role:'',primary:true});s.contacts=await contacts(s.companyId,s.companyName,[...s.selected.keys()]);}catch(e){console.error('[crm multi contact] load failed',e);s.contacts=[]}finally{if(t===s.token){s.loading=false;render(m)}}}
function snapshot(m){if(!open(m))return null;const s=S[m],p=primary(m)||s.primary,ids=new Set(s.selected.keys());if(uuid(p))ids.add(p);return {rows:[...ids].filter(uuid).map(id=>({contactId:id,isPrimary:id===p,role:ROLES.includes(clean(s.selected.get(id)?.role))?clean(s.selected.get(id)?.role):null}))}}
async function sync(m,id,snap){if(!snap||!uuid(id))return;const c=CFG[m],x=db();if(!x)throw new Error('Supabase client unavailable');const {data:old,error:e0}=await x.from(c.table).select('contact_id').eq(c.parent,id);if(e0)throw e0;const {error:e1}=await x.from(c.table).update({is_primary:false,updated_at:new Date().toISOString()}).eq(c.parent,id).eq('is_primary',true);if(e1)throw e1;if(snap.rows.length){const payload=snap.rows.map(r=>({[c.parent]:id,contact_id:r.contactId,is_primary:r.isPrimary,opportunity_role:r.role,updated_at:new Date().toISOString()}));const {error}=await x.from(c.table).upsert(payload,{onConflict:`${c.parent},contact_id`});if(error)throw error}const keep=snap.rows.map(r=>r.contactId),removed=(old||[]).map(r=>clean(r.contact_id)).filter(cid=>uuid(cid)&&!keep.includes(cid));if(removed.length){const {error}=await x.from(c.table).delete().eq(c.parent,id).in('contact_id',removed);if(error)throw error}}
function resultId(r,fallback=''){return firstUuid([r?.id,r?.row?.id,r?.data?.id,r?.lead?.id,r?.deal?.id,fallback])}
function wrap(m){const c=ctl(m);if(!c)return false;const mark=`__crmMulti_${VERSION}`;if(c[mark])return true;const oo=c.openForm;if(typeof oo==='function')c.openForm=async function(row=null){const r=await oo.call(this,row);global.setTimeout(()=>load(m,row),0);return r};const cn=m==='lead'?'createLead':'createDeal',un=m==='lead'?'updateLead':'updateDeal',oc=c[cn];if(typeof oc==='function')c[cn]=async function(record={}){const s=snapshot(m),r=await oc.call(this,record),id=resultId(r);if(s&&id)await sync(m,id,s);gridLater(m);return r};const ou=c[un];if(typeof ou==='function')c[un]=async function(id,updates={}){const s=snapshot(m),r=await ou.call(this,id,updates),rid=resultId(r,id);if(s&&rid)await sync(m,rid,s);gridLater(m);return r};const or=c.render;if(typeof or==='function')c.render=function(...a){const r=or.apply(this,a);gridLater(m);return r};c[mark]=true;return true}
async function countMap(m){const c=CFG[m],x=db(),map=new Map();if(!x)return map;const {data,error}=await x.from(c.table).select(`${c.parent},contact_id,is_primary`);if(error)return map;(data||[]).forEach(r=>{const id=clean(r[c.parent]);if(!uuid(id))return;const z=map.get(id)||{total:0,primary:0};z.total++;if(r.is_primary)z.primary++;map.set(id,z)});return map}
async function grid(m){const host=document.getElementById(m==='lead'?'leadsGridView':'dealsGridView');if(!host||host.hidden)return;const map=await countMap(m);host.querySelectorAll('[data-crm-grid-record]').forEach(card=>{const z=map.get(clean(card.dataset.crmGridRecord))||{total:0,primary:0},add=Math.max(0,z.total-Math.min(1,z.primary||(z.total?1:0)));let chip=card.querySelector('.crm-contact-count-chip');if(!add){chip?.remove();return}if(!chip){chip=document.createElement('span');chip.className='crm-contact-count-chip';const st=card.querySelector('.ic-crm-card-status');st?.parentNode?st.parentNode.insertBefore(chip,st.nextSibling):card.prepend(chip)}chip.textContent=`+${add} contact${add===1?'':'s'}`;chip.title=`${z.total} linked contacts including primary`})}
function gridLater(m){global.setTimeout(()=>grid(m),90);global.setTimeout(()=>grid(m),260)}
function events(){if(global.__crmMultiEvents)return;global.__crmMultiEvents=true;document.addEventListener('input',e=>{for(const m of Object.keys(CFG))if(e.target?.id===CFG[m].search)filter(m)});document.addEventListener('change',e=>{const ch=e.target?.closest?.('[data-multi-check]');if(ch){const m=ch.closest(`#${CFG.lead.field}`)?'lead':ch.closest(`#${CFG.deal.field}`)?'deal':'';if(!m)return;const id=clean(ch.dataset.multiCheck),s=S[m];if(ch.checked)s.selected.set(id,s.selected.get(id)||{role:'',primary:false});else if(id!==s.primary)s.selected.delete(id);render(m);return}const ro=e.target?.closest?.('[data-multi-role]');if(ro){const m=ro.closest(`#${CFG.lead.field}`)?'lead':ro.closest(`#${CFG.deal.field}`)?'deal':'';if(!m)return;const id=clean(ro.dataset.multiRole),old=S[m].selected.get(id)||{role:'',primary:id===S[m].primary};S[m].selected.set(id,{...old,role:ROLES.includes(ro.value)?ro.value:''});return}if(['leadFormContactId','leadFormCompanyId'].includes(e.target?.id))global.setTimeout(()=>load('lead',ctl('lead')?.state?.currentLead||null),40);if(['dealContactIdDisplay','dealCompanyIdDisplay'].includes(e.target?.id))global.setTimeout(()=>load('deal',ctl('deal')?.state?.currentDeal||null),40)},true);document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-crm-view-key][data-crm-view-mode="grid"]');if(!b)return;if(b.dataset.crmViewKey==='leads')gridLater('lead');if(b.dataset.crmViewKey==='deals')gridLater('deal')})}
function patch(){styles();events();return wrap('lead')&&wrap('deal')}
function boot(){if(patch()){gridLater('lead');gridLater('deal');return}if(tries++<120)global.setTimeout(boot,150)}
global.InCheck360CrmMultiContact=Object.freeze({version:VERSION,roles:ROLES.slice(),refreshLead:()=>load('lead',ctl('lead')?.state?.currentLead||null),refreshDeal:()=>load('deal',ctl('deal')?.state?.currentDeal||null),refreshGrid:()=>{gridLater('lead');gridLater('deal')}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window);
