(function installEmployeeCalendar(global){
'use strict';
const S={db:null,user:'',profile:null,people:[],peopleMap:new Map(),settings:null,shares:[],owners:new Set(),cal:null,summary:[],ready:null,bound:false,timer:0};
const TYPES=['Meeting','Call','Follow-up','Task','Deadline','Reminder','Personal','Other'];
const STATUSES=['Planned','Confirmed','Completed','Cancelled'];
const COLORS={Meeting:'#155eef',Call:'#7c3aed','Follow-up':'#0f9f6e',Task:'#0f766e',Deadline:'#dc2626',Reminder:'#d97706',Personal:'#64748b',Other:'#475569'};
const REMINDERS=[[-1,'None'],[0,'At start time'],[5,'5 minutes before'],[15,'15 minutes before'],[30,'30 minutes before'],[60,'1 hour before'],[120,'2 hours before'],[240,'4 hours before'],[1440,'1 day before'],[2880,'2 days before'],[10080,'1 week before']];
const $=id=>document.getElementById(id); const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m,t='info'){try{if(global.UI?.toast)return global.UI.toast(m,t);if(global.U?.toast)return global.U.toast(m,t)}catch(_){} console[t==='error'?'error':'log']('[calendar]',m)}
function db(){const x=global.SupabaseClient?.getClient?.()||global.supabaseClient||global.supabase;if(!x?.from)throw Error('Supabase client is unavailable');return x}
function tz(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}catch(_){return'UTC'}}
function personName(id){if(String(id)===S.user)return S.profile?.display_name||'My Calendar';return S.peopleMap.get(String(id))?.display_name||'Shared Calendar'}
function initials(n){const p=clean(n).split(' ').filter(Boolean);return((p[0]?.[0]||'')+(p[1]?.[0]||p[0]?.[1]||'')).toUpperCase()}
function localInput(v){const d=v?new Date(v):new Date();if(isNaN(d))return'';const z=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function dayKey(v){const d=new Date(v),z=n=>String(n).padStart(2,'0');return isNaN(d)?'':`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function fmt(v){const d=new Date(v);return isNaN(d)?'—':new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function reminderHTML(v=-1){return REMINDERS.map(([x,l])=>`<option value="${x}" ${Number(v)===x?'selected':''}>${l}</option>`).join('')}
function incoming(){return S.shares.filter(x=>x.is_active&&String(x.shared_with_user_id)===S.user)}
function outgoing(){return S.shares.filter(x=>x.is_active&&String(x.owner_user_id)===S.user)}
function canEdit(owner){return String(owner)===S.user||incoming().some(x=>String(x.owner_user_id)===String(owner)&&x.access_level==='edit')}
function ensureTab(){let t=$('employeeCalendarTab');const a=$('dealsTab')||$('leadsTab')||$('contactsTab')||$('companyTab');const host=a?.closest('.view-menu-group')?.querySelector(':scope>.view-menu-group-body')||a?.parentElement||document.querySelector('.view-tabs');if(!host)return null;if(!t){t=document.createElement('button');t.id='employeeCalendarTab';t.type='button';t.className='view-tab';t.dataset.view='employeeCalendar';t.setAttribute('aria-selected','false');t.innerHTML='<span class="icon" aria-hidden="true">🗓️</span><span>Calendar</span>';a?.parentElement===host?a.insertAdjacentElement('afterend',t):host.appendChild(t)}t.hidden=false;t.style.removeProperty('display');return t}
function ensureView(){let v=$('employeeCalendarView');if(v)return v;const host=document.querySelector('.content-panels')||document.querySelector('.content');if(!host)return null;v=document.createElement('section');v.id='employeeCalendarView';v.className='view ec-page';v.hidden=true;v.innerHTML=`
<div class="ec-head"><div><div class="ec-eyebrow">CRM / Employee Calendar</div><h1>Calendar</h1><p>Your work calendar is private by default. Share it only with colleagues you choose.</p></div><div class="ec-actions"><button class="btn" id="ecRefresh">↻ Refresh</button><button class="btn" id="ecSettings">⚙ Settings</button><button class="btn" id="ecShare">👥 Share Calendar</button><button class="btn primary" id="ecNew">＋ New Item</button></div></div>
<div class="ec-kpis"><article><span>Today</span><strong id="ecToday">0</strong><small>calendar items</small></article><article><span>Next 7 Days</span><strong id="ecWeek">0</strong><small>upcoming items</small></article><article><span>Shared With Me</span><strong id="ecIncoming">0</strong><small>calendars</small></article><article><span>Shared By Me</span><strong id="ecOutgoing">0</strong><small>people</small></article></div>
<div class="ec-layout"><main class="ec-card"><div class="ec-filters"><label class="ec-search">⌕ <input id="ecSearch" type="search" placeholder="Search calendar…"></label><select id="ecTypeFilter"><option value="">All types</option>${TYPES.map(x=>`<option>${x}</option>`).join('')}</select><select id="ecStatusFilter"><option value="">All statuses</option>${STATUSES.map(x=>`<option>${x}</option>`).join('')}</select><button id="ecClear" type="button">Clear</button></div><div id="employeeCalendar" class="ec-calendar"></div><div id="ecFallback" class="ec-fallback" hidden>Calendar is loading…</div></main>
<aside class="ec-side"><section class="ec-card ec-side-card"><div class="ec-side-title"><strong>My Calendars</strong><small>Visibility</small></div><div id="ecCalendarList"></div></section><section class="ec-card ec-side-card"><div class="ec-side-title"><strong>Upcoming</strong><small>7 days</small></div><div id="ecUpcoming"></div></section></aside></div>
<div id="ecEventModal" class="ec-modal" hidden><div class="ec-dialog ec-dialog-lg" role="dialog" aria-modal="true"><div class="ec-modal-head"><div><div class="ec-eyebrow">Calendar Item</div><h2 id="ecEventTitleHead">New Calendar Item</h2></div><button class="ec-x" type="button" data-ec-close="ecEventModal">×</button></div><form id="ecEventForm"><input id="ecId" type="hidden"><div class="ec-grid">
<label class="ec-field ec-span"><span>Title *</span><input id="ecTitle" maxlength="250" required placeholder="e.g. Follow-up with client"></label><label class="ec-field"><span>Calendar</span><select id="ecOwner"></select></label><label class="ec-field"><span>Type</span><select id="ecType">${TYPES.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="ec-field"><span>Status</span><select id="ecStatus">${STATUSES.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="ec-field"><span>Show as</span><select id="ecShowAs"><option value="busy">Busy</option><option value="free">Free</option></select></label><label class="ec-field"><span>Starts *</span><input id="ecStart" type="datetime-local" required></label><label class="ec-field"><span>Ends</span><input id="ecEnd" type="datetime-local"></label><label class="ec-check"><input id="ecAllDay" type="checkbox"><span>All-day item</span></label><label class="ec-field"><span>Privacy</span><select id="ecPrivacy"><option value="shared">Visible to people I share with</option><option value="private">Private — only me</option></select></label><label class="ec-field"><span>Location</span><input id="ecLocation" placeholder="Office, client site…"></label><label class="ec-field"><span>Meeting link</span><input id="ecMeeting" type="url" placeholder="https://…"></label><label class="ec-field"><span>Related to</span><select id="ecRelatedType"><option value="">None</option><option value="companies">Company</option><option value="contacts">Contact</option><option value="leads">Lead</option><option value="deals">Deal</option></select></label><label class="ec-field"><span>Related record</span><select id="ecRelated" disabled><option value="">Select record</option></select></label><label class="ec-field ec-span"><span>Description / notes</span><textarea id="ecNotes" rows="4"></textarea></label></div>
<div class="ec-section"><strong>Reminders</strong><small>Choose up to 3 reminders for this item.</small></div><div class="ec-reminders"><label class="ec-field"><span>Reminder 1</span><select id="ecR1"></select></label><label class="ec-field"><span>Reminder 2</span><select id="ecR2"></select></label><label class="ec-field"><span>Reminder 3</span><select id="ecR3"></select></label></div><div class="ec-channels"><label class="ec-check"><input id="ecPwa" type="checkbox" checked><span>In-app + PWA</span></label><label class="ec-check"><input id="ecEmail" type="checkbox"><span>Email</span></label></div><div class="ec-modal-actions"><button class="btn danger" id="ecDelete" type="button" hidden>Delete</button><span></span><button class="btn" type="button" data-ec-close="ecEventModal">Cancel</button><button class="btn primary" id="ecSave" type="submit">Save Item</button></div></form></div></div>
<div id="ecShareModal" class="ec-modal" hidden><div class="ec-dialog" role="dialog" aria-modal="true"><div class="ec-modal-head"><div><div class="ec-eyebrow">Calendar Access</div><h2>Share My Calendar</h2><p>Grant access only to colleagues you choose.</p></div><button class="ec-x" type="button" data-ec-close="ecShareModal">×</button></div><div class="ec-share-create"><label class="ec-field"><span>Employee</span><select id="ecSharePerson"></select></label><label class="ec-field"><span>Access</span><select id="ecShareAccess"><option value="view">View only</option><option value="edit">Can edit</option></select></label><button class="btn primary" id="ecGrant" type="button">Grant Access</button></div><div class="ec-share-cols"><section><div class="ec-section"><strong>People with access</strong><small>You control these permissions.</small></div><div id="ecOutgoingShares"></div></section><section><div class="ec-section"><strong>Shared with me</strong><small>Calendars others gave you.</small></div><div id="ecIncomingShares"></div></section></div><div class="ec-modal-actions"><span></span><span></span><button class="btn" type="button" data-ec-close="ecShareModal">Close</button></div></div></div>
<div id="ecSettingsModal" class="ec-modal" hidden><div class="ec-dialog ec-dialog-sm" role="dialog" aria-modal="true"><div class="ec-modal-head"><div><div class="ec-eyebrow">Preferences</div><h2>Calendar Settings</h2><p>Working hours, timezone and daily agenda.</p></div><button class="ec-x" type="button" data-ec-close="ecSettingsModal">×</button></div><form id="ecSettingsForm"><div class="ec-grid"><label class="ec-field ec-span"><span>Timezone</span><select id="ecTimezone"></select></label><label class="ec-field"><span>Week starts on</span><select id="ecWeekStart"><option value="1">Monday</option><option value="0">Sunday</option><option value="6">Saturday</option></select></label><span></span><label class="ec-field"><span>Working day starts</span><input id="ecWorkStart" type="time"></label><label class="ec-field"><span>Working day ends</span><input id="ecWorkEnd" type="time"></label></div><div class="ec-section"><strong>Daily agenda</strong><small>Get “You have 3 calendar items today” in the morning.</small></div><div class="ec-settings-row"><label class="ec-check"><input id="ecAgenda" type="checkbox"><span>Enable</span></label><label class="ec-field"><span>Send at</span><input id="ecAgendaTime" type="time"></label><label class="ec-check"><input id="ecAgendaPwa" type="checkbox"><span>PWA</span></label><label class="ec-check"><input id="ecAgendaEmail" type="checkbox"><span>Email</span></label></div><div class="ec-section"><strong>Default reminders</strong><small>Automatically applied to new items.</small></div><div class="ec-reminders"><label class="ec-field"><span>Reminder 1</span><select id="ecDR1"></select></label><label class="ec-field"><span>Reminder 2</span><select id="ecDR2"></select></label><label class="ec-field"><span>Reminder 3</span><select id="ecDR3"></select></label></div><div class="ec-modal-actions"><span></span><span></span><button class="btn" type="button" data-ec-close="ecSettingsModal">Cancel</button><button class="btn primary" type="submit">Save Settings</button></div></form></div></div>`;
host.appendChild(v);return v}
function modal(id,on=true){const m=$(id);if(!m)return;m.hidden=!on;m.setAttribute('aria-hidden',on?'false':'true');document.body.classList.toggle('ec-modal-open',!!document.querySelector('.ec-modal:not([hidden])'))}
function show(updateHash=true){const t=ensureTab(),v=ensureView();if(!t||!v)return;document.body.classList.add('ic-employee-calendar-active');document.querySelectorAll('.view-tab.active,.view-tab[aria-selected="true"]').forEach(x=>{if(x!==t){x.classList.remove('active');x.setAttribute('aria-selected','false')}});t.classList.add('active');t.setAttribute('aria-selected','true');v.hidden=false;v.classList.add('active');t.closest('.view-menu-group')?.classList.add('is-expanded');t.closest('.view-menu-group')?.classList.remove('is-collapsed');if(updateHash&&!location.hash.startsWith('#employee-calendar'))history.pushState(null,'','#employee-calendar');global.InCheck360ModernTopbar?.refresh?.();ready().then(()=>setTimeout(()=>{S.cal?.render();S.cal?.updateSize();S.cal?.refetchEvents()},30)).catch(e=>toast(e.message,'error'))}
function hide(){document.body.classList.remove('ic-employee-calendar-active');$('employeeCalendarTab')?.classList.remove('active');$('employeeCalendarTab')?.setAttribute('aria-selected','false')}
async function currentUser(){S.db=db();const{data,error}=await S.db.auth.getUser();if(error)throw error;S.user=clean(data?.user?.id);if(!S.user)throw Error('Please sign in to use Calendar')}
async function loadPeople(){const{data,error}=await S.db.rpc('employee_calendar_list_people');if(error)throw error;S.people=data||[];S.peopleMap=new Map(S.people.map(x=>[String(x.id),x]));S.profile=S.peopleMap.get(S.user)||{id:S.user,display_name:'My Calendar'}}
async function loadSettings(){const r=await S.db.from('employee_calendar_settings').select('*').eq('user_id',S.user).maybeSingle();if(r.error)throw r.error;if(r.data){S.settings=r.data;return}const p={user_id:S.user,timezone:tz(),week_starts_on:1,working_day_start:'09:00',working_day_end:'18:00',daily_agenda_enabled:true,daily_agenda_time:'08:00',daily_agenda_pwa_enabled:true,daily_agenda_email_enabled:false,default_reminders:[1440,120,30]};const x=await S.db.from('employee_calendar_settings').insert(p).select('*').single();if(x.error)throw x.error;S.settings=x.data}
async function loadShares(){const{data,error}=await S.db.from('employee_calendar_shares').select('*').or(`owner_user_id.eq.${S.user},shared_with_user_id.eq.${S.user}`).order('created_at');if(error)throw error;S.shares=data||[];const allowed=[S.user,...incoming().map(x=>String(x.owner_user_id))];if(!S.owners.size)allowed.forEach(x=>S.owners.add(x));else{const set=new Set(allowed);[...S.owners].forEach(x=>{if(!set.has(x))S.owners.delete(x)});S.owners.add(S.user)}renderOwners();renderShares()}
function renderOwners(){const r=$('ecCalendarList');if(!r)return;const rows=[{id:S.user,name:personName(S.user),access:'owner'},...incoming().map(x=>({id:String(x.owner_user_id),name:personName(x.owner_user_id),access:x.access_level}))];r.innerHTML=rows.map(x=>`<label class="ec-owner"><input type="checkbox" data-owner="${esc(x.id)}" ${S.owners.has(x.id)?'checked':''}><span class="ec-avatar">${esc(initials(x.name))}</span><span><strong>${esc(x.name)}</strong><small>${x.access==='owner'?'My calendar':x.access==='edit'?'Shared · Can edit':'Shared · View only'}</small></span></label>`).join('');r.querySelectorAll('[data-owner]').forEach(i=>i.onchange=()=>{i.checked?S.owners.add(i.dataset.owner):S.owners.delete(i.dataset.owner);if(!S.owners.size){S.owners.add(S.user);r.querySelector(`[data-owner="${S.user}"]`).checked=true}S.cal?.refetchEvents();loadSummary().catch(()=>{})})}
function pass(row){if(!S.owners.has(String(row.owner_user_id)))return false;const q=clean($('ecSearch')?.value).toLowerCase(),ty=clean($('ecTypeFilter')?.value),st=clean($('ecStatusFilter')?.value);if(ty&&row.event_type!==ty)return false;if(st&&row.status!==st)return false;if(q&&!`${row.title||''} ${row.description||''} ${row.location||''} ${row.related_label||''} ${personName(row.owner_user_id)}`.toLowerCase().includes(q))return false;return true}
async function fetchEvents(info,ok,fail){try{const{data,error}=await S.db.from('employee_calendar_events').select('*').gte('start_at',info.start.toISOString()).lt('start_at',info.end.toISOString()).order('start_at').limit(2000);if(error)throw error;ok((data||[]).filter(pass).map(r=>({id:r.id,title:r.title,start:r.start_at,end:r.end_at||undefined,allDay:!!r.all_day,backgroundColor:COLORS[r.event_type]||'#475569',borderColor:COLORS[r.event_type]||'#475569',textColor:'#fff',editable:canEdit(r.owner_user_id),extendedProps:{row:r}})))}catch(e){fail?.(e);toast('Unable to load calendar items','error')}}
function initCal(){if(S.cal)return;if(!global.FullCalendar?.Calendar){$('ecFallback').hidden=false;setTimeout(initCal,300);return} $('ecFallback').hidden=true;S.cal=new global.FullCalendar.Calendar($('employeeCalendar'),{initialView:'dayGridMonth',headerToolbar:{left:'prev,next today',center:'title',right:'dayGridMonth,timeGridWeek,timeGridDay,listWeek'},buttonText:{today:'Today',month:'Month',week:'Week',day:'Day',list:'Agenda'},height:'auto',nowIndicator:true,navLinks:true,selectable:true,dayMaxEvents:4,firstDay:Number(S.settings?.week_starts_on??1),businessHours:{daysOfWeek:[1,2,3,4,5],startTime:String(S.settings?.working_day_start||'09:00').slice(0,5),endTime:String(S.settings?.working_day_end||'18:00').slice(0,5)},events:fetchEvents,dateClick:i=>{const a=new Date(`${i.dateStr}T09:00:00`);openEvent(null,{start:a,end:new Date(a.getTime()+3600000)})},select:i=>{openEvent(null,{start:i.start,end:i.end,allDay:i.allDay});S.cal.unselect()},eventClick:i=>openEvent(i.event.extendedProps.row),eventDrop:i=>moveEvent(i).catch(e=>{i.revert();toast(e.message,'error')}),eventResize:i=>moveEvent(i).catch(e=>{i.revert();toast(e.message,'error')})});S.cal.render()}
async function moveEvent(info){const r=info.event.extendedProps.row;if(!canEdit(r.owner_user_id))throw Error('You do not have edit access to this calendar');const x=await S.db.from('employee_calendar_events').update({start_at:info.event.start.toISOString(),end_at:info.event.end?.toISOString()||null,all_day:!!info.event.allDay,updated_by:S.user}).eq('id',r.id);if(x.error)throw x.error;await loadSummary()}
async function loadSummary(){const n=new Date(),a=new Date(n);a.setHours(0,0,0,0);const b=new Date(a);b.setDate(b.getDate()+8);const{data,error}=await S.db.from('employee_calendar_events').select('*').gte('start_at',a.toISOString()).lt('start_at',b.toISOString()).order('start_at').limit(500);if(error)throw error;S.summary=(data||[]).filter(x=>S.owners.has(String(x.owner_user_id))&&!['Cancelled','Completed'].includes(x.status));$('ecToday').textContent=S.summary.filter(x=>dayKey(x.start_at)===dayKey(n)).length;$('ecWeek').textContent=S.summary.length;$('ecIncoming').textContent=incoming().length;$('ecOutgoing').textContent=outgoing().length;renderUpcoming()}
function renderUpcoming(){const r=$('ecUpcoming');if(!r)return;const rows=S.summary.filter(x=>new Date(x.start_at)>=new Date()).slice(0,8);r.innerHTML=rows.length?rows.map(x=>`<button class="ec-upcoming" type="button" data-event="${esc(x.id)}"><i style="background:${COLORS[x.event_type]||'#475569'}"></i><span><strong>${esc(x.title)}</strong><small>${esc(fmt(x.start_at))}</small><em>${esc(personName(x.owner_user_id))}</em></span></button>`).join(''):'<div class="ec-empty"><strong>No upcoming items</strong><small>Your next 7 days are clear.</small></div>';r.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const x=S.summary.find(z=>String(z.id)===b.dataset.event);if(x)openEvent(x)})}
function editableCalendars(){return[{id:S.user,name:'My Calendar'},...incoming().filter(x=>x.access_level==='edit').map(x=>({id:String(x.owner_user_id),name:`${personName(x.owner_user_id)} · shared`}))]}
async function related(type,id=''){const s=$('ecRelated');if(!type){s.disabled=true;s.innerHTML='<option value="">Select record</option>';return}s.disabled=true;s.innerHTML='<option>Loading…</option>';try{const{data,error}=await S.db.from(type).select('*').limit(120);if(error)throw error;const label=x=>clean(x.company_name||x.legal_name||x.full_name||x.name||x.lead_name||x.deal_name||x.email||x.company_id||x.contact_id||x.lead_id||x.deal_id||x.id);s.innerHTML='<option value="">Select record</option>'+((data||[]).map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(id)?'selected':''}>${esc(label(x))}</option>`).join(''));s.disabled=false}catch(_){s.innerHTML='<option value="">No accessible records</option>'}}
async function openEvent(row=null,d={}){const f=$('ecEventForm');f.reset();$('ecId').value=row?.id||'';$('ecEventTitleHead').textContent=row?'Edit Calendar Item':'New Calendar Item';$('ecTitle').value=row?.title||'';$('ecOwner').innerHTML=editableCalendars().map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('ecOwner').value=row?.owner_user_id||S.user;$('ecOwner').disabled=!!row;$('ecType').value=row?.event_type||'Meeting';$('ecStatus').value=row?.status||'Planned';$('ecShowAs').value=row?.show_as||'busy';const st=row?.start_at?new Date(row.start_at):(d.start||new Date(Date.now()+3600000)),en=row?.end_at?new Date(row.end_at):(d.end||new Date(st.getTime()+3600000));$('ecStart').value=localInput(st);$('ecEnd').value=localInput(en);$('ecAllDay').checked=!!(row?.all_day??d.allDay);$('ecPrivacy').value=row?.privacy||'shared';$('ecLocation').value=row?.location||'';$('ecMeeting').value=row?.meeting_url||'';$('ecNotes').value=row?.description||'';$('ecRelatedType').value=row?.related_resource||'';await related($('ecRelatedType').value,row?.related_id||'');const rr=Array.isArray(row?.reminder_offsets)?row.reminder_offsets:(S.settings?.default_reminders||[1440,120,30]);['ecR1','ecR2','ecR3'].forEach((id,i)=>$(id).innerHTML=reminderHTML(rr[i]??-1));$('ecPwa').checked=row?row.reminder_pwa_enabled!==false:true;$('ecEmail').checked=!!row?.reminder_email_enabled;const edit=!row||canEdit(row.owner_user_id);f.querySelectorAll('input,select,textarea').forEach(x=>{if(x.id!=='ecId')x.disabled=!edit});if(row)$('ecOwner').disabled=true;if(row&&String(row.owner_user_id)!==S.user)$('ecPrivacy').disabled=true;$('ecSave').hidden=!edit;$('ecDelete').hidden=!row||!edit;modal('ecEventModal',true);setTimeout(()=>$('ecTitle')?.focus(),20)}
function offsets(prefix){return[1,2,3].map(i=>Number($(`${prefix}${i}`)?.value??-1)).filter((x,i,a)=>x>=0&&a.indexOf(x)===i).slice(0,3)}
async function saveEvent(e){e.preventDefault();const id=clean($('ecId').value),owner=clean($('ecOwner').value)||S.user,st=new Date($('ecStart').value),en=$('ecEnd').value?new Date($('ecEnd').value):null;if(isNaN(st))return toast('Start date and time is required','error');if(en&&en<st)return toast('End cannot be before start','error');const rs=$('ecRelated'),p={owner_user_id:owner,title:clean($('ecTitle').value),description:clean($('ecNotes').value)||null,event_type:$('ecType').value,status:$('ecStatus').value,start_at:st.toISOString(),end_at:en?.toISOString()||null,all_day:$('ecAllDay').checked,location:clean($('ecLocation').value)||null,meeting_url:clean($('ecMeeting').value)||null,related_resource:clean($('ecRelatedType').value)||null,related_id:clean(rs.value)||null,related_label:rs.value?clean(rs.selectedOptions[0]?.textContent):null,privacy:owner===S.user?$('ecPrivacy').value:'shared',show_as:$('ecShowAs').value,reminder_offsets:offsets('ecR'),reminder_pwa_enabled:$('ecPwa').checked,reminder_email_enabled:$('ecEmail').checked,updated_by:S.user};if(!p.title)return toast('Title is required','error');const x=id?await S.db.from('employee_calendar_events').update(p).eq('id',id):await S.db.from('employee_calendar_events').insert({...p,created_by:S.user});if(x.error)throw x.error;modal('ecEventModal',false);toast(id?'Calendar item updated':'Calendar item created');await refresh()}
async function delEvent(){const id=clean($('ecId').value);if(!id||!confirm('Delete this calendar item?'))return;const x=await S.db.from('employee_calendar_events').delete().eq('id',id);if(x.error)throw x.error;modal('ecEventModal',false);toast('Calendar item deleted');await refresh()}
function renderShares(){const a=$('ecSharePerson'),shared=new Set(outgoing().map(x=>String(x.shared_with_user_id))),available=S.people.filter(x=>String(x.id)!==S.user&&!shared.has(String(x.id)));if(a)a.innerHTML=available.length?'<option value="">Select employee</option>'+available.map(x=>`<option value="${esc(x.id)}">${esc(x.display_name)}${x.job_title?' · '+esc(x.job_title):''}</option>`).join(''):'<option value="">No additional employees</option>';const out=$('ecOutgoingShares');if(out){out.innerHTML=outgoing().length?outgoing().map(x=>{const p=S.peopleMap.get(String(x.shared_with_user_id))||{};return`<div class="ec-share-row"><span class="ec-avatar">${esc(initials(p.display_name||'Employee'))}</span><span><strong>${esc(p.display_name||p.email||'Employee')}</strong><small>${x.access_level==='edit'?'Can edit':'View only'}</small></span><select data-share="${esc(x.id)}"><option value="view" ${x.access_level==='view'?'selected':''}>View only</option><option value="edit" ${x.access_level==='edit'?'selected':''}>Can edit</option></select><button data-revoke="${esc(x.id)}" type="button">Revoke</button></div>`}).join(''):'<div class="ec-empty"><strong>Not shared yet</strong><small>Only you can see your calendar.</small></div>';out.querySelectorAll('[data-share]').forEach(s=>s.onchange=()=>shareAccess(s.dataset.share,s.value).catch(e=>toast(e.message,'error')));out.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>revoke(b.dataset.revoke).catch(e=>toast(e.message,'error')))}const inc=$('ecIncomingShares');if(inc)inc.innerHTML=incoming().length?incoming().map(x=>{const p=S.peopleMap.get(String(x.owner_user_id))||{};return`<div class="ec-share-row"><span class="ec-avatar">${esc(initials(p.display_name||'Employee'))}</span><span><strong>${esc(p.display_name||p.email||'Employee')}</strong><small>${x.access_level==='edit'?'Can edit':'View only'}</small></span><b>${x.access_level==='edit'?'Edit':'View'}</b></div>`}).join(''):'<div class="ec-empty"><strong>No shared calendars</strong><small>Calendars shared with you appear here.</small></div>'}
async function grant(){const who=clean($('ecSharePerson').value);if(!who)return toast('Select an employee','error');const{error}=await S.db.from('employee_calendar_shares').upsert({owner_user_id:S.user,shared_with_user_id:who,access_level:$('ecShareAccess').value,is_active:true},{onConflict:'owner_user_id,shared_with_user_id'});if(error)throw error;toast('Calendar access granted');await loadShares();await loadSummary()}
async function shareAccess(id,level){const{error}=await S.db.from('employee_calendar_shares').update({access_level:level,is_active:true}).eq('id',id);if(error)throw error;toast('Access updated');await loadShares()}
async function revoke(id){if(!confirm('Revoke this calendar access?'))return;const{error}=await S.db.from('employee_calendar_shares').delete().eq('id',id);if(error)throw error;toast('Access revoked');await loadShares();await loadSummary()}
function openShare(){renderShares();modal('ecShareModal',true)}
function zones(sel){return[...new Set([tz(),sel,'UTC','Asia/Beirut','Asia/Dubai','Asia/Riyadh','Europe/Amsterdam'].filter(Boolean))].map(x=>`<option value="${esc(x)}" ${x===sel?'selected':''}>${esc(x)}</option>`).join('')}
function openSettings(){const s=S.settings||{};$('ecTimezone').innerHTML=zones(s.timezone||tz());$('ecWeekStart').value=String(s.week_starts_on??1);$('ecWorkStart').value=String(s.working_day_start||'09:00').slice(0,5);$('ecWorkEnd').value=String(s.working_day_end||'18:00').slice(0,5);$('ecAgenda').checked=s.daily_agenda_enabled!==false;$('ecAgendaTime').value=String(s.daily_agenda_time||'08:00').slice(0,5);$('ecAgendaPwa').checked=s.daily_agenda_pwa_enabled!==false;$('ecAgendaEmail').checked=!!s.daily_agenda_email_enabled;const r=Array.isArray(s.default_reminders)?s.default_reminders:[1440,120,30];['ecDR1','ecDR2','ecDR3'].forEach((id,i)=>$(id).innerHTML=reminderHTML(r[i]??-1));modal('ecSettingsModal',true)}
async function saveSettings(e){e.preventDefault();const p={timezone:$('ecTimezone').value,week_starts_on:Number($('ecWeekStart').value),working_day_start:$('ecWorkStart').value||'09:00',working_day_end:$('ecWorkEnd').value||'18:00',daily_agenda_enabled:$('ecAgenda').checked,daily_agenda_time:$('ecAgendaTime').value||'08:00',daily_agenda_pwa_enabled:$('ecAgendaPwa').checked,daily_agenda_email_enabled:$('ecAgendaEmail').checked,default_reminders:offsets('ecDR')};const{data,error}=await S.db.from('employee_calendar_settings').update(p).eq('user_id',S.user).select('*').single();if(error)throw error;S.settings=data;if(S.cal){S.cal.setOption('firstDay',Number(p.week_starts_on));S.cal.setOption('businessHours',{daysOfWeek:[1,2,3,4,5],startTime:p.working_day_start,endTime:p.working_day_end})}modal('ecSettingsModal',false);toast('Calendar settings saved')}
async function refresh(){await loadShares();S.cal?.refetchEvents();await loadSummary()}
function bind(){if(S.bound)return;const t=ensureTab(),v=ensureView();if(!t||!v)return;S.bound=true;t.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();show()});document.addEventListener('click',e=>{const x=e.target?.closest?.('.view-tab');if(x&&x.id!=='employeeCalendarTab')hide()},true);global.addEventListener('hashchange',()=>location.hash.startsWith('#employee-calendar')?show(false):hide());$('ecNew').onclick=()=>openEvent();$('ecRefresh').onclick=()=>refresh().catch(e=>toast(e.message,'error'));$('ecShare').onclick=openShare;$('ecSettings').onclick=openSettings;$('ecEventForm').onsubmit=e=>saveEvent(e).catch(x=>toast(x.message,'error'));$('ecDelete').onclick=()=>delEvent().catch(e=>toast(e.message,'error'));$('ecGrant').onclick=()=>grant().catch(e=>toast(e.message,'error'));$('ecSettingsForm').onsubmit=e=>saveSettings(e).catch(x=>toast(x.message,'error'));$('ecRelatedType').onchange=e=>related(e.target.value);['ecSearch','ecTypeFilter','ecStatusFilter'].forEach(id=>$(id).addEventListener(id==='ecSearch'?'input':'change',()=>S.cal?.refetchEvents()));$('ecClear').onclick=()=>{$('ecSearch').value='';$('ecTypeFilter').value='';$('ecStatusFilter').value='';S.cal?.refetchEvents()};document.querySelectorAll('[data-ec-close]').forEach(b=>b.onclick=()=>modal(b.dataset.ecClose,false));document.querySelectorAll('.ec-modal').forEach(m=>m.addEventListener('mousedown',e=>{if(e.target===m)modal(m.id,false)}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.querySelector('.ec-modal:not([hidden])');if(m)modal(m.id,false)}})}
async function ready(){if(S.ready)return S.ready;S.ready=(async()=>{await currentUser();await Promise.all([loadPeople(),loadSettings()]);await loadShares();initCal();await loadSummary();return true})().catch(e=>{S.ready=null;throw e});return S.ready}
function install(){if(!document.body||document.body.classList.contains('auth-locked'))return false;if(!ensureTab()||!ensureView())return false;bind();if(location.hash.startsWith('#employee-calendar'))setTimeout(()=>show(false),20);return true}
function schedule(ms=60){clearTimeout(S.timer);S.timer=setTimeout(install,ms)}
function boot(){schedule(0);setTimeout(()=>schedule(0),300);setTimeout(()=>schedule(0),1000);if(global.MutationObserver){new MutationObserver(r=>{if(!document.body.classList.contains('auth-locked')&&r.some(x=>x.addedNodes?.length))schedule(120)}).observe(document.body,{childList:true,subtree:true});new MutationObserver(()=>document.body.classList.contains('auth-locked')?hide():schedule(0)).observe(document.body,{attributes:true,attributeFilter:['class']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
global.InCheck360EmployeeCalendar=Object.freeze({open:show,refresh,newItem:openEvent});
})(window);
