const ResellerUserAccess = (() => {
  const state = {
    mounted: false,
    bound: false,
    activeView: 'ruDashboard',
    crmTab: 'companies',
    modal: null,
    reseller: null,
    data: { companies: [], contacts: [], ownerships: [], leads: [], deals: [], activations: [], requests: [], renewals: [], settlements: [], payments: [] },
    admin: { resellers: [], users: [], links: [] }
  };

  const VIEWS = [
    ['ruDashboard','Dashboard','◫'],
    ['ruCrm','My CRM','◎'],
    ['ruMarket','Market Check','⌕'],
    ['ruActivations','Activations','✓'],
    ['ruRequests','Requests','✉'],
    ['ruRenewals','Renewals','↻'],
    ['ruSettlements','Settlements','$'],
    ['ruStatement','Statement of Account','≡']
  ];

  const $ = id => document.getElementById(id);
  const clean = v => String(v ?? '').trim();
  const norm = v => clean(v).toLowerCase().replace(/[\s-]+/g,'_');
  const esc = v => clean(v).replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
  const today = () => new Date().toISOString().slice(0,10);
  const addDays = (date,days) => { const d=new Date(`${date||today()}T00:00:00`); d.setDate(d.getDate()+Number(days||0)); return d.toISOString().slice(0,10); };
  const fmtDate = v => { if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d); };
  const fmtDateTime = v => { if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d); };
  const money = (v,c='USD') => { try{return new Intl.NumberFormat(undefined,{style:'currency',currency:clean(c)||'USD',maximumFractionDigits:2}).format(num(v));}catch{return `${clean(c)||'USD'} ${num(v).toFixed(2)}`;} };
  const getClient = () => { try{return window.SupabaseClient?.getClient?.()||null;}catch{return null;} };
  function identity(){ const s=window.Session||{}; const st=s.state||{}; let u={}; try{u=s.user?.()||{}}catch{} const p=st.profile||u.profile||{}; return {id:clean(st.user_id||st.id||u.user_id||u.id||p.id),role:norm(st.role_key||st.role||u.role_key||u.role||p.role_key||p.role),email:clean(st.email||u.email||p.email),name:clean(st.name||u.name||p.name||p.full_name)}; }
  const isAdmin = () => identity().role==='admin';
  const isReseller = () => identity().role==='reseller_user';
  const balance = s => Math.max(0,num(s.amount_due)-num(s.amount_paid));
  const companyName = id => state.data.companies.find(x=>x.id===id)?.company_name||'—';
  const contactName = id => { const c=state.data.contacts.find(x=>x.id===id); return c ? (c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email||c.contact_code) : '—'; };
  const labelStatus = s => clean(s).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
  const badge = s => `<span class="rm-badge ${esc(norm(s))}">${esc(labelStatus(s))}</span>`;
  const button = (label,action,kind='primary',extra='') => `<button type="button" class="btn ${esc(kind)}" data-ru-action="${esc(action)}" ${extra}>${esc(label)}</button>`;
  const empty = (cols,msg='No records yet.') => `<tr><td colspan="${cols}" class="rm-empty">${esc(msg)}</td></tr>`;
  const pageHeader = (title,desc,action='') => `<header class="rm-page-header"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="rm-actions">${action}</div></header>`;

  async function fetchRows(table,order='created_at',ascending=false){ const db=getClient(); if(!db)return[]; const {data,error}=await db.from(table).select('*').order(order,{ascending}).limit(5000); if(error)throw error; return data||[]; }

  async function loadOwn(){
    const db=getClient(); if(!db)return false;
    try{
      const {data:resellers,error:rErr}=await db.from('resellers').select('*').limit(2); if(rErr)throw rErr;
      state.reseller=(resellers||[])[0]||null;
      if(!state.reseller){ renderUnlinked(); return false; }
      const [companies,contacts,ownerships,leads,deals,activations,requests,renewals,settlements,payments]=await Promise.all([
        fetchRows('reseller_companies'),fetchRows('reseller_contacts'),fetchRows('reseller_ownerships'),fetchRows('reseller_leads'),fetchRows('reseller_deals'),
        fetchRows('reseller_activations'),fetchRows('reseller_requests'),fetchRows('reseller_renewals','renewal_date',true),fetchRows('reseller_settlements','due_date',true),fetchRows('reseller_payments','payment_date',true)
      ]);
      state.data={companies,contacts,ownerships,leads,deals,activations,requests,renewals,settlements,payments};
      return true;
    }catch(err){ console.error('[ResellerUserAccess] load failed',err); toast(err.message||'Unable to load reseller workspace.','error'); return false; }
  }

  function hideOtherSidebarGroups(){
    if(!isReseller())return;
    document.querySelectorAll('.grouped-view-tabs > .view-menu-group').forEach(g=>{
      if(g.id==='resellerUserWorkspaceGroup') g.style.removeProperty('display');
      else g.style.setProperty('display','none','important');
    });
    document.querySelectorAll('.grouped-view-tabs > .view-tab').forEach(t=>t.style.setProperty('display','none','important'));
  }

  function viewTemplate(key){
    if(key==='ruDashboard')return `<div class="rm-shell">${pageHeader('My Reseller Dashboard','Your private reseller workspace. Only data belonging to your reseller account is available here.',button('↻ Refresh','refresh','ghost'))}<section id="ruDashboardBody"></section></div>`;
    if(key==='ruCrm')return `<div class="rm-shell">${pageHeader('My CRM','Companies, contacts, leads and deals belonging only to your reseller account.')}<div class="rm-crm-tabs"><button class="rm-crm-tab active" data-ru-crm="companies">Companies</button><button class="rm-crm-tab" data-ru-crm="contacts">Contacts</button><button class="rm-crm-tab" data-ru-crm="leads">Leads</button><button class="rm-crm-tab" data-ru-crm="deals">Deals</button></div><section id="ruCrmBody"></section></div>`;
    if(key==='ruMarket')return `<div class="rm-shell">${pageHeader('Market Check','Check whether a company or contact is already being worked on. Only the status is returned.')}<section class="rm-card"><form id="ruMarketForm" class="rm-toolbar"><label><span>Company name</span><input id="ruMarketCompany" placeholder="Company name"></label><label><span>Website</span><input id="ruMarketWebsite" placeholder="example.com"></label><label><span>Email</span><input id="ruMarketEmail" type="email" placeholder="name@example.com"></label><label><span>Phone</span><input id="ruMarketPhone" placeholder="+961 …"></label><button type="submit" class="btn primary">Check Market</button></form></section><section id="ruMarketResult" class="rm-card"><div class="rm-empty">Enter at least one identifier and run Market Check.</div></section><section id="ruOwnershipBody"></section></div>`;
    if(key==='ruActivations')return `<div class="rm-shell">${pageHeader('Activations','Submit activation requests and follow their internal approval status.',button('+ New Activation','new-activation'))}<section id="ruActivationsBody"></section></div>`;
    if(key==='ruRequests')return `<div class="rm-shell">${pageHeader('Requests','Send and track reseller requests in one place.',button('+ New Request','new-request'))}<section id="ruRequestsBody"></section></div>`;
    if(key==='ruRenewals')return `<div class="rm-shell">${pageHeader('Renewals','Track upcoming renewals and send your renewal decision.')}<section id="ruRenewalsBody"></section></div>`;
    if(key==='ruSettlements')return `<div class="rm-shell">${pageHeader('Settlements','Read-only view of amounts due to InCheck 360 Holding and recorded payments.')}<section id="ruSettlementsBody"></section></div>`;
    return `<div class="rm-shell">${pageHeader('Statement of Account','Your reseller financial statement. Financial records are read-only.')}<section id="ruStatementBody"></section></div>`;
  }

  function mountWorkspace(){
    if(!isReseller())return false;
    if(state.mounted&&$('resellerUserWorkspaceGroup'))return true;
    const menu=document.querySelector('.grouped-view-tabs'); const panels=document.querySelector('.content-panels'); if(!menu||!panels)return false;
    const group=document.createElement('div'); group.id='resellerUserWorkspaceGroup'; group.className='view-menu-group is-expanded'; group.setAttribute('role','group'); group.setAttribute('aria-label','Reseller Workspace');
    group.innerHTML=`<button class="view-menu-group-title view-menu-group-toggle" type="button" aria-expanded="true"><span class="view-menu-group-label"><span class="view-menu-group-icon">🤝</span><span>Reseller Workspace</span></span><span class="view-menu-group-chevron">▾</span></button><div class="view-menu-group-body">${VIEWS.map(([k,l,i])=>`<button id="${k}Tab" class="view-tab" data-ru-view="${k}" role="tab" aria-selected="false"><span class="icon">${i}</span> ${esc(l)}</button>`).join('')}</div>`;
    menu.prepend(group);
    VIEWS.forEach(([k])=>{ const s=document.createElement('section'); s.id=`${k}View`; s.className='view rm-view'; s.setAttribute('role','tabpanel'); s.innerHTML=viewTemplate(k); panels.appendChild(s); });
    const modal=document.createElement('div'); modal.id='ruModalRoot'; modal.className='rm-hidden'; document.body.appendChild(modal);
    state.mounted=true; bind(); hideOtherSidebarGroups(); void loadOwn().then(()=>activate('ruDashboard'));
    return true;
  }

  function activate(key){ if(!isReseller()||!mountWorkspace())return; if(!VIEWS.some(v=>v[0]===key))key='ruDashboard'; document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); document.querySelectorAll('.view-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')}); $(`${key}View`)?.classList.add('active'); $(`${key}Tab`)?.classList.add('active'); $(`${key}Tab`)?.setAttribute('aria-selected','true'); state.activeView=key; renderActive(); hideOtherSidebarGroups(); }

  function renderUnlinked(){
    VIEWS.forEach(([k])=>{ const v=$(`${k}View`); if(v)v.innerHTML=`<div class="rm-shell">${pageHeader('Reseller Workspace','This user has the reseller_user role but is not linked to a reseller account.')}<section class="rm-card rm-empty">Ask an Administrator to open <strong>Reseller Management → Resellers</strong> and assign this user to a reseller.</section></div>`; });
  }

  function renderActive(){ if(!state.reseller)return renderUnlinked(); const k=state.activeView; if(k==='ruDashboard')renderDashboard(); else if(k==='ruCrm')renderCrm(); else if(k==='ruMarket')renderOwnerships(); else if(k==='ruActivations')renderActivations(); else if(k==='ruRequests')renderRequests(); else if(k==='ruRenewals')renderRenewals(); else if(k==='ruSettlements')renderSettlements(); else renderStatement(); }

  function renderDashboard(){ const el=$('ruDashboardBody'); if(!el)return; const pipeline=state.data.deals.filter(x=>!['won','lost'].includes(x.stage)).reduce((a,x)=>a+num(x.customer_sale_amount),0); const customers=state.data.companies.filter(x=>x.company_status==='customer').length; const locations=state.data.companies.filter(x=>x.company_status==='customer').reduce((a,x)=>a+num(x.estimated_locations),0); const outstanding=state.data.settlements.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+balance(x),0); const overdue=state.data.settlements.filter(x=>x.status!=='cancelled'&&x.due_date&&x.due_date<today()&&balance(x)>0).reduce((a,x)=>a+balance(x),0); const renewUntil=addDays(today(),60); const renewals=state.data.renewals.filter(x=>['upcoming','contacting_customer','confirmed'].includes(x.status)&&x.renewal_date<=renewUntil).length; const openRequests=state.data.requests.filter(x=>!['resolved','closed','rejected'].includes(x.status)).length;
    el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>${esc(state.reseller.company_name)}</strong><span>${esc(state.reseller.reseller_code)} · ${esc(state.reseller.territory||state.reseller.country||'')}</span></div>${badge(state.reseller.status)}</div></section><section class="rm-grid rm-summary-grid"><article class="rm-card rm-summary-card"><span>Open Pipeline</span><strong>${money(pipeline,state.reseller.currency)}</strong><small>Customer-facing deals</small></article><article class="rm-card rm-summary-card"><span>Active Customers</span><strong>${customers}</strong><small>${locations} estimated locations</small></article><article class="rm-card rm-summary-card"><span>Outstanding</span><strong>${money(outstanding,state.reseller.currency)}</strong><small>Due to InCheck</small></article><article class="rm-card rm-summary-card"><span>Overdue</span><strong class="${overdue?'rm-kpi-danger':''}">${money(overdue,state.reseller.currency)}</strong><small>Past-due balance</small></article><article class="rm-card rm-summary-card"><span>Renewals ≤60d</span><strong>${renewals}</strong><small>Upcoming renewals</small></article><article class="rm-card rm-summary-card"><span>Open Requests</span><strong>${openRequests}</strong><small>Not yet closed</small></article></section>`;
  }

  function renderCrm(){ const el=$('ruCrmBody'); if(!el)return; document.querySelectorAll('[data-ru-crm]').forEach(x=>x.classList.toggle('active',x.dataset.ruCrm===state.crmTab)); if(state.crmTab==='contacts')return renderContacts(el); if(state.crmTab==='leads')return renderLeads(el); if(state.crmTab==='deals')return renderDeals(el); renderCompanies(el); }
  function renderCompanies(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Companies</strong><span>Your reseller-owned prospects and customers</span></div>${button('+ Company','new-company','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Company</th><th>Ownership</th><th>Status</th><th>Locations</th><th>Contact</th><th>Action</th></tr></thead><tbody>${state.data.companies.length?state.data.companies.map(c=>`<tr><td><strong>${esc(c.company_name)}</strong><div class="rm-sub">${esc(c.company_code)} · ${esc(c.website||'')}</div></td><td>${badge(c.ownership_status)}${c.ownership_expires_at?`<div class="rm-sub">to ${fmtDate(c.ownership_expires_at)}</div>`:''}</td><td>${badge(c.company_status)}</td><td>${num(c.estimated_locations)}</td><td>${esc(c.main_email||c.main_phone||'—')}</td><td>${button('Edit','edit-company','ghost rm-btn-sm',`data-id="${esc(c.id)}"`)}</td></tr>`).join(''):empty(6,'No companies yet.')}</tbody></table></div></section>`; }
  function renderContacts(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Contacts</strong><span>Your private reseller contacts</span></div>${button('+ Contact','new-contact','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Contact</th><th>Company</th><th>Title</th><th>Email</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.data.contacts.length?state.data.contacts.map(c=>`<tr><td><strong>${esc(contactName(c.id))}</strong><div class="rm-sub">${esc(c.contact_code)}</div></td><td>${esc(companyName(c.company_id))}</td><td>${esc(c.job_title||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.mobile||c.phone||'—')}</td><td>${badge(c.contact_status)}</td><td>${button('Edit','edit-contact','ghost rm-btn-sm',`data-id="${esc(c.id)}"`)}</td></tr>`).join(''):empty(7,'No contacts yet.')}</tbody></table></div></section>`; }
  function renderLeads(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Leads</strong><span>Your reseller sales leads</span></div>${button('+ Lead','new-lead','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Lead</th><th>Company</th><th>Status</th><th>Priority</th><th>Estimated Value</th><th>Next Follow-up</th><th>Action</th></tr></thead><tbody>${state.data.leads.length?state.data.leads.map(l=>`<tr><td><strong>${esc(l.lead_name||l.lead_code)}</strong><div class="rm-sub">${esc(l.lead_code)}</div></td><td>${esc(companyName(l.company_id))}</td><td>${badge(l.status)}</td><td>${esc(labelStatus(l.priority))}</td><td class="rm-money">${money(l.estimated_value,l.currency)}</td><td>${fmtDateTime(l.next_follow_up_at)}</td><td>${button('Edit','edit-lead','ghost rm-btn-sm',`data-id="${esc(l.id)}"`)}</td></tr>`).join(''):empty(7,'No leads yet.')}</tbody></table></div></section>`; }
  function renderDeals(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Deals</strong><span>Won deals automatically create a draft activation. Amount due to InCheck is server-calculated.</span></div>${button('+ Deal','new-deal','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Deal</th><th>Company</th><th>Stage</th><th>Customer Value</th><th>Due to InCheck</th><th>Locations</th><th>Close</th><th>Action</th></tr></thead><tbody>${state.data.deals.length?state.data.deals.map(d=>`<tr><td><strong>${esc(d.deal_name)}</strong><div class="rm-sub">${esc(d.deal_code)}</div></td><td>${esc(companyName(d.company_id))}</td><td>${badge(d.stage)}</td><td class="rm-money">${money(d.customer_sale_amount,d.currency)}</td><td class="rm-money">${money(d.estimated_incheck_amount,d.currency)}</td><td>${num(d.location_count)}</td><td>${fmtDate(d.expected_close_date)}</td><td><div class="rm-actions">${!['won','lost'].includes(d.stage)?button('Mark Won','deal-won','ghost rm-btn-sm',`data-id="${esc(d.id)}"`):''}${button('Edit','edit-deal','ghost rm-btn-sm',`data-id="${esc(d.id)}"`)}</div></td></tr>`).join(''):empty(8,'No deals yet.')}</tbody></table></div></section>`; }

  function renderOwnerships(){ const el=$('ruOwnershipBody'); if(!el)return; const rows=state.data.ownerships.filter(x=>['pending','approved'].includes(x.status)); el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>My Prospect Registrations</strong><span>Ownership decisions are made internally by InCheck.</span></div></div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Registration</th><th>Company</th><th>Status</th><th>Submitted</th><th>Expires</th></tr></thead><tbody>${rows.length?rows.map(o=>`<tr><td>${esc(o.ownership_code)}</td><td><strong>${esc(companyName(o.company_id))}</strong></td><td>${badge(o.status)}</td><td>${fmtDateTime(o.submitted_at)}</td><td>${fmtDate(o.expires_at)}</td></tr>`).join(''):empty(5,'No pending or active registrations.')}</tbody></table></div></section>`; }
  function renderActivations(){ const el=$('ruActivationsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Activation</th><th>Customer</th><th>Status</th><th>Package</th><th>Locations</th><th>Due to InCheck</th><th>Service</th><th>Action</th></tr></thead><tbody>${state.data.activations.length?state.data.activations.map(a=>`<tr><td><strong>${esc(a.activation_code)}</strong></td><td>${esc(companyName(a.company_id))}</td><td>${badge(a.status)}</td><td>${esc(a.package_name||a.product_name||'—')}</td><td>${num(a.location_count)}</td><td class="rm-money">${money(a.amount_due_to_incheck,a.currency)}</td><td>${fmtDate(a.service_start_date)} → ${fmtDate(a.service_end_date)}</td><td><div class="rm-actions">${a.status==='draft'?button('Submit','activation-submit','ghost rm-btn-sm',`data-id="${esc(a.id)}"`):''}${['draft','submitted'].includes(a.status)?button('Edit','edit-activation','ghost rm-btn-sm',`data-id="${esc(a.id)}"`):''}</div></td></tr>`).join(''):empty(8,'No activations yet.')}</tbody></table></div></section>`; }
  function renderRequests(){ const el=$('ruRequestsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Request</th><th>Customer</th><th>Type</th><th>Priority</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>${state.data.requests.length?state.data.requests.map(r=>`<tr><td><strong>${esc(r.subject)}</strong><div class="rm-sub">${esc(r.request_code)}</div></td><td>${esc(companyName(r.company_id))}</td><td>${esc(labelStatus(r.request_type))}</td><td>${esc(labelStatus(r.priority))}</td><td>${badge(r.status)}</td><td>${fmtDateTime(r.due_at)}</td><td>${['draft','submitted','waiting_on_reseller'].includes(r.status)?button('Edit','edit-request','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):'—'}</td></tr>`).join(''):empty(7,'No requests yet.')}</tbody></table></div></section>`; }
  function renderRenewals(){ const el=$('ruRenewalsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Renewal</th><th>Customer</th><th>Status</th><th>Renewal Date</th><th>Response Due</th><th>Locations</th><th>Amount</th><th>Action</th></tr></thead><tbody>${state.data.renewals.length?state.data.renewals.map(r=>`<tr><td><strong>${esc(r.renewal_code)}</strong></td><td>${esc(companyName(r.company_id))}</td><td>${badge(r.status)}</td><td>${fmtDate(r.renewal_date)}</td><td>${fmtDate(r.response_due_date)}</td><td>${num(r.current_locations)}</td><td class="rm-money">${money(r.renewal_amount,r.currency)}</td><td><div class="rm-actions">${r.status==='upcoming'?button('Contacting','renewal-contacting','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${['upcoming','contacting_customer'].includes(r.status)?button('Confirm','renewal-confirm','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${!['renewed','not_renewing','expired'].includes(r.status)?button('No Renewal','renewal-no','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}</div></td></tr>`).join(''):empty(8,'No renewals yet.')}</tbody></table></div></section>`; }
  function renderSettlements(){ const el=$('ruSettlementsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Settlement</th><th>Customer</th><th>Source</th><th>Due</th><th>Paid</th><th>Balance</th><th>Due Date</th><th>Status</th><th>Invoice</th></tr></thead><tbody>${state.data.settlements.length?state.data.settlements.map(s=>`<tr><td><strong>${esc(s.settlement_code)}</strong><div class="rm-sub">${esc(s.description)}</div></td><td>${esc(companyName(s.company_id))}</td><td>${esc(labelStatus(s.source_type))}</td><td class="rm-money">${money(s.amount_due,s.currency)}</td><td class="rm-money">${money(s.amount_paid,s.currency)}</td><td class="rm-money">${money(balance(s),s.currency)}</td><td>${fmtDate(s.due_date)}</td><td>${badge(s.status)}</td><td>${esc(s.erp_invoice_number||'—')}</td></tr>`).join(''):empty(9,'No settlements yet.')}</tbody></table></div></section>`; }
  function renderStatement(){ const el=$('ruStatementBody'); if(!el||!state.reseller)return; const sets=state.data.settlements.filter(x=>x.status!=='cancelled'); const pays=state.data.payments; const due=sets.reduce((a,x)=>a+num(x.amount_due),0); const paid=pays.reduce((a,x)=>a+num(x.amount),0); const rows=[...sets.map(x=>({date:x.created_at,ref:x.erp_invoice_number||x.settlement_code,desc:x.description,debit:num(x.amount_due),credit:0})),...pays.map(x=>({date:x.payment_date||x.created_at,ref:x.erp_receipt_number||x.payment_code,desc:`Payment ${x.payment_method||''}`.trim(),debit:0,credit:num(x.amount)}))].sort((a,b)=>new Date(a.date)-new Date(b.date)); let running=0; rows.forEach(x=>{running+=x.debit-x.credit;x.balance=running;}); el.innerHTML=`<section class="rm-grid rm-three-col"><article class="rm-card rm-summary-card"><span>Total Debits</span><strong>${money(due,state.reseller.currency)}</strong><small>Obligations raised</small></article><article class="rm-card rm-summary-card"><span>Total Credits</span><strong>${money(paid,state.reseller.currency)}</strong><small>Payments recorded</small></article><article class="rm-card rm-summary-card"><span>Balance Due</span><strong>${money(Math.max(0,due-paid),state.reseller.currency)}</strong><small>${esc(state.reseller.company_name)}</small></article></section><section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${esc(x.ref)}</td><td>${esc(x.desc)}</td><td class="rm-money">${x.debit?money(x.debit,state.reseller.currency):'—'}</td><td class="rm-money">${x.credit?money(x.credit,state.reseller.currency):'—'}</td><td class="rm-money"><strong>${money(x.balance,state.reseller.currency)}</strong></td></tr>`).join(''):empty(6,'No statement activity yet.')}</tbody></table></div></section>`; }

  const CONFIG = {
    company:{title:'Company',fields:[['company_name','Company Name','text',true],['legal_name','Legal Name','text'],['website','Website','text'],['main_email','Main Email','email'],['main_phone','Main Phone','text'],['country','Country','text'],['city','City','text'],['estimated_locations','Estimated Locations','number'],['company_status','Status','select',true,['prospect','qualified','lost']],['notes','Notes','textarea']]},
    contact:{title:'Contact',fields:[['company_id','Company','company'],['first_name','First Name','text'],['last_name','Last Name','text'],['job_title','Job Title','text'],['department','Department','text'],['email','Email','email'],['phone','Phone','text'],['mobile','Mobile','text'],['contact_status','Status','select',true,['active','inactive','left_company']],['notes','Notes','textarea']]},
    lead:{title:'Lead',fields:[['company_id','Company','company'],['contact_id','Contact','contact'],['lead_name','Lead Name','text'],['status','Status','select',true,['new','contacted','qualified','nurturing','lost']],['priority','Priority','select',true,['low','medium','high','urgent']],['estimated_value','Estimated Value','number'],['currency','Currency','text'],['next_follow_up_at','Next Follow-up','datetime-local'],['notes','Notes','textarea']]},
    deal:{title:'Deal',fields:[['company_id','Company','company',true],['contact_id','Contact','contact'],['lead_id','Lead','lead'],['deal_name','Deal Name','text',true],['stage','Stage','select',true,['prospecting','qualified','proposal','negotiation','lost']],['currency','Currency','text'],['customer_sale_amount','Customer Sale Amount','number'],['location_count','Locations','number'],['probability_percent','Probability %','number'],['expected_close_date','Expected Close','date'],['reseller_customer_invoice_ref','Customer Invoice Ref','text'],['notes','Notes','textarea']]},
    activation:{title:'Activation',fields:[['company_id','Customer','company',true],['deal_id','Deal','deal'],['status','Status','select',true,['draft','submitted']],['package_name','Package','text'],['location_count','Locations','number'],['customer_sale_amount','Customer Sale Amount','number'],['currency','Currency','text'],['billing_frequency','Billing Frequency','select',true,['monthly','quarterly','semi_annual','annual']],['service_start_date','Service Start','date'],['service_end_date','Service End','date'],['reseller_customer_invoice_ref','Customer Invoice Ref','text'],['notes','Notes','textarea']]},
    request:{title:'Request',fields:[['company_id','Customer','company'],['activation_id','Activation','activation'],['request_type','Request Type','select',true,['new_activation','add_location','remove_location','pricing_exception','discount_approval','customer_ownership','ownership_extension','transfer_customer','hardware','support','billing','renewal_change','cancellation','general']],['subject','Subject','text',true],['description','Description','textarea'],['priority','Priority','select',true,['low','normal','high','urgent']],['status','Status','select',true,['draft','submitted','waiting_on_reseller']]]}
  };
  const TABLE={company:'reseller_companies',contact:'reseller_contacts',lead:'reseller_leads',deal:'reseller_deals',activation:'reseller_activations',request:'reseller_requests'};
  function options(type,selected){ let rows=[]; if(type==='company')rows=state.data.companies; if(type==='contact')rows=state.data.contacts; if(type==='lead')rows=state.data.leads; if(type==='deal')rows=state.data.deals; if(type==='activation')rows=state.data.activations; return `<option value="">Select…</option>`+rows.map(r=>{const label=type==='company'?`${r.company_code} · ${r.company_name}`:type==='contact'?`${r.contact_code} · ${contactName(r.id)}`:type==='lead'?`${r.lead_code} · ${r.lead_name||companyName(r.company_id)}`:type==='deal'?`${r.deal_code} · ${r.deal_name}`:`${r.activation_code} · ${companyName(r.company_id)}`;return `<option value="${esc(r.id)}" ${r.id===selected?'selected':''}>${esc(label)}</option>`;}).join(''); }
  function fieldHtml(f,record){ const [name,label,type,required,vals]=f; let value=record?.[name]??''; if(type==='datetime-local'&&value)value=new Date(value).toISOString().slice(0,16); const req=required?'required':''; if(type==='textarea')return `<label class="rm-field full"><span>${esc(label)}</span><textarea name="${esc(name)}" ${req}>${esc(value)}</textarea></label>`; if(type==='select')return `<label class="rm-field"><span>${esc(label)}</span><select name="${esc(name)}" ${req}>${vals.map(v=>`<option value="${esc(v)}" ${clean(value)===v?'selected':''}>${esc(labelStatus(v))}</option>`).join('')}</select></label>`; if(['company','contact','lead','deal','activation'].includes(type))return `<label class="rm-field"><span>${esc(label)}</span><select name="${esc(name)}" ${req}>${options(type,value)}</select></label>`; return `<label class="rm-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${type==='number'?'step="0.01"':''} ${req}></label>`; }
  function openModal(entity,record={}){ const cfg=CONFIG[entity]; if(!cfg||!state.reseller)return; state.modal={entity,id:record.id||''}; const root=$('ruModalRoot'); root.className='rm-modal-backdrop'; root.innerHTML=`<div class="rm-modal" role="dialog" aria-modal="true"><div class="rm-modal-head"><h2>${record.id?'Edit':'New'} ${esc(cfg.title)}</h2><button class="rm-modal-close" type="button" data-ru-action="close-modal">×</button></div><form id="ruEntityForm"><div class="rm-form-grid">${cfg.fields.map(f=>fieldHtml(f,record)).join('')}</div><div class="rm-modal-foot"><button type="button" class="btn ghost" data-ru-action="close-modal">Cancel</button><button type="submit" class="btn primary">Save</button></div></form></div>`; }
  function closeModal(){ const root=$('ruModalRoot'); if(root){root.className='rm-hidden';root.innerHTML='';} state.modal=null; }
  function modalPayload(){ const cfg=CONFIG[state.modal?.entity]; const form=$('ruEntityForm'); if(!cfg||!form||!state.reseller)return null; const fd=new FormData(form); const out={reseller_id:state.reseller.id}; cfg.fields.forEach(([name,,type])=>{let v=fd.get(name);if(type==='number')v=v===''?0:num(v);else if(v==='')v=null;out[name]=v;}); if(state.modal.entity==='contact')out.full_name=[out.first_name,out.last_name].filter(Boolean).join(' ')||null; if(state.modal.entity==='company'&&!out.source)out.source='manual'; return out; }
  async function saveModal(){ const m=state.modal; const payload=modalPayload(); const db=getClient(); if(!m||!payload||!db)return; try{payload.updated_by=identity().id; let res; if(m.id)res=await db.from(TABLE[m.entity]).update(payload).eq('id',m.id).select('*').single(); else {payload.created_by=identity().id;res=await db.from(TABLE[m.entity]).insert(payload).select('*').single();} if(res.error)throw res.error; closeModal(); await loadOwn(); renderActive(); toast('Saved successfully.');}catch(err){toast(err.message||'Unable to save.','error');} }
  async function updateStatus(table,id,status,extra={}){ const db=getClient(); if(!db)return; const {error}=await db.from(table).update({status,...extra,updated_by:identity().id}).eq('id',id); if(error)throw error; await loadOwn(); renderActive(); }
  async function runMarket(){ const db=getClient(); if(!db)return; const box=$('ruMarketResult'); if(box)box.innerHTML='<div class="rm-empty">Checking…</div>'; const q={p_company_name:$('ruMarketCompany')?.value||null,p_website:$('ruMarketWebsite')?.value||null,p_email:$('ruMarketEmail')?.value||null,p_phone:$('ruMarketPhone')?.value||null}; try{const {data,error}=await db.rpc('reseller_user_market_check',q);if(error)throw error;const r=Array.isArray(data)?data[0]:data;const status=r?.status||'available'; if(box)box.innerHTML=`<div class="rm-market-result"><div><h3>${badge(status)}</h3><p>${status==='available'?'No active ownership, customer or active sales engagement was found.':'Only availability status is exposed; owner and CRM details remain private.'}</p></div>${status==='available'?button('Register Prospect','register-prospect','primary'):''}</div>`; state.lastMarket={...q,status}; await loadOwn();renderOwnerships();}catch(err){if(box)box.innerHTML=`<div class="rm-empty">${esc(err.message||'Market Check failed.')}</div>`;} }
  async function registerProspect(){ if(!state.lastMarket||state.lastMarket.status!=='available'||!state.reseller)return; const db=getClient(); if(!db)return; const payload={reseller_id:state.reseller.id,company_name:state.lastMarket.p_company_name||state.lastMarket.p_website||state.lastMarket.p_email||'New Prospect',website:state.lastMarket.p_website||null,main_email:state.lastMarket.p_email||null,main_phone:state.lastMarket.p_phone||null,company_status:'prospect',source:'market_check',estimated_locations:1,created_by:identity().id}; const {data,error}=await db.from('reseller_companies').insert(payload).select('*').single(); if(error)throw error; const own=await db.from('reseller_ownerships').insert({reseller_id:state.reseller.id,company_id:data.id,status:'pending',created_by:identity().id}); if(own.error)throw own.error; await loadOwn(); renderActive(); toast('Prospect registered for ownership review.'); }

  function bind(){ if(state.bound)return; state.bound=true; document.addEventListener('click',e=>{ const tab=e.target?.closest?.('[data-ru-view]'); if(tab){e.preventDefault();activate(tab.dataset.ruView);return;} const crm=e.target?.closest?.('[data-ru-crm]'); if(crm){state.crmTab=crm.dataset.ruCrm;renderCrm();return;} const b=e.target?.closest?.('[data-ru-action]'); if(!b)return; void handleAction(b.dataset.ruAction,b); const unlink=e.target?.closest?.('[data-rua-unlink]'); if(unlink)void unlinkAdmin(unlink.dataset.ruaUnlink); }); document.addEventListener('submit',e=>{if(e.target?.id==='ruEntityForm'){e.preventDefault();void saveModal();} if(e.target?.id==='ruMarketForm'){e.preventDefault();void runMarket();} if(e.target?.id==='ruaAssignForm'){e.preventDefault();void assignAdmin();}}); }
  async function handleAction(action,b){ try{ if(action==='refresh'){await loadOwn();renderActive();return;} if(action==='close-modal')return closeModal(); if(action==='new-company')return openModal('company',{company_status:'prospect',estimated_locations:1}); if(action==='new-contact')return openModal('contact',{contact_status:'active'}); if(action==='new-lead')return openModal('lead',{status:'new',priority:'medium',currency:state.reseller?.currency||'USD'}); if(action==='new-deal')return openModal('deal',{stage:'prospecting',currency:state.reseller?.currency||'USD',location_count:1,probability_percent:10}); if(action==='new-activation')return openModal('activation',{status:'draft',currency:state.reseller?.currency||'USD',billing_frequency:'annual',location_count:1}); if(action==='new-request')return openModal('request',{status:'submitted',priority:'normal',request_type:'general'}); if(action.startsWith('edit-')){const entity=action.slice(5);const arr=state.data[entity==='company'?'companies':entity==='contact'?'contacts':entity==='lead'?'leads':entity==='deal'?'deals':entity==='activation'?'activations':'requests'];const rec=arr.find(x=>x.id===b.dataset.id);if(rec)return openModal(entity,rec);} if(action==='deal-won'){await updateStatus('reseller_deals',b.dataset.id,'won',{won_at:new Date().toISOString()});toast('Deal marked Won. Draft activation created.');return;} if(action==='activation-submit'){await updateStatus('reseller_activations',b.dataset.id,'submitted',{requested_at:new Date().toISOString()});toast('Activation submitted.');return;} if(action==='renewal-contacting'){await updateStatus('reseller_renewals',b.dataset.id,'contacting_customer');return;} if(action==='renewal-confirm'){await updateStatus('reseller_renewals',b.dataset.id,'confirmed',{decision_date:today()});return;} if(action==='renewal-no'){await updateStatus('reseller_renewals',b.dataset.id,'not_renewing',{decision_date:today()});return;} if(action==='register-prospect')return await registerProspect(); }catch(err){toast(err.message||'Action failed.','error');} }

  async function loadAdminAccess(){ if(!isAdmin())return; const db=getClient(); if(!db)return; try{const [r,u,l]=await Promise.all([db.from('resellers').select('id,reseller_code,company_name,status').order('company_name'),db.from('profiles').select('id,name,full_name,email,role_key,is_active').eq('role_key','reseller_user').eq('is_active',true).order('name'),db.from('reseller_user_links').select('*').order('created_at')]); if(r.error)throw r.error;if(u.error)throw u.error;if(l.error)throw l.error;state.admin={resellers:r.data||[],users:u.data||[],links:l.data||[]}; renderAdminPanel();}catch(err){console.warn('[ResellerUserAccess] admin assignment load skipped',err?.message||err);} }
  function renderAdminPanel(){ if(!isAdmin())return; const host=$('rmResellersBody'); if(!host)return; let panel=$('ruaAdminPanel'); if(panel)panel.remove(); panel=document.createElement('section'); panel.id='ruaAdminPanel'; panel.className='rm-card'; const userName=id=>{const u=state.admin.users.find(x=>x.id===id);return u?(u.name||u.full_name||u.email):id}; const resellerName=id=>state.admin.resellers.find(x=>x.id===id)?.company_name||id; panel.innerHTML=`<div class="rm-section-title"><div><strong>Reseller User Access</strong><span>Assign users with the reseller_user role to exactly one reseller. This link controls row-level access.</span></div></div><form id="ruaAssignForm" class="rm-toolbar"><label><span>Reseller User</span><select id="ruaUser"><option value="">Select…</option>${state.admin.users.map(u=>`<option value="${esc(u.id)}">${esc(u.name||u.full_name||u.email)} · ${esc(u.email||'')}</option>`).join('')}</select></label><label><span>Reseller</span><select id="ruaReseller"><option value="">Select…</option>${state.admin.resellers.map(r=>`<option value="${esc(r.id)}">${esc(r.reseller_code)} · ${esc(r.company_name)}</option>`).join('')}</select></label><button class="btn primary" type="submit">Assign Access</button></form><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>User</th><th>Reseller</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.admin.links.length?state.admin.links.map(l=>`<tr><td><strong>${esc(userName(l.user_id))}</strong></td><td>${esc(resellerName(l.reseller_id))}</td><td>${badge(l.is_active?'active':'inactive')}</td><td>${button('Remove','noop','ghost rm-btn-sm',`data-rua-unlink="${esc(l.id)}"`)}</td></tr>`).join(''):empty(4,state.admin.users.length?'No reseller users assigned yet.':'Create a user with role reseller_user in Users first.')}</tbody></table></div>`; host.appendChild(panel); }
  async function assignAdmin(){ if(!isAdmin())return; const uid=$('ruaUser')?.value; const rid=$('ruaReseller')?.value; if(!uid||!rid)return toast('Select both a reseller user and reseller.','error'); const db=getClient(); const who=identity().id; const {error}=await db.from('reseller_user_links').upsert({user_id:uid,reseller_id:rid,is_active:true,created_by:who,updated_by:who,updated_at:new Date().toISOString()},{onConflict:'user_id'}); if(error)return toast(error.message,'error'); await loadAdminAccess(); toast('Reseller access assigned.'); }
  async function unlinkAdmin(id){ if(!isAdmin()||!id)return; const db=getClient(); const {error}=await db.from('reseller_user_links').delete().eq('id',id); if(error)return toast(error.message,'error'); await loadAdminAccess(); toast('Reseller access removed.'); }

  function toast(message,type='success'){ try{if(window.UI?.toast)return window.UI.toast(message,type);if(window.showToast)return window.showToast(message,type);}catch{} console[type==='error'?'error':'log']('[ResellerUserAccess]',message); }
  function boot(){ const run=()=>{ if(document.body?.classList.contains('auth-locked'))return; bind(); if(isReseller()){mountWorkspace();hideOtherSidebarGroups();} if(isAdmin())void loadAdminAccess(); }; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run(); const obs=new MutationObserver(()=>{if(isReseller())hideOtherSidebarGroups();if(isAdmin()&&$('rmResellersBody')&&!$('ruaAdminPanel'))void loadAdminAccess();}); if(document.body)obs.observe(document.body,{attributes:true,childList:true,subtree:true}); window.setInterval(()=>{if(isReseller()){mountWorkspace();hideOtherSidebarGroups();}if(isAdmin()&&$('rmResellersBody')&&!$('ruaAdminPanel'))void loadAdminAccess();},2500); }
  return Object.freeze({boot,refresh:()=>isReseller()?loadOwn().then(renderActive):loadAdminAccess()});
})();

ResellerUserAccess.boot();
window.ResellerUserAccess=ResellerUserAccess;
