const ResellerManagement = (() => {
  const state = {
    mounted: false,
    bound: false,
    loading: false,
    activeView: 'resellerDashboard',
    crmTab: 'companies',
    modal: null,
    lastMarketQuery: null,
    lastMarketResult: null,
    data: { resellers: [], companies: [], contacts: [], ownerships: [], leads: [], deals: [], activations: [], requests: [], renewals: [], settlements: [], payments: [], profiles: [] }
  };
  const VIEWS = [
    ['resellerDashboard','Dashboard','◫'],['resellers','Resellers','🤝'],['resellerCrm','Reseller CRM','◎'],['resellerMarketCheck','Market Check','⌕'],
    ['resellerActivations','Activations','✓'],['resellerRequests','Requests','✉'],['resellerRenewals','Renewals','↻'],['resellerSettlements','Settlements','$'],
    ['resellerStatement','Statement of Account','≡'],['resellerReports','Reports','▥']
  ];
  const TABLE = { reseller:'resellers', company:'reseller_companies', contact:'reseller_contacts', lead:'reseller_leads', deal:'reseller_deals', activation:'reseller_activations', request:'reseller_requests', renewal:'reseller_renewals', settlement:'reseller_settlements', payment:'reseller_payments' };
  const $ = id => document.getElementById(id);
  const clean = v => String(v ?? '').trim();
  const norm = v => clean(v).toLowerCase().replace(/[\s-]+/g,'_');
  const esc = v => clean(v).replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
  const today = () => new Date().toISOString().slice(0,10);
  const addDays = (date, days) => { const d=new Date(`${date || today()}T00:00:00`); d.setDate(d.getDate()+Number(days||0)); return d.toISOString().slice(0,10); };
  const money = (v,c='USD') => { try { return new Intl.NumberFormat(undefined,{style:'currency',currency:clean(c)||'USD',maximumFractionDigits:2}).format(num(v)); } catch { return `${clean(c)||'USD'} ${num(v).toFixed(2)}`; } };
  const fmtDate = v => { if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d); };
  const fmtDateTime = v => { if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d); };
  const getClient = () => { try { return window.SupabaseClient?.getClient?.() || null; } catch { return null; } };
  function identity(){ const s=window.Session||{}; const st=s.state||{}; let u={}; try{u=s.user?.()||{}}catch{} const p=st.profile||u.profile||{}; return { id:clean(st.user_id||st.id||u.user_id||u.id||p.id), role:norm(st.role_key||st.role||u.role_key||u.role||p.role_key||p.role), email:clean(st.email||u.email||p.email) }; }
  const isAdmin = () => identity().role === 'admin';
  const badge = s => `<span class="rm-badge ${esc(norm(s))}">${esc(labelStatus(s))}</span>`;
  function labelStatus(s){ const m={onboarding:'Onboarding',active:'Active',suspended:'Suspended',inactive:'Inactive',expired:'Expired',unregistered:'Unregistered',pending:'Pending',approved:'Approved',rejected:'Rejected',released:'Released',available:'Available',pending_registration:'Pending Registration',already_engaged:'Already Engaged',existing_customer:'Existing Customer',prospect:'Prospect',qualified:'Qualified',customer:'Customer',lost:'Lost',new:'New',contacted:'Contacted',nurturing:'Nurturing',converted:'Converted',prospecting:'Prospecting',proposal:'Proposal',negotiation:'Negotiation',won:'Won',draft:'Draft',submitted:'Submitted',under_review:'Under Review',activated:'Activated',cancelled:'Cancelled',assigned:'Assigned',in_progress:'In Progress',waiting_on_reseller:'Waiting on Reseller',resolved:'Resolved',closed:'Closed',upcoming:'Upcoming',contacting_customer:'Contacting Customer',confirmed:'Confirmed',not_renewing:'Not Renewing',renewed:'Renewed',partially_paid:'Partially Paid',paid:'Paid',overdue:'Overdue'}; return m[norm(s)]||clean(s).replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
  const resellerName = id => state.data.resellers.find(x=>x.id===id)?.company_name || '—';
  const companyName = id => state.data.companies.find(x=>x.id===id)?.company_name || '—';
  const contactName = id => { const x=state.data.contacts.find(v=>v.id===id); return x ? (x.full_name || [x.first_name,x.last_name].filter(Boolean).join(' ') || x.email || x.contact_code) : '—'; };
  const dealName = id => state.data.deals.find(x=>x.id===id)?.deal_name || '—';
  const activationName = id => state.data.activations.find(x=>x.id===id)?.activation_code || '—';
  const settlementName = id => state.data.settlements.find(x=>x.id===id)?.settlement_code || '—';
  const balance = s => Math.max(0,num(s.amount_due)-num(s.amount_paid));
  function settlementStatus(s){ if(norm(s.status)==='cancelled')return 'cancelled'; if(balance(s)<=0 && num(s.amount_due)>0)return 'paid'; if(num(s.amount_paid)>0)return 'partially_paid'; if(s.due_date && s.due_date<today())return 'overdue'; return 'pending'; }
  function commercialLabel(r){ const model=norm(r?.commercial_model); if(model==='revenue_share')return `${num(r.revenue_share_percent)}% revenue share`; if(model==='fixed_wholesale')return `${money(r.wholesale_rate,r.currency)} fixed`; return `${money(r.wholesale_rate,r.currency)} / location`; }
  function calcAmount(resellerId, sale, locations){ const r=state.data.resellers.find(x=>x.id===resellerId); if(!r)return 0; if(r.commercial_model==='revenue_share')return Math.round(num(sale)*num(r.revenue_share_percent))/100; if(r.commercial_model==='fixed_wholesale')return num(r.wholesale_rate); return num(r.wholesale_rate)*num(locations); }
  function selectOptions(rows,valueKey,labelFn,selected){ return `<option value="">Select…</option>`+rows.map(r=>`<option value="${esc(r[valueKey])}" ${r[valueKey]===selected?'selected':''}>${esc(labelFn(r))}</option>`).join(''); }
  function pageHeader(title,desc,action=''){ return `<header class="rm-page-header"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="rm-actions">${action}</div></header>`; }
  function button(label,action,kind='primary',extra=''){ return `<button type="button" class="btn ${esc(kind)}" data-rm-action="${esc(action)}" ${extra}>${esc(label)}</button>`; }
  function empty(col,msg='No records yet.'){ return `<tr><td colspan="${col}" class="rm-empty">${esc(msg)}</td></tr>`; }

  function viewTemplate(key){
    if(key==='resellerDashboard') return `<div class="rm-shell">${pageHeader('Reseller Management','Central control of the reseller channel: CRM, ownership, activations, amounts due, renewals and requests.',button('↻ Refresh','refresh','ghost'))}<section id="rmDashboardBody"></section></div>`;
    if(key==='resellers') return `<div class="rm-shell">${pageHeader('Resellers','Master profiles, agreements, territory and the commercial terms that determine what each reseller owes.',button('+ New Reseller','new-reseller'))}<section id="rmResellersBody"></section></div>`;
    if(key==='resellerCrm') return `<div class="rm-shell">${pageHeader('Reseller CRM','A separate sub-CRM for reseller-owned companies, contacts, leads and deals.')}<div class="rm-crm-tabs"><button class="rm-crm-tab active" data-rm-crm="companies">Companies</button><button class="rm-crm-tab" data-rm-crm="contacts">Contacts</button><button class="rm-crm-tab" data-rm-crm="leads">Leads</button><button class="rm-crm-tab" data-rm-crm="deals">Deals</button></div><section id="rmCrmBody"></section></div>`;
    if(key==='resellerMarketCheck') return `<div class="rm-shell">${pageHeader('Market Check','Check whether a company or contact is available before anyone starts working it. Results expose status only.')}<section class="rm-card"><form id="rmMarketForm" class="rm-toolbar"><label><span>Reseller</span><select id="rmMarketReseller"></select></label><label><span>Company name</span><input id="rmMarketCompany" placeholder="Company name"></label><label><span>Website</span><input id="rmMarketWebsite" placeholder="example.com"></label><label><span>Email</span><input id="rmMarketEmail" type="email" placeholder="name@example.com"></label><label><span>Phone</span><input id="rmMarketPhone" placeholder="+961 …"></label><button type="submit" class="btn primary">Check Market</button></form></section><section id="rmMarketResult" class="rm-card"><div class="rm-empty">Enter at least one identifier and run Market Check.</div></section><section id="rmOwnershipBody"></section></div>`;
    if(key==='resellerActivations') return `<div class="rm-shell">${pageHeader('Activations','Deal-won handoff, internal approval and activation. Approval automatically creates the reseller financial obligation.',button('+ New Activation','new-activation'))}<section id="rmActivationsBody"></section></div>`;
    if(key==='resellerRequests') return `<div class="rm-shell">${pageHeader('Reseller Requests','One workflow for activation changes, ownership, pricing, hardware, billing, support, renewals and cancellations.',button('+ New Request','new-request'))}<section id="rmRequestsBody"></section></div>`;
    if(key==='resellerRenewals') return `<div class="rm-shell">${pageHeader('Reseller Renewals','Track upcoming customer renewals and the reseller response through renewal or non-renewal.',button('+ New Renewal','new-renewal'))}<section id="rmRenewalsBody"></section></div>`;
    if(key==='resellerSettlements') return `<div class="rm-shell">${pageHeader('Reseller Settlements','What each reseller owes InCheck 360 Holding. Customer invoicing remains the reseller’s responsibility.',button('+ Manual Settlement','new-settlement'))}<section id="rmSettlementsBody"></section></div>`;
    if(key==='resellerStatement') return `<div class="rm-shell">${pageHeader('Reseller Statement of Account','Debits from reseller obligations and credits from payments, with a running balance.')}<section class="rm-card"><div class="rm-toolbar"><label><span>Reseller</span><select id="rmStatementReseller"></select></label></div></section><section id="rmStatementBody"></section></div>`;
    return `<div class="rm-shell">${pageHeader('Reseller Reports','Commercial performance, pipeline, customers, locations, renewals and balances by reseller.',button('↻ Refresh','refresh','ghost'))}<section id="rmReportsBody"></section></div>`;
  }

  function mount(){
    if(!isAdmin()){ $('resellerManagementGroup')?.remove(); VIEWS.forEach(([k])=>$(`${k}View`)?.remove()); state.mounted=false; return false; }
    if(state.mounted && $('resellerManagementGroup')) return true;
    const menu=document.querySelector('.grouped-view-tabs'); const panels=document.querySelector('.content-panels'); if(!menu||!panels)return false;
    const group=document.createElement('div'); group.id='resellerManagementGroup'; group.className='view-menu-group'; group.dataset.menuGroup='reseller_management'; group.setAttribute('role','group'); group.setAttribute('aria-label','Reseller Management modules');
    group.innerHTML=`<button class="view-menu-group-title view-menu-group-toggle" type="button" aria-expanded="false" aria-controls="resellerManagementGroupBody"><span class="view-menu-group-label"><span class="view-menu-group-icon" aria-hidden="true">🤝</span><span>Reseller Management</span></span><span class="view-menu-group-chevron" aria-hidden="true">▾</span></button><div id="resellerManagementGroupBody" class="view-menu-group-body">${VIEWS.map(([k,l,i])=>`<button id="${k}Tab" class="view-tab" data-view="${k}" role="tab" aria-selected="false" aria-controls="${k}View"><span class="icon" aria-hidden="true">${i}</span> ${esc(l)}</button>`).join('')}</div>`;
    const admin=$('administrationUserActivityGroup'); if(admin?.parentElement===menu)menu.insertBefore(group,admin); else menu.appendChild(group);
    VIEWS.forEach(([k])=>{ const s=document.createElement('section'); s.id=`${k}View`; s.className='view rm-view'; s.setAttribute('role','tabpanel'); s.setAttribute('aria-labelledby',`${k}Tab`); s.innerHTML=viewTemplate(k); panels.appendChild(s); });
    const modal=document.createElement('div'); modal.id='rmModalRoot'; modal.className='rm-hidden'; document.body.appendChild(modal);
    state.mounted=true; bind(); fillStaticSelectors();
    const hash=location.hash.replace('#',''); const match=VIEWS.find(([k])=>hash===routeFor(k)); if(match)setTimeout(()=>activate(match[0]),0);
    return true;
  }
  function routeFor(k){ return ({resellerDashboard:'reseller-dashboard',resellers:'resellers',resellerCrm:'reseller-crm',resellerMarketCheck:'reseller-market-check',resellerActivations:'reseller-activations',resellerRequests:'reseller-requests',resellerRenewals:'reseller-renewals',resellerSettlements:'reseller-settlements',resellerStatement:'reseller-statement',resellerReports:'reseller-reports'})[k]||k; }
  function activate(key){ if(!isAdmin()||!mount())return; if(!VIEWS.some(v=>v[0]===key))key='resellerDashboard'; document.querySelectorAll('.view').forEach(x=>x.classList.remove('active')); document.querySelectorAll('.view-tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')}); $(`${key}View`)?.classList.add('active'); $(`${key}Tab`)?.classList.add('active'); $(`${key}Tab`)?.setAttribute('aria-selected','true'); const g=$('resellerManagementGroup'); g?.classList.add('is-expanded'); g?.querySelector('.view-menu-group-toggle')?.setAttribute('aria-expanded','true'); state.activeView=key; try{history.replaceState(null,'',`${location.pathname}${location.search}#${routeFor(key)}`)}catch{}; void refresh(true); }
  function bind(){ if(state.bound)return; state.bound=true;
    document.addEventListener('click',e=>{
      const tab=e.target?.closest?.('#resellerManagementGroup .view-tab'); if(tab){e.preventDefault();e.stopPropagation();activate(tab.dataset.view);return;}
      const crm=e.target?.closest?.('[data-rm-crm]'); if(crm){state.crmTab=crm.dataset.rmCrm; document.querySelectorAll('.rm-crm-tab').forEach(x=>x.classList.toggle('active',x.dataset.rmCrm===state.crmTab)); renderCrm();return;}
      const b=e.target?.closest?.('[data-rm-action]'); if(!b)return; const action=b.dataset.rmAction; if(!action)return; void handleAction(action,b);
    });
    document.addEventListener('submit',e=>{ if(e.target?.id==='rmMarketForm'){e.preventDefault();void runMarketCheck();} if(e.target?.id==='rmEntityForm'){e.preventDefault();void saveModal();} });
    document.addEventListener('change',e=>{ if(e.target?.id==='rmStatementReseller')renderStatement(); if(e.target?.name==='reseller_id' && state.modal) updateDependentModalOptions(); });
    $('resellerManagementGroup')?.querySelector('.view-menu-group-toggle')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const g=$('resellerManagementGroup');const ex=g.classList.toggle('is-expanded');e.currentTarget.setAttribute('aria-expanded',ex?'true':'false');});
  }

  async function fetchRows(table,order='created_at',ascending=false){ const db=getClient(); if(!db)return[]; let q=db.from(table).select('*').order(order,{ascending}).limit(5000); const {data,error}=await q; if(error)throw error; return data||[]; }
  async function loadAll(){ if(state.loading)return; state.loading=true; try{
    const [resellers,companies,contacts,ownerships,leads,deals,activations,requests,renewals,settlements,payments,profiles]=await Promise.all([
      fetchRows('resellers','company_name',true),fetchRows('reseller_companies'),fetchRows('reseller_contacts'),fetchRows('reseller_ownerships'),fetchRows('reseller_leads'),fetchRows('reseller_deals'),fetchRows('reseller_activations'),fetchRows('reseller_requests'),fetchRows('reseller_renewals','renewal_date',true),fetchRows('reseller_settlements','due_date',true),fetchRows('reseller_payments','payment_date',true),fetchRows('profiles','name',true)
    ]); state.data={resellers,companies,contacts,ownerships,leads,deals,activations,requests,renewals,settlements,payments,profiles}; fillStaticSelectors();
  }catch(err){console.error('[ResellerManagement] load failed',err); toast(err.message||'Unable to load reseller data','error');}finally{state.loading=false;} }
  async function refresh(force=false){ if(force||!state.data.resellers.length)await loadAll(); renderActive(); }
  function renderActive(){ const k=state.activeView; if(k==='resellerDashboard')renderDashboard(); else if(k==='resellers')renderResellers(); else if(k==='resellerCrm')renderCrm(); else if(k==='resellerMarketCheck')renderOwnerships(); else if(k==='resellerActivations')renderActivations(); else if(k==='resellerRequests')renderRequests(); else if(k==='resellerRenewals')renderRenewals(); else if(k==='resellerSettlements')renderSettlements(); else if(k==='resellerStatement')renderStatement(); else renderReports(); }
  function fillStaticSelectors(){ if($('rmMarketReseller'))$('rmMarketReseller').innerHTML=selectOptions(state.data.resellers,'id',r=>`${r.reseller_code} · ${r.company_name}`,''); if($('rmStatementReseller')){const current=$('rmStatementReseller').value;$('rmStatementReseller').innerHTML=selectOptions(state.data.resellers,'id',r=>`${r.reseller_code} · ${r.company_name}`,current||state.data.resellers[0]?.id); if(!current&&state.data.resellers[0])$('rmStatementReseller').value=state.data.resellers[0].id;} }

  function renderDashboard(){ const el=$('rmDashboardBody'); if(!el)return; const activeR=state.data.resellers.filter(x=>x.status==='active').length; const pipeline=state.data.deals.filter(x=>!['won','lost'].includes(x.stage)).reduce((a,x)=>a+num(x.customer_sale_amount),0); const customers=new Set(state.data.companies.filter(x=>x.company_status==='customer').map(x=>x.id)).size; const outstanding=state.data.settlements.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+balance(x),0); const overdue=state.data.settlements.filter(x=>settlementStatus(x)==='overdue').reduce((a,x)=>a+balance(x),0); const in60=addDays(today(),60); const renewals=state.data.renewals.filter(x=>['upcoming','contacting_customer','confirmed'].includes(x.status)&&x.renewal_date<=in60).length; const ownership=state.data.ownerships.filter(x=>x.status==='pending').slice(0,6); const acts=state.data.activations.filter(x=>['submitted','under_review','approved'].includes(x.status)).slice(0,6); const over=state.data.settlements.filter(x=>settlementStatus(x)==='overdue').slice(0,6);
    el.innerHTML=`<section class="rm-grid rm-summary-grid"><article class="rm-card rm-summary-card"><span>Active Resellers</span><strong>${activeR}</strong><small>${state.data.resellers.length} total</small></article><article class="rm-card rm-summary-card"><span>Pipeline</span><strong>${money(pipeline)}</strong><small>Open reseller deals</small></article><article class="rm-card rm-summary-card"><span>Active Customers</span><strong>${customers}</strong><small>Reseller customers</small></article><article class="rm-card rm-summary-card"><span>Outstanding</span><strong>${money(outstanding)}</strong><small>Due to InCheck</small></article><article class="rm-card rm-summary-card"><span>Overdue</span><strong class="${overdue?'rm-kpi-danger':''}">${money(overdue)}</strong><small>${renewals} renewals ≤60d</small></article></section><section class="rm-attention"><article class="rm-card"><div class="rm-section-title"><div><strong>Pending Ownership</strong><span>Prospects waiting for decision</span></div></div>${miniOwnership(ownership)}</article><article class="rm-card"><div class="rm-section-title"><div><strong>Activation Queue</strong><span>Submitted / review / approved</span></div></div>${miniActivations(acts)}</article><article class="rm-card"><div class="rm-section-title"><div><strong>Overdue Settlements</strong><span>Reseller amounts past due</span></div></div>${miniSettlements(over)}</article><article class="rm-card"><div class="rm-section-title"><div><strong>Upcoming Renewals</strong><span>Next 60 days</span></div></div>${miniRenewals(state.data.renewals.filter(x=>['upcoming','contacting_customer','confirmed'].includes(x.status)&&x.renewal_date<=in60).slice(0,6))}</article></section>`;
  }
  function miniOwnership(rows){return rows.length?`<div class="rm-table-wrap"><table class="rm-table"><tbody>${rows.map(o=>`<tr><td><strong>${esc(companyName(o.company_id))}</strong><div class="rm-sub">${esc(resellerName(o.reseller_id))}</div></td><td>${badge(o.status)}</td><td>${button('Review','goto-market','ghost','data-id="'+esc(o.id)+'"')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rm-empty">Nothing waiting.</div>';}
  function miniActivations(rows){return rows.length?`<div class="rm-table-wrap"><table class="rm-table"><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.activation_code)}</strong><div class="rm-sub">${esc(companyName(a.company_id))}</div></td><td>${badge(a.status)}</td><td class="rm-money">${money(a.amount_due_to_incheck,a.currency)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rm-empty">Activation queue is clear.</div>';}
  function miniSettlements(rows){return rows.length?`<div class="rm-table-wrap"><table class="rm-table"><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.settlement_code)}</strong><div class="rm-sub">${esc(resellerName(s.reseller_id))}</div></td><td>${fmtDate(s.due_date)}</td><td class="rm-money rm-kpi-danger">${money(balance(s),s.currency)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rm-empty">No overdue balances.</div>';}
  function miniRenewals(rows){return rows.length?`<div class="rm-table-wrap"><table class="rm-table"><tbody>${rows.map(r=>`<tr><td><strong>${esc(companyName(r.company_id))}</strong><div class="rm-sub">${esc(resellerName(r.reseller_id))}</div></td><td>${fmtDate(r.renewal_date)}</td><td>${badge(r.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="rm-empty">No renewals in the next 60 days.</div>';}

  function renderResellers(){ const el=$('rmResellersBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Reseller</th><th>Status</th><th>Territory</th><th>Commercial Model</th><th>Agreement</th><th>Customers</th><th>Outstanding</th><th>Action</th></tr></thead><tbody>${state.data.resellers.length?state.data.resellers.map(r=>{const cust=state.data.companies.filter(x=>x.reseller_id===r.id&&x.company_status==='customer').length;const out=state.data.settlements.filter(x=>x.reseller_id===r.id&&x.status!=='cancelled').reduce((a,x)=>a+balance(x),0);return `<tr><td><strong>${esc(r.company_name)}</strong><div class="rm-sub">${esc(r.reseller_code)} · ${esc(r.primary_contact_email||'')}</div></td><td>${badge(r.status)}</td><td>${esc(r.territory||r.country||'—')}</td><td>${esc(commercialLabel(r))}</td><td>${fmtDate(r.agreement_start_date)} → ${fmtDate(r.agreement_end_date)}</td><td>${cust}</td><td class="rm-money">${money(out,r.currency)}</td><td>${button('Edit','edit-reseller','ghost rm-btn-sm',`data-id="${esc(r.id)}"`)}</td></tr>`}).join(''):empty(8,'No resellers yet. Create the first reseller profile.')}</tbody></table></div></section>`; }

  function renderCrm(){ const el=$('rmCrmBody'); if(!el)return; document.querySelectorAll('.rm-crm-tab').forEach(x=>x.classList.toggle('active',x.dataset.rmCrm===state.crmTab)); if(state.crmTab==='contacts')return renderContacts(el); if(state.crmTab==='leads')return renderLeads(el); if(state.crmTab==='deals')return renderDeals(el); return renderCompanies(el); }
  function renderCompanies(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Companies</strong><span>Reseller-owned prospect and customer records</span></div>${button('+ Company','new-company','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Company</th><th>Reseller</th><th>Ownership</th><th>Status</th><th>Locations</th><th>Contact</th><th>Action</th></tr></thead><tbody>${state.data.companies.length?state.data.companies.map(c=>{const o=state.data.ownerships.find(x=>x.company_id===c.id&&['pending','approved'].includes(x.status));return `<tr><td><strong>${esc(c.company_name)}</strong><div class="rm-sub">${esc(c.company_code)} · ${esc(c.website||c.main_email||'')}</div></td><td>${esc(resellerName(c.reseller_id))}</td><td>${badge(c.ownership_status)}${c.ownership_expires_at?`<div class="rm-sub">to ${fmtDate(c.ownership_expires_at)}</div>`:''}</td><td>${badge(c.company_status)}</td><td>${num(c.estimated_locations)}</td><td>${esc(c.main_email||c.main_phone||'—')}</td><td><div class="rm-actions">${o?.status==='pending'?button('Approve','ownership-approve','ghost rm-btn-sm',`data-id="${esc(o.id)}"`):''}${o?.status==='approved'?button('Release','ownership-release','ghost rm-btn-sm',`data-id="${esc(o.id)}"`):''}${button('Edit','edit-company','ghost rm-btn-sm',`data-id="${esc(c.id)}"`)}</div></td></tr>`}).join(''):empty(7,'No reseller companies yet.')}</tbody></table></div></section>`; }
  function renderContacts(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Contacts</strong><span>Private contacts inside each reseller CRM</span></div>${button('+ Contact','new-contact','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Contact</th><th>Reseller</th><th>Company</th><th>Title</th><th>Email</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.data.contacts.length?state.data.contacts.map(c=>`<tr><td><strong>${esc(contactName(c.id))}</strong><div class="rm-sub">${esc(c.contact_code)}</div></td><td>${esc(resellerName(c.reseller_id))}</td><td>${esc(companyName(c.company_id))}</td><td>${esc(c.job_title||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.mobile||c.phone||'—')}</td><td>${badge(c.contact_status)}</td><td>${button('Edit','edit-contact','ghost rm-btn-sm',`data-id="${esc(c.id)}"`)}</td></tr>`).join(''):empty(8,'No reseller contacts yet.')}</tbody></table></div></section>`; }
  function renderLeads(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Leads</strong><span>Early reseller opportunities and follow-up</span></div>${button('+ Lead','new-lead','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Lead</th><th>Reseller</th><th>Company</th><th>Status</th><th>Priority</th><th>Estimated Value</th><th>Next Follow-up</th><th>Action</th></tr></thead><tbody>${state.data.leads.length?state.data.leads.map(l=>`<tr><td><strong>${esc(l.lead_name||l.lead_code)}</strong><div class="rm-sub">${esc(l.lead_code)}</div></td><td>${esc(resellerName(l.reseller_id))}</td><td>${esc(companyName(l.company_id))}</td><td>${badge(l.status)}</td><td>${esc(labelStatus(l.priority))}</td><td class="rm-money">${money(l.estimated_value,l.currency)}</td><td>${fmtDateTime(l.next_follow_up_at)}</td><td>${button('Edit','edit-lead','ghost rm-btn-sm',`data-id="${esc(l.id)}"`)}</td></tr>`).join(''):empty(8,'No reseller leads yet.')}</tbody></table></div></section>`; }
  function renderDeals(el){ el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Deals</strong><span>Commercial pipeline. Won deals automatically create a draft activation.</span></div>${button('+ Deal','new-deal','primary rm-btn-sm')}</div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Deal</th><th>Reseller</th><th>Company</th><th>Stage</th><th>Customer Value</th><th>InCheck Due</th><th>Locations</th><th>Expected Close</th><th>Action</th></tr></thead><tbody>${state.data.deals.length?state.data.deals.map(d=>`<tr><td><strong>${esc(d.deal_name)}</strong><div class="rm-sub">${esc(d.deal_code)}</div></td><td>${esc(resellerName(d.reseller_id))}</td><td>${esc(companyName(d.company_id))}</td><td>${badge(d.stage)}</td><td class="rm-money">${money(d.customer_sale_amount,d.currency)}</td><td class="rm-money">${money(d.estimated_incheck_amount||calcAmount(d.reseller_id,d.customer_sale_amount,d.location_count),d.currency)}</td><td>${num(d.location_count)}</td><td>${fmtDate(d.expected_close_date)}</td><td><div class="rm-actions">${!['won','lost'].includes(d.stage)?button('Mark Won','deal-won','ghost rm-btn-sm',`data-id="${esc(d.id)}"`):''}${button('Edit','edit-deal','ghost rm-btn-sm',`data-id="${esc(d.id)}"`)}</div></td></tr>`).join(''):empty(9,'No reseller deals yet.')}</tbody></table></div></section>`; }

  function renderOwnerships(){ const el=$('rmOwnershipBody'); if(!el)return; const rows=state.data.ownerships.filter(x=>['pending','approved'].includes(x.status)); el.innerHTML=`<section class="rm-card"><div class="rm-section-title"><div><strong>Prospect Ownership</strong><span>Approve, reject, extend or release registrations</span></div></div><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Registration</th><th>Company</th><th>Reseller</th><th>Status</th><th>Submitted</th><th>Expires</th><th>Action</th></tr></thead><tbody>${rows.length?rows.map(o=>`<tr><td>${esc(o.ownership_code)}</td><td><strong>${esc(companyName(o.company_id))}</strong></td><td>${esc(resellerName(o.reseller_id))}</td><td>${badge(o.status)}</td><td>${fmtDateTime(o.submitted_at)}</td><td>${fmtDate(o.expires_at)}</td><td><div class="rm-actions">${o.status==='pending'?`${button('Approve','ownership-approve','ghost rm-btn-sm',`data-id="${esc(o.id)}"`)}${button('Reject','ownership-reject','ghost rm-btn-sm',`data-id="${esc(o.id)}"`)}`:`${button('Extend','ownership-extend','ghost rm-btn-sm',`data-id="${esc(o.id)}"`)}${button('Release','ownership-release','ghost rm-btn-sm',`data-id="${esc(o.id)}"`)}`}</div></td></tr>`).join(''):empty(7,'No pending or active prospect registrations.')}</tbody></table></div></section>`; }

  function renderActivations(){ const el=$('rmActivationsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Activation</th><th>Reseller</th><th>Customer</th><th>Status</th><th>Package</th><th>Locations</th><th>Due to InCheck</th><th>Service</th><th>Action</th></tr></thead><tbody>${state.data.activations.length?state.data.activations.map(a=>`<tr><td><strong>${esc(a.activation_code)}</strong><div class="rm-sub">${esc(dealName(a.deal_id))}</div></td><td>${esc(resellerName(a.reseller_id))}</td><td>${esc(companyName(a.company_id))}</td><td>${badge(a.status)}</td><td>${esc(a.package_name||a.product_name||'—')}</td><td>${num(a.location_count)}</td><td class="rm-money">${money(a.amount_due_to_incheck,a.currency)}</td><td>${fmtDate(a.service_start_date)} → ${fmtDate(a.service_end_date)}</td><td><div class="rm-actions">${a.status==='draft'?button('Submit','activation-submit','ghost rm-btn-sm',`data-id="${esc(a.id)}"`):''}${a.status==='submitted'?button('Review','activation-review','ghost rm-btn-sm',`data-id="${esc(a.id)}"`):''}${['submitted','under_review'].includes(a.status)?`${button('Approve','activation-approve','ghost rm-btn-sm',`data-id="${esc(a.id)}"`)}${button('Reject','activation-reject','ghost rm-btn-sm',`data-id="${esc(a.id)}"`)}`:''}${a.status==='approved'?button('Activate','activation-activate','ghost rm-btn-sm',`data-id="${esc(a.id)}"`):''}${button('Edit','edit-activation','ghost rm-btn-sm',`data-id="${esc(a.id)}"`)}</div></td></tr>`).join(''):empty(9,'No activation requests yet.')}</tbody></table></div></section>`; }
  function renderRequests(){ const el=$('rmRequestsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Request</th><th>Reseller</th><th>Customer</th><th>Type</th><th>Priority</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>${state.data.requests.length?state.data.requests.map(r=>`<tr><td><strong>${esc(r.subject)}</strong><div class="rm-sub">${esc(r.request_code)}</div></td><td>${esc(resellerName(r.reseller_id))}</td><td>${esc(companyName(r.company_id))}</td><td>${esc(labelStatus(r.request_type))}</td><td>${esc(labelStatus(r.priority))}</td><td>${badge(r.status)}</td><td>${fmtDateTime(r.due_at)}</td><td><div class="rm-actions">${r.status==='submitted'?button('Start','request-start','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${['submitted','assigned','in_progress'].includes(r.status)?button('Wait','request-wait','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${!['resolved','closed','rejected'].includes(r.status)?button('Resolve','request-resolve','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${r.status==='resolved'?button('Close','request-close','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${button('Edit','edit-request','ghost rm-btn-sm',`data-id="${esc(r.id)}"`)}</div></td></tr>`).join(''):empty(8,'No reseller requests yet.')}</tbody></table></div></section>`; }
  function renderRenewals(){ const el=$('rmRenewalsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Renewal</th><th>Reseller</th><th>Customer</th><th>Status</th><th>Renewal Date</th><th>Response Due</th><th>Locations</th><th>Amount</th><th>Action</th></tr></thead><tbody>${state.data.renewals.length?state.data.renewals.map(r=>`<tr><td><strong>${esc(r.renewal_code)}</strong><div class="rm-sub">${esc(activationName(r.activation_id))}</div></td><td>${esc(resellerName(r.reseller_id))}</td><td>${esc(companyName(r.company_id))}</td><td>${badge(r.status)}</td><td>${fmtDate(r.renewal_date)}</td><td>${fmtDate(r.response_due_date)}</td><td>${num(r.current_locations)}</td><td class="rm-money">${money(r.renewal_amount,r.currency)}</td><td><div class="rm-actions">${r.status==='upcoming'?button('Contacting','renewal-contacting','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${['upcoming','contacting_customer'].includes(r.status)?button('Confirm','renewal-confirm','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${['confirmed','contacting_customer'].includes(r.status)?button('Renew','renewal-renew','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${!['renewed','not_renewing','expired'].includes(r.status)?button('No Renewal','renewal-no','ghost rm-btn-sm',`data-id="${esc(r.id)}"`):''}${button('Edit','edit-renewal','ghost rm-btn-sm',`data-id="${esc(r.id)}"`)}</div></td></tr>`).join(''):empty(9,'No reseller renewals yet.')}</tbody></table></div></section>`; }
  function renderSettlements(){ const el=$('rmSettlementsBody'); if(!el)return; el.innerHTML=`<section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Settlement</th><th>Reseller</th><th>Customer</th><th>Source</th><th>Due</th><th>Paid</th><th>Balance</th><th>Due Date</th><th>Status</th><th>Invoice</th><th>Action</th></tr></thead><tbody>${state.data.settlements.length?state.data.settlements.map(s=>`<tr><td><strong>${esc(s.settlement_code)}</strong><div class="rm-sub">${esc(s.description)}</div></td><td>${esc(resellerName(s.reseller_id))}</td><td>${esc(companyName(s.company_id))}</td><td>${esc(labelStatus(s.source_type))}</td><td class="rm-money">${money(s.amount_due,s.currency)}</td><td class="rm-money">${money(s.amount_paid,s.currency)}</td><td class="rm-money ${settlementStatus(s)==='overdue'?'rm-kpi-danger':''}">${money(balance(s),s.currency)}</td><td>${fmtDate(s.due_date)}</td><td>${badge(settlementStatus(s))}</td><td>${esc(s.erp_invoice_number||'—')}</td><td><div class="rm-actions">${balance(s)>0&&s.status!=='cancelled'?button('Payment','record-payment','ghost rm-btn-sm',`data-id="${esc(s.id)}"`):''}${button('Edit','edit-settlement','ghost rm-btn-sm',`data-id="${esc(s.id)}"`)}</div></td></tr>`).join(''):empty(11,'No reseller settlements yet.')}</tbody></table></div></section>`; }

  function renderStatement(){ const el=$('rmStatementBody'); if(!el)return; fillStaticSelectors(); const rid=$('rmStatementReseller')?.value||state.data.resellers[0]?.id; if(!rid){el.innerHTML='<div class="rm-card rm-empty">Create a reseller first.</div>';return;} const r=state.data.resellers.find(x=>x.id===rid); const sets=state.data.settlements.filter(x=>x.reseller_id===rid&&x.status!=='cancelled'); const pays=state.data.payments.filter(x=>x.reseller_id===rid); const due=sets.reduce((a,x)=>a+num(x.amount_due),0); const paid=pays.reduce((a,x)=>a+num(x.amount),0); const rows=[...sets.map(x=>({date:x.created_at,type:'Debit',ref:x.erp_invoice_number||x.settlement_code,desc:x.description,debit:num(x.amount_due),credit:0})),...pays.map(x=>({date:x.payment_date||x.created_at,type:'Credit',ref:x.erp_receipt_number||x.payment_code,desc:`Payment ${x.payment_method||''}`.trim(),debit:0,credit:num(x.amount)}))].sort((a,b)=>new Date(a.date)-new Date(b.date)); let running=0; rows.forEach(x=>{running+=x.debit-x.credit;x.balance=running;}); el.innerHTML=`<section class="rm-grid rm-three-col"><article class="rm-card rm-summary-card"><span>Total Debits</span><strong>${money(due,r?.currency)}</strong><small>Obligations raised</small></article><article class="rm-card rm-summary-card"><span>Total Credits</span><strong>${money(paid,r?.currency)}</strong><small>Payments recorded</small></article><article class="rm-card rm-summary-card"><span>Balance Due</span><strong class="rm-statement-balance">${money(Math.max(0,due-paid),r?.currency)}</strong><small>${esc(r?.company_name||'')}</small></article></section><section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${esc(x.ref)}</td><td>${esc(x.desc)}</td><td class="rm-money">${x.debit?money(x.debit,r?.currency):'—'}</td><td class="rm-money">${x.credit?money(x.credit,r?.currency):'—'}</td><td class="rm-money"><strong>${money(x.balance,r?.currency)}</strong></td></tr>`).join(''):empty(6,'No statement activity for this reseller.')}</tbody></table></div></section>`; }

  function renderReports(){ const el=$('rmReportsBody'); if(!el)return; const rows=state.data.resellers.map(r=>{const deals=state.data.deals.filter(x=>x.reseller_id===r.id);const pipeline=deals.filter(x=>!['won','lost'].includes(x.stage)).reduce((a,x)=>a+num(x.customer_sale_amount),0);const won=deals.filter(x=>x.stage==='won').length;const comps=state.data.companies.filter(x=>x.reseller_id===r.id&&x.company_status==='customer');const loc=comps.reduce((a,x)=>a+num(x.estimated_locations),0);const sets=state.data.settlements.filter(x=>x.reseller_id===r.id&&x.status!=='cancelled');const due=sets.reduce((a,x)=>a+num(x.amount_due),0);const paid=state.data.payments.filter(x=>x.reseller_id===r.id).reduce((a,x)=>a+num(x.amount),0);const renew=state.data.renewals.filter(x=>x.reseller_id===r.id&&['upcoming','contacting_customer','confirmed'].includes(x.status)).length;return {r,pipeline,won,customers:comps.length,loc,due,paid,out:Math.max(0,due-paid),renew};}); const totalOut=rows.reduce((a,x)=>a+x.out,0); const totalPipe=rows.reduce((a,x)=>a+x.pipeline,0); el.innerHTML=`<section class="rm-grid rm-summary-grid"><article class="rm-card rm-summary-card"><span>Resellers</span><strong>${rows.length}</strong><small>${rows.filter(x=>x.r.status==='active').length} active</small></article><article class="rm-card rm-summary-card"><span>Open Pipeline</span><strong>${money(totalPipe)}</strong><small>Customer-facing value</small></article><article class="rm-card rm-summary-card"><span>Customers</span><strong>${rows.reduce((a,x)=>a+x.customers,0)}</strong><small>Across reseller channel</small></article><article class="rm-card rm-summary-card"><span>Locations</span><strong>${rows.reduce((a,x)=>a+x.loc,0)}</strong><small>Estimated active</small></article><article class="rm-card rm-summary-card"><span>Outstanding</span><strong>${money(totalOut)}</strong><small>Due to InCheck</small></article></section><section class="rm-card"><div class="rm-table-wrap"><table class="rm-table"><thead><tr><th>Reseller</th><th>Status</th><th>Pipeline</th><th>Won Deals</th><th>Customers</th><th>Locations</th><th>Obligations</th><th>Paid</th><th>Outstanding</th><th>Open Renewals</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td><strong>${esc(x.r.company_name)}</strong><div class="rm-sub">${esc(x.r.reseller_code)}</div></td><td>${badge(x.r.status)}</td><td class="rm-money">${money(x.pipeline,x.r.currency)}</td><td>${x.won}</td><td>${x.customers}</td><td>${x.loc}</td><td class="rm-money">${money(x.due,x.r.currency)}</td><td class="rm-money">${money(x.paid,x.r.currency)}</td><td class="rm-money">${money(x.out,x.r.currency)}</td><td>${x.renew}</td></tr>`).join(''):empty(10,'No reseller data to report yet.')}</tbody></table></div></section>`; }

  const configs = {
    reseller:{title:'Reseller',fields:[['company_name','Company Name','text',true],['legal_name','Legal Name','text'],['status','Status','select',true,['onboarding','active','suspended','inactive','expired']],['country','Country','text'],['territory','Territory','text'],['primary_contact_name','Primary Contact','text'],['primary_contact_email','Primary Email','email'],['primary_contact_phone','Primary Phone','text'],['agreement_start_date','Agreement Start','date'],['agreement_end_date','Agreement End','date'],['currency','Currency','text',true],['payment_term_days','Payment Terms (days)','number',true],['commercial_model','Commercial Model','select',true,['per_location','fixed_wholesale','revenue_share']],['wholesale_rate','Wholesale Rate','number'],['revenue_share_percent','Revenue Share %','number'],['ownership_days','Ownership Period (days)','number'],['renewal_responsibility','Renewal Responsibility','select',true,['reseller','incheck','shared']],['hardware_model','Hardware Responsibility','select',true,['reseller','incheck','shared','not_applicable']],['notes','Notes','textarea']]},
    company:{title:'Reseller Company',fields:[['reseller_id','Reseller','reseller',true],['company_name','Company Name','text',true],['legal_name','Legal Name','text'],['website','Website','text'],['main_email','Main Email','email'],['main_phone','Main Phone','text'],['country','Country','text'],['city','City','text'],['address','Address','text'],['company_status','Company Status','select',true,['prospect','qualified','customer','inactive','released','lost']],['estimated_locations','Estimated Locations','number'],['source','Source','select',true,['manual','market_check','import','transfer']],['notes','Notes','textarea']]},
    contact:{title:'Reseller Contact',fields:[['reseller_id','Reseller','reseller',true],['company_id','Company','company'],['first_name','First Name','text'],['last_name','Last Name','text'],['full_name','Full Name','text'],['job_title','Job Title','text'],['department','Department','text'],['email','Email','email'],['phone','Phone','text'],['mobile','Mobile','text'],['is_primary','Primary Contact','checkbox'],['contact_status','Status','select',true,['active','inactive','left_company']],['notes','Notes','textarea']]},
    lead:{title:'Reseller Lead',fields:[['reseller_id','Reseller','reseller',true],['company_id','Company','company'],['contact_id','Contact','contact'],['lead_name','Lead Name','text'],['status','Status','select',true,['new','contacted','qualified','nurturing','converted','lost']],['source','Source','text'],['priority','Priority','select',true,['low','medium','high','urgent']],['estimated_value','Estimated Value','number'],['currency','Currency','text'],['next_follow_up_at','Next Follow-up','datetime-local'],['notes','Notes','textarea']]},
    deal:{title:'Reseller Deal',fields:[['reseller_id','Reseller','reseller',true],['company_id','Company','company',true],['contact_id','Contact','contact'],['lead_id','Lead','lead'],['deal_name','Deal Name','text',true],['stage','Stage','select',true,['prospecting','qualified','proposal','negotiation','won','lost']],['currency','Currency','text'],['customer_sale_amount','Customer Sale Amount','number'],['estimated_incheck_amount','Estimated Amount Due to InCheck','number'],['location_count','Locations','number'],['probability_percent','Probability %','number'],['expected_close_date','Expected Close','date'],['reseller_customer_invoice_ref','Reseller Customer Invoice Ref','text'],['notes','Notes','textarea']]},
    activation:{title:'Reseller Activation',fields:[['reseller_id','Reseller','reseller',true],['company_id','Customer','company',true],['deal_id','Deal','deal'],['status','Status','select',true,['draft','submitted','under_review','approved','rejected','activated','cancelled']],['product_name','Product','text'],['package_name','Package','text'],['location_count','Locations','number'],['customer_sale_amount','Customer Sale Amount','number'],['amount_due_to_incheck','Amount Due to InCheck','number'],['currency','Currency','text'],['billing_frequency','Billing Frequency','select',true,['monthly','quarterly','semi_annual','annual']],['service_start_date','Service Start','date'],['service_end_date','Service End','date'],['reseller_customer_invoice_ref','Reseller Customer Invoice Ref','text'],['notes','Notes','textarea']]},
    request:{title:'Reseller Request',fields:[['reseller_id','Reseller','reseller',true],['company_id','Customer','company'],['activation_id','Activation','activation'],['request_type','Request Type','select',true,['new_activation','add_location','remove_location','pricing_exception','discount_approval','customer_ownership','ownership_extension','transfer_customer','hardware','support','billing','renewal_change','cancellation','general']],['subject','Subject','text',true],['description','Description','textarea'],['priority','Priority','select',true,['low','normal','high','urgent']],['status','Status','select',true,['draft','submitted','assigned','in_progress','waiting_on_reseller','resolved','closed','rejected']],['assigned_to','Assigned To','profile'],['due_at','Due At','datetime-local'],['resolution','Resolution','textarea']]},
    renewal:{title:'Reseller Renewal',fields:[['reseller_id','Reseller','reseller',true],['company_id','Customer','company',true],['activation_id','Activation','activation'],['status','Status','select',true,['upcoming','contacting_customer','confirmed','not_renewing','renewed','expired']],['currency','Currency','text'],['renewal_amount','Renewal Amount','number'],['current_locations','Current Locations','number'],['renewal_date','Renewal Date','date',true],['response_due_date','Response Due','date'],['new_start_date','New Start','date'],['new_end_date','New End','date'],['notes','Notes','textarea']]},
    settlement:{title:'Reseller Settlement',fields:[['reseller_id','Reseller','reseller',true],['company_id','Customer','company'],['source_type','Source','select',true,['manual','adjustment']],['description','Description','text',true],['currency','Currency','text'],['amount_due','Amount Due','number',true],['due_date','Due Date','date'],['status','Status','select',true,['pending','partially_paid','paid','overdue','cancelled']],['erp_invoice_number','ERP Invoice Number','text'],['notes','Notes','textarea']]},
    payment:{title:'Record Reseller Payment',fields:[['reseller_id','Reseller','reseller',true],['settlement_id','Settlement','settlement',true],['amount','Amount','number',true],['payment_date','Payment Date','date',true],['payment_method','Payment Method','select',false,['bank_transfer','cash','wise','whish','other']],['payment_reference','Payment Reference','text'],['erp_receipt_number','ERP Receipt Number','text'],['notes','Notes','textarea']]}
  };
  function fieldOptions(type,selected,resellerId){ if(type==='reseller')return selectOptions(state.data.resellers,'id',r=>`${r.reseller_code} · ${r.company_name}`,selected); if(type==='company')return selectOptions(state.data.companies.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.company_code} · ${r.company_name}`,selected); if(type==='contact')return selectOptions(state.data.contacts.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.contact_code} · ${contactName(r.id)}`,selected); if(type==='lead')return selectOptions(state.data.leads.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.lead_code} · ${r.lead_name||companyName(r.company_id)}`,selected); if(type==='deal')return selectOptions(state.data.deals.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.deal_code} · ${r.deal_name}`,selected); if(type==='activation')return selectOptions(state.data.activations.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.activation_code} · ${companyName(r.company_id)}`,selected); if(type==='settlement')return selectOptions(state.data.settlements.filter(x=>!resellerId||x.reseller_id===resellerId),'id',r=>`${r.settlement_code} · ${r.description}`,selected); if(type==='profile')return selectOptions(state.data.profiles.filter(x=>x.is_active!==false),'id',r=>r.name||r.full_name||r.email,selected); return ''; }
  function fieldHtml(f,record,resellerId){ const [name,label,type,required,opts]=f; let value=record?.[name]??''; if(type==='datetime-local'&&value)value=new Date(value).toISOString().slice(0,16); const req=required?'required':''; if(type==='textarea')return `<label class="rm-field full"><span>${esc(label)}</span><textarea name="${esc(name)}" ${req}>${esc(value)}</textarea></label>`; if(type==='checkbox')return `<label class="rm-field rm-checkbox"><input type="checkbox" name="${esc(name)}" ${value?'checked':''}><span>${esc(label)}</span></label>`; if(type==='select')return `<label class="rm-field"><span>${esc(label)}</span><select name="${esc(name)}" ${req}>${(opts||[]).map(o=>`<option value="${esc(o)}" ${clean(value)===o?'selected':''}>${esc(labelStatus(o))}</option>`).join('')}</select></label>`; if(['reseller','company','contact','lead','deal','activation','settlement','profile'].includes(type))return `<label class="rm-field"><span>${esc(label)}</span><select name="${esc(name)}" data-rm-ref="${esc(type)}" ${req}>${fieldOptions(type,value,resellerId)}</select></label>`; return `<label class="rm-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${type==='number'?'step="0.01"':''} ${req}></label>`; }
  function openModal(entity,record={},options={}){ const cfg=configs[entity]; if(!cfg)return; const rid=record.reseller_id||options.prefill?.reseller_id||''; const merged={...record,...(options.prefill||{})}; state.modal={entity,id:record.id||'',registerOwnership:!!options.registerOwnership}; const root=$('rmModalRoot'); root.className='rm-modal-backdrop'; root.innerHTML=`<div class="rm-modal" role="dialog" aria-modal="true"><div class="rm-modal-head"><h2>${record.id?'Edit':'New'} ${esc(cfg.title)}</h2><button class="rm-modal-close" type="button" data-rm-action="close-modal" aria-label="Close">×</button></div><form id="rmEntityForm"><div class="rm-form-grid">${cfg.fields.map(f=>fieldHtml(f,merged,rid)).join('')}${options.registerOwnership?'<div class="rm-note rm-field full">Saving this company will also create a <strong>Pending Registration</strong> ownership request for the selected reseller.</div>':''}</div><div class="rm-modal-foot"><button type="button" class="btn ghost" data-rm-action="close-modal">Cancel</button><button type="submit" class="btn primary">Save</button></div></form></div>`; setTimeout(()=>root.querySelector('input,select,textarea')?.focus(),0); }
  function closeModal(){ const root=$('rmModalRoot'); if(root){root.className='rm-hidden';root.innerHTML='';} state.modal=null; }
  function updateDependentModalOptions(){ const form=$('rmEntityForm'); if(!form)return; const rid=form.elements.reseller_id?.value||''; form.querySelectorAll('select[data-rm-ref]').forEach(sel=>{const type=sel.dataset.rmRef;if(type==='reseller'||type==='profile')return;const old=sel.value;sel.innerHTML=fieldOptions(type,old,rid);if([...sel.options].some(o=>o.value===old))sel.value=old;}); }
  function modalPayload(){ const form=$('rmEntityForm'); const cfg=configs[state.modal?.entity]; if(!form||!cfg)return null; const fd=new FormData(form); const out={}; cfg.fields.forEach(([name,,type])=>{ if(type==='checkbox')out[name]=form.elements[name]?.checked||false; else {let v=fd.get(name); if(type==='number')v=v===''?0:num(v); else if(v==='')v=null; out[name]=v;} }); if(state.modal.entity==='contact'&&!out.full_name)out.full_name=[out.first_name,out.last_name].filter(Boolean).join(' ')||null; if(state.modal.entity==='deal'&&(!out.estimated_incheck_amount||out.estimated_incheck_amount<=0))out.estimated_incheck_amount=calcAmount(out.reseller_id,out.customer_sale_amount,out.location_count); if(state.modal.entity==='activation'&&(!out.amount_due_to_incheck||out.amount_due_to_incheck<=0))out.amount_due_to_incheck=calcAmount(out.reseller_id,out.customer_sale_amount,out.location_count); return out; }
  async function saveModal(){ const m=state.modal; if(!m)return; const payload=modalPayload(); if(!payload)return; const db=getClient(); if(!db)return; const who=identity().id; const table=TABLE[m.entity]; try{ let saved; if(m.id){ if('updated_by' in (state.data[table]||{}))payload.updated_by=who; const {data,error}=await db.from(table).update({...payload,updated_by:who}).eq('id',m.id).select('*').single(); if(error)throw error;saved=data;} else {payload.created_by=who; const {data,error}=await db.from(table).insert(payload).select('*').single(); if(error)throw error;saved=data;} if(m.entity==='company'&&m.registerOwnership&&saved?.id){ const {error}=await db.from('reseller_ownerships').insert({reseller_id:saved.reseller_id,company_id:saved.id,status:'pending',created_by:who}); if(error)throw error; } closeModal(); await loadAll(); renderActive(); toast('Saved successfully.'); }catch(err){console.error('[ResellerManagement] save failed',err);toast(err.message||'Unable to save','error');} }

  async function runMarketCheck(){ const db=getClient(); if(!db)return; const q={p_reseller_id:$('rmMarketReseller')?.value||null,p_company_name:$('rmMarketCompany')?.value||null,p_website:$('rmMarketWebsite')?.value||null,p_email:$('rmMarketEmail')?.value||null,p_phone:$('rmMarketPhone')?.value||null}; const box=$('rmMarketResult'); if(box)box.innerHTML='<div class="rm-empty">Checking CRM, clients and reseller ownership…</div>'; try{const {data,error}=await db.rpc('reseller_market_check',q);if(error)throw error;const result=Array.isArray(data)?data[0]:data;state.lastMarketQuery=q;state.lastMarketResult=result;const status=result?.status||'available';if(box)box.innerHTML=`<div class="rm-market-result"><div><h3>${badge(status)}</h3><p>${status==='available'?'No active ownership, client or active sales engagement was found.':'Status only is shown; ownership and confidential CRM details remain hidden.'}</p></div>${status==='available'?button('Register Prospect','register-prospect','primary'):''}</div>`;await loadAll();renderOwnerships();}catch(err){if(box)box.innerHTML=`<div class="rm-empty">${esc(err.message||'Market Check failed.')}</div>`;} }

  async function updateRow(table,id,changes,msg){ const db=getClient(); if(!db)return; const {error}=await db.from(table).update({...changes,updated_by:identity().id}).eq('id',id); if(error)throw error; await loadAll(); renderActive(); toast(msg||'Updated.'); }
  async function ownershipAction(id,status){ const o=state.data.ownerships.find(x=>x.id===id); if(!o)return; const changes={status,decided_at:new Date().toISOString(),decided_by:identity().id}; if(status==='approved'){changes.starts_at=new Date().toISOString();changes.expires_at=new Date(Date.now()+num(state.data.resellers.find(r=>r.id===o.reseller_id)?.ownership_days||90)*86400000).toISOString();} await updateRow('reseller_ownerships',id,changes,`Ownership ${labelStatus(status).toLowerCase()}.`); }
  async function extendOwnership(id){ const o=state.data.ownerships.find(x=>x.id===id);if(!o)return;const days=num(state.data.resellers.find(r=>r.id===o.reseller_id)?.ownership_days||90);const base=o.expires_at&&new Date(o.expires_at)>new Date()?new Date(o.expires_at):new Date();base.setDate(base.getDate()+days);await updateRow('reseller_ownerships',id,{expires_at:base.toISOString()},`Ownership extended ${days} days.`); }
  async function statusAction(table,id,status,extra={}){ await updateRow(table,id,{status,...extra},`Status changed to ${labelStatus(status)}.`); }

  async function handleAction(action,b){ try{
    if(action==='refresh'){await refresh(true);return;} if(action==='close-modal'){closeModal();return;} if(action==='goto-market'){activate('resellerMarketCheck');return;}
    if(action==='new-reseller')return openModal('reseller',{currency:'USD',payment_term_days:30,commercial_model:'per_location',ownership_days:90,status:'onboarding',renewal_responsibility:'reseller',hardware_model:'reseller'});
    if(action==='new-company')return openModal('company',{company_status:'prospect',source:'manual',estimated_locations:1}); if(action==='new-contact')return openModal('contact',{contact_status:'active'}); if(action==='new-lead')return openModal('lead',{status:'new',priority:'medium',currency:'USD'}); if(action==='new-deal')return openModal('deal',{stage:'prospecting',currency:'USD',location_count:1,probability_percent:10}); if(action==='new-activation')return openModal('activation',{status:'draft',product_name:'InCheck 360',billing_frequency:'annual',currency:'USD',location_count:1}); if(action==='new-request')return openModal('request',{status:'submitted',priority:'normal',request_type:'general'}); if(action==='new-renewal')return openModal('renewal',{status:'upcoming',currency:'USD',current_locations:1,renewal_date:addDays(today(),60)}); if(action==='new-settlement')return openModal('settlement',{source_type:'manual',status:'pending',currency:'USD',due_date:addDays(today(),30)});
    if(action.startsWith('edit-')){const entity=action.replace('edit-','');const arr=state.data[entity==='reseller'?'resellers':entity==='company'?'companies':entity==='contact'?'contacts':entity==='lead'?'leads':entity==='deal'?'deals':entity==='activation'?'activations':entity==='request'?'requests':entity==='renewal'?'renewals':'settlements'];const rec=arr.find(x=>x.id===b.dataset.id);if(rec)return openModal(entity,rec);}
    if(action==='register-prospect'){const q=state.lastMarketQuery||{};return openModal('company',{reseller_id:q.p_reseller_id||'',company_name:q.p_company_name||'',website:q.p_website||'',main_email:q.p_email||'',main_phone:q.p_phone||'',company_status:'prospect',source:'market_check',estimated_locations:1},{registerOwnership:true});}
    if(action==='ownership-approve')return ownershipAction(b.dataset.id,'approved'); if(action==='ownership-reject')return ownershipAction(b.dataset.id,'rejected'); if(action==='ownership-release')return ownershipAction(b.dataset.id,'released'); if(action==='ownership-extend')return extendOwnership(b.dataset.id);
    if(action==='deal-won')return updateRow('reseller_deals',b.dataset.id,{stage:'won',won_at:new Date().toISOString()},'Deal marked Won. A draft activation was created automatically.');
    if(action==='activation-submit')return statusAction('reseller_activations',b.dataset.id,'submitted',{requested_at:new Date().toISOString()}); if(action==='activation-review')return statusAction('reseller_activations',b.dataset.id,'under_review'); if(action==='activation-approve')return statusAction('reseller_activations',b.dataset.id,'approved',{approved_at:new Date().toISOString(),approved_by:identity().id}); if(action==='activation-reject')return statusAction('reseller_activations',b.dataset.id,'rejected'); if(action==='activation-activate')return statusAction('reseller_activations',b.dataset.id,'activated',{activated_at:new Date().toISOString()});
    if(action==='request-start')return statusAction('reseller_requests',b.dataset.id,'in_progress'); if(action==='request-wait')return statusAction('reseller_requests',b.dataset.id,'waiting_on_reseller'); if(action==='request-resolve')return statusAction('reseller_requests',b.dataset.id,'resolved',{resolved_at:new Date().toISOString(),resolved_by:identity().id}); if(action==='request-close')return statusAction('reseller_requests',b.dataset.id,'closed');
    if(action==='renewal-contacting')return statusAction('reseller_renewals',b.dataset.id,'contacting_customer'); if(action==='renewal-confirm')return statusAction('reseller_renewals',b.dataset.id,'confirmed',{decision_date:today()}); if(action==='renewal-renew')return statusAction('reseller_renewals',b.dataset.id,'renewed',{decision_date:today()}); if(action==='renewal-no')return statusAction('reseller_renewals',b.dataset.id,'not_renewing',{decision_date:today()});
    if(action==='record-payment'){const s=state.data.settlements.find(x=>x.id===b.dataset.id);if(s)return openModal('payment',{reseller_id:s.reseller_id,settlement_id:s.id,amount:balance(s),payment_date:today()});}
  }catch(err){console.error('[ResellerManagement] action failed',err);toast(err.message||'Action failed','error');} }

  function toast(message,type='success'){ try{ if(window.UI?.toast)return window.UI.toast(message,type); if(window.showToast)return window.showToast(message,type); }catch{} console[type==='error'?'error':'log']('[ResellerManagement]',message); }
  function boot(){ const tryNow=()=>{ if(document.body?.classList.contains('auth-locked'))return; if(isAdmin()){mount();} }; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tryNow,{once:true}); else tryNow(); const obs=new MutationObserver(()=>tryNow()); if(document.body)obs.observe(document.body,{attributes:true,attributeFilter:['class']}); window.setTimeout(tryNow,600); window.setTimeout(tryNow,1800); }
  return Object.freeze({boot,refresh:()=>refresh(true),activate});
})();

ResellerManagement.boot();
window.ResellerManagement = ResellerManagement;
