const WorkflowGuide = (() => {
  const S = { open:false, module:'', tour:-1, tourSteps:[], timer:null, nudge:null, observer:null, booted:false };
  const clean = v => String(v ?? '').replace(/\s+/g,' ').trim();
  const norm = v => clean(v).toLowerCase().replace(/[\s-]+/g,'_');
  const esc = v => clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const role = () => { try { const p=window.Session?.authContext?.()?.profile||window.Session?.state?.profile||{}; return norm(p.role_key||p.role||window.Session?.role?.()||''); } catch { return ''; } };
  const userKey = () => { try { const c=window.Session?.authContext?.()||{},p=c.profile||window.Session?.state?.profile||{},u=c.user||window.Session?.state?.user||{}; return clean(u.id||p.id||u.email||p.email||'user'); } catch { return 'user'; } };
  const visible = el => { if(!(el instanceof Element)||el.closest('[hidden],.rm-hidden'))return false; const x=getComputedStyle(el),r=el.getBoundingClientRect(); return x.display!=='none'&&x.visibility!=='hidden'&&r.width>0&&r.height>0; };

  function moduleInfo(){
    const tab=document.querySelector('.view-tab.active,.view-tab[aria-selected="true"]');
    if(!tab)return{key:'',label:'Current page',group:'Workspace',tab:null,view:null};
    const key=clean(tab.dataset.view||tab.id),label=clean(tab.textContent||key),g=tab.closest('.view-menu-group');
    const group=clean(g?.querySelector('.view-menu-group-label > span:last-child')?.textContent||g?.getAttribute('aria-label')||'Workspace').replace(/\s+modules$/i,'');
    const view=document.getElementById(tab.getAttribute('aria-controls')||'')||document.querySelector('.view.active,[role="tabpanel"].active');
    return{key,label,group,tab,view};
  }
  function can(step){
    if(step.roles?.length&&!step.roles.map(norm).includes(role()))return false;
    if(step.resource&&step.action&&window.Permissions?.can){try{if(!window.Permissions.can(step.resource,step.action))return false;}catch{}}
    return true;
  }
  function target(step,root=moduleInfo().view||document){
    for(const q of (Array.isArray(step?.target)?step.target:step?.target?[step.target]:[])){
      try{const local=[...(root||document).querySelectorAll(q)].find(visible);if(local)return local;const global=[...document.querySelectorAll(q)].find(visible);if(global)return global;}catch{}
    }
    return null;
  }
  function status(view=moduleInfo().view){
    if(!view)return'';
    for(const q of ['[data-current-status]','[data-status]:not([data-status=""])','.status-badge','.rm-badge','select[name="status"]','select[id*="Status"]']){
      let nodes=[];try{nodes=[...view.querySelectorAll(q)]}catch{}
      for(const n of nodes){if(!visible(n))continue;const v=clean(n.value||n.dataset.currentStatus||n.dataset.status||n.textContent);if(v&&v.length<60&&!/^status$/i.test(v))return v;}
    }
    return'';
  }
  const st=(title,text,targetSel='',extra={})=>({title,text,target:targetSel,...extra});
  const basePolicies=['The guide follows your current role, permissions and visible ERP actions. It never unlocks or bypasses a blocked action.','If the ERP workflow rejects, blocks or requires approval for an action, the ERP decision is authoritative.'];

  function proposalPolicies(){
    const rules=(Array.isArray(window.Workflow?.state?.rules)?window.Workflow.state.rules:[]).filter(r=>r?.is_active!==false&&['proposal','proposals'].includes(clean(r?.resource).toLowerCase()));
    if(!rules.length)return['Proposal approvals and discount thresholds are controlled by the live Workflow configuration. Numeric limits are intentionally not asserted until those rules are loaded.'];
    const uniq=(f)=>[...new Set(rules.map(r=>r?.[f]).filter(v=>v!==null&&v!==undefined&&v!==''))];
    const line=(label,a,b)=>{const x=uniq(a),y=uniq(b),p=[];if(x.length)p.push(`no-approval ${x.join(' / ')}%`);if(y.length)p.push(`hard stop ${y.join(' / ')}%`);return p.length?`${label}: ${p.join(', ')} from the currently loaded Workflow rules.`:''};
    return[
      line('Annual SaaS','annual_saas_no_approval_until_percent','annual_saas_hard_stop_discount_percent'),
      line('One-time fees','one_time_fee_no_approval_until_percent','one_time_fee_hard_stop_discount_percent'),
      line('Hardware','hardware_no_approval_until_percent','hardware_hard_stop_discount_percent'),
      'If a previously approved discount is increased, the Workflow Engine can require a new approval.'
    ].filter(Boolean);
  }

  const CRM_POLICY=['Search/reuse existing company and contact records before creating new ones so the CRM stays duplicate-safe.'];
  const FIN_POLICY=['Financial actions should remain traceable to their source invoice, payment, credit, payable or approved accounting record.'];
  const RESELLER_POLICY=['Reseller-owned records are scoped by reseller_id. Market ownership and financial controls must not be bypassed.'];
  const C={
    issues:{purpose:'Create, prioritize and follow operational tickets until resolution.',steps:[st('Review the queue','Use KPIs and filters to identify what needs attention first.',['#kpis','#issuesSummaryCard','#mainFiltersPanel']),st('Create the ticket correctly','Complete the issue, priority, module, ownership and evidence fields.',['#createTicketBtn','[data-global-create="true"]'],{resource:'tickets',action:'create'}),st('Open the ticket','Review description, evidence and history before changing it.','#issuesTable tbody tr'),st('Update progress','Keep status and meaningful notes aligned with real progress.',['#bulkEditBtn','[data-action*="edit"]']),st('Close with evidence','Resolve/close only after the underlying issue is addressed.')],policies:['Use the ticket log for meaningful changes instead of undocumented follow-up.']},
    calendar:{purpose:'Plan events, deadlines and operational follow-up.',steps:[st('Review the calendar','Check existing commitments first.',['#calendarView','.fc-view-harness']),st('Create the event','Add clear timing, owner and notes.',['#calendarView .btn.primary','button[id*="Event"]']),st('Check ownership and conflicts','Confirm the right person and timing.'),st('Keep it current','Move, complete or cancel the event when the plan changes.')],policies:['Calendar visibility/editing follows employee-calendar access rules.']},
    lifecycleAnalytics:{purpose:'Understand conversion and aging across the commercial lifecycle.',steps:[st('Set the reporting scope','Apply the relevant period/stage filters.','#lifecycleAnalyticsView [class*="filter"]'),st('Review conversion and aging','Look for stalled or weak stages.'),st('Open the source records','Drill into the leads/deals/proposals causing the signal.'),st('Act at source','Change the operational record, not only the dashboard.')],policies:['Analytics summarizes source records; it does not replace them.']},
    clientSuccess:{purpose:'Manage client health, locations, risks and follow-up.',steps:[st('Select the client scope','Choose the relevant client/group/location.','#clientSuccessView select'),st('Review health and attention items','Check risks, issues and renewals.'),st('Open the client context','Review ownership, brands/locations and history.'),st('Record the follow-up','Keep the client-success record aligned with reality.')],policies:['Actions follow client_success permissions.']},
    csm:{purpose:'Record meaningful daily customer-success work and next actions.',steps:[st('Review today','Check what is already recorded.'),st('Add the activity','Capture client, action, outcome and next follow-up.','#csmView .btn.primary'),st('Set the next owner/action','Make the follow-up explicit.'),st('Close the day cleanly','Ensure important interactions are represented.')],policies:['Use source CRM/client records too when the business state itself changes.']},
    hr:{purpose:'Manage employee, HR and payroll records through authorized controls.',steps:[st('Choose the HR area','Open the relevant employee/payroll area.','#hrView [role="tab"]'),st('Verify employee and period','Confirm identity, status and affected period.'),st('Enter the HR action','Complete required fields using the visible authorized action.','#hrView .btn.primary'),st('Review before finalizing','Verify dates, amounts and status.')],policies:['HR/payroll visibility and writes are role-controlled.']},
    company:{purpose:'Maintain the CRM company master used by contacts, leads, deals and verification.',steps:[st('Search first','Check name/domain before creating another company.',['#companyView input[type="search"]','#companyView [placeholder*="Search"]']),st('Create or open the company','Reuse the existing legal/commercial entity when it exists.',['#companyView .btn.primary','#companyView table tbody tr']),st('Complete core data','Keep name, domain, country and industry accurate.'),st('Complete verification when required','Finish verification so downstream workflows are not blocked.'),st('Continue through CRM','Link contacts/leads/deals instead of duplicating the company.')],policies:CRM_POLICY},
    contacts:{purpose:'Maintain contact identities and link them to the correct company/work.',steps:[st('Search first','Check name, email and phone.',['#contactsView input[type="search"]','#contactsView [placeholder*="Search"]']),st('Create or open the contact','Reuse the existing person and link the correct company.',['#contactsView .btn.primary','#contactsView table tbody tr']),st('Keep identifiers accurate','Email/phone are important for matching.'),st('Link commercial context','Use the contact from the relevant lead/deal/client.')],policies:CRM_POLICY},
    leads:{purpose:'Qualify potential opportunities before active deal work.',steps:[st('Review new leads','Filter by status/owner.','#leadsView [class*="filter"]'),st('Open the lead','Confirm company/contact, need and ownership.','#leadsView table tbody tr'),st('Qualify the opportunity','Record enough context to progress, nurture or close.'),st('Convert when ready','Create a deal only when active commercial work should start.','#leadsView [data-action*="convert"]')],policies:CRM_POLICY},
    deals:{purpose:'Manage qualified opportunities through proposal and outcome.',steps:[st('Review pipeline','Focus on deals needing action.','#dealsView [class*="filter"]'),st('Open the deal','Confirm company, contact, value, timing and next action.','#dealsView table tbody tr'),st('Keep the stage real','Move stage only when customer progress changed.'),st('Create the proposal','Use the linked proposal action when commercially ready.',['#dealsView [data-action*="proposal"]','button[id*="Proposal"]']),st('Record won/lost outcome','Keep the lifecycle traceable.')],policies:CRM_POLICY},
    proposals:{purpose:'Prepare controlled commercial offers and move them through workflow, approval, sending and acceptance.',steps:[st('Confirm the commercial source','Start from the correct deal/company/contact.'),st('Build the scope','Add SaaS, one-time and hardware items with correct quantity/duration/billing.',['#proposalItemsTable','[data-proposal-items]','#proposalsView .btn.primary']),st('Review discounts','Enter discounts normally; Workflow determines allow/approval/block.'),st('Complete terms','Confirm validity, payment terms and billing frequency.'),st('Save / send through Workflow','Use the available transition and wait for approval when required.',['#proposalsView [data-action*="send"]','#proposalsView [data-action*="save"]','#proposalsView .btn.primary']),st('After acceptance','Continue to the linked agreement.')],policies:proposalPolicies},
    agreements:{purpose:'Manage the contractual record linked to accepted commercial terms and billing.',steps:[st('Open the agreement','Confirm the correct customer/commercial source.',['#agreementsView table tbody tr','#agreementsView .btn.primary']),st('Review parties and annex','Verify parties, dates, service term and commercial annex.'),st('Complete signatures','Keep status aligned with actual signature state.'),st('Protect the signed record','Use amendments for later contractual changes.'),st('Continue to billing','Use the permitted invoice action.',['#agreementsView [data-action*="invoice"]','button[id*="Invoice"]'])],policies:['Signed agreements are controlled records; later contractual changes should use the amendment flow.']},
    commissionTracker:{purpose:'Track commission eligibility, installments, payments and receipts.',steps:[st('Select the commission scope','Filter to the salesperson/period/record.'),st('Review the source transaction','Verify the linked commercial/payment event.'),st('Record the authorized action','Use only the available financial action.','#commissionTrackerView .btn.primary'),st('Verify status/receipt','Confirm the resulting commission state.')],policies:['Commission access is controlled by sales-commission permissions/access level.']},
    proposalCatalog:{purpose:'Maintain shared products/modules/fees used in proposals.',steps:[st('Search the catalog','Reuse an existing item when appropriate.'),st('Create or edit the item','Keep name, category, pricing and billing defaults accurate.','#proposalCatalogView .btn.primary'),st('Verify proposal behavior','Confirm the item appears with expected defaults.')],policies:['Catalog changes can affect future proposal pricing and defaults.']},
    accounting:{purpose:'Operate accounting records available to your authorized role.',steps:[st('Choose the accounting area','Open the correct accounting sub-area.'),st('Review the source document','Confirm counterparty, amount, date and reference.'),st('Record the transaction','Use the authorized accounting action.','#accountingView .btn.primary'),st('Reconcile the result','Confirm balance/status agrees with source.')],policies:FIN_POLICY},
    clients:{purpose:'Manage active client context, service dates, locations, billing and renewal visibility.',steps:[st('Search/open the client','Reuse the existing client master.',['#clientsView input[type="search"]','#clientsView table tbody tr']),st('Review active service','Check locations, service dates and linked commercial records.'),st('Review finance/renewal','Identify collection or renewal follow-up.'),st('Update at source','Change contractual/financial data in its agreement/invoice flow.')],policies:['Client summaries are downstream; agreements, invoices and receipts remain controlled sources.']},
    invoices:{purpose:'Issue invoices, track amounts due and connect verified payment to receipts.',steps:[st('Confirm the source','Verify agreement/client/customer and invoice items.'),st('Review invoice details','Check number, amounts, due date and payment schedule.'),st('Issue through the allowed action','Treat issued invoices as controlled financial documents.',['#invoicesView [data-action*="issue"]','#invoicesView .btn.primary']),st('Track collection','Use payment follow-up/forecast.'),st('Record verified payment','Use the receipt/accounting flow so balance updates.')],policies:FIN_POLICY},
    receipts:{purpose:'Record verified customer payments against the correct financial source.',steps:[st('Verify payment first','Confirm money was received and identify its invoice/schedule.'),st('Create the receipt','Record amount, date, method and reference.','#receiptsView .btn.primary'),st('Check allocation','Confirm correct invoice/client and amount.'),st('Verify balance','Review resulting invoice/client statement.')],policies:[...FIN_POLICY,'Do not create a receipt for an unverified payment.']},
    creditNotes:{purpose:'Apply controlled invoice credits while preserving the audit trail.',steps:[st('Identify the invoice','Select the correct source invoice.'),st('Enter credit and reason','Use the supported credit-note action.','#creditNotesView .btn.primary'),st('Review financial impact','Confirm amount and resulting invoice/client balance.'),st('Finalize through permitted status','Use configured financial-role actions only.')],policies:FIN_POLICY},
    paymentForecast:{purpose:'Prioritize collection using due dates, balances and follow-up status.',steps:[st('Set the collection view','Filter by due/overdue, period, client and currency.'),st('Review priority balances','Start with overdue and near-due items.'),st('Open the source record','Verify invoice/client before follow-up.'),st('Record follow-up','Capture real outcome and next expected action.')],policies:['Forecast is derived from financial records; payment/receipt changes belong in source workflows.']},
    renewalForecast:{purpose:'Identify upcoming renewals and drive them to renew/change/non-renewal.',steps:[st('Set the renewal horizon','Review target month/period.'),st('Open the source client/item','Confirm service dates/location.'),st('Record the decision','Use renewal/no-renewal/override controls.'),st('Create renewal records','Continue through agreement/invoice when confirmed.')],policies:['Renewal overrides should document their reason and remain traceable to source.']},
    biners:{purpose:'Control payables, schedules, payments and forecast visibility.',steps:[st('Open the payable','Confirm vendor/source, obligation and due schedule.'),st('Review scheduled payments','Check upcoming/overdue amounts.'),st('Record payment','Enter amount, date, method and reference.','#binersView .btn.primary'),st('Verify remaining balance','Confirm schedule/forecast updated.')],policies:FIN_POLICY},
    communication_centre:{purpose:'Keep operational conversations attached to work, with ownership and closure.',steps:[st('Open/create the conversation','Use a clear title/category and link the ERP record.','#communicationCentreView .btn.primary'),st('Assign the audience','Set the users/roles who need to act.'),st('Reply in the same thread','Keep follow-up together.'),st('Resolve/close when complete','Close only after the communication need is resolved.')],policies:['Visibility/actions follow Communication Centre permissions; replies notify according to active notification rules.']},
    notifications:{purpose:'Review actionable ERP notifications and navigate to their source.',steps:[st('Review unread/priority items','Start with approvals, reminders and follow-up.'),st('Open the source record','Use the deep link rather than acting from summary only.'),st('Complete the source action','Resolve the real record.'),st('Clear notification state','Mark read after review.')],policies:['Notifications are prompts; the source module is authoritative.']},
    notificationSetup:{purpose:'Configure which ERP events notify whom and through which channels.',steps:[st('Select the event/rule','Identify the business event.'),st('Review recipients/channels','Confirm recipient mode and delivery channels.'),st('Save deliberately','Avoid notification noise.','#notificationSetupView .btn.primary'),st('Verify with a real event','Observe the source workflow after configuration.')],policies:['Notification rules should be actionable and have a clear owner.']},
    workflow:{purpose:'Configure live state transitions, approvals and policy thresholds.',steps:[st('Select the resource','Open the exact workflow rule.'),st('Review transition','Confirm current/next status.'),st('Review approvals/limits','Check approval role and commercial thresholds.'),st('Save deliberately','Verify downstream module behavior after saving.','#workflowView .btn.primary')],policies:['Workflow is a source of truth for policy enforcement and for live proposal policy text shown by this guide.']},
    users:{purpose:'Manage ERP user identities, roles and account status.',steps:[st('Find the user','Open the existing account first.'),st('Review identity and role','Confirm the correct person and job role.'),st('Create/update access','Assign the minimum role required.','#usersView .btn.primary'),st('Verify resulting access','Confirm module visibility/permissions.'),st('Deactivate when access should stop','Do not recycle/shared credentials.')],policies:['Role, permissions, email and active status remain administrator-controlled; users edit only allowed personal profile fields.']},
    rolePermissions:{purpose:'Control what each ERP role can see and do.',steps:[st('Choose the role','Open the role being reviewed.'),st('Review permissions','Compare view/create/edit/delete/export to real job needs.'),st('Apply least privilege','Grant only required access.'),st('Verify UX and route protection','Unauthorized modules should be hidden and direct access blocked.')],policies:['Sensitive access should be enforced by backend/RLS as well as UI visibility.']},
    backupCenter:{purpose:'Operate controlled ERP backup and restore procedures.',steps:[st('Review backup health','Check latest backup/status/warnings.'),st('Choose the correct action','Confirm target/environment before backup/restore.'),st('Verify completion','Check the backup log/status after operation.')],policies:['Backup/restore is privileged; verify the target before destructive restore actions.']},
    userActivity:{purpose:'Understand login, active/idle time, module dwell and meaningful UI activity.',steps:[st('Select the session','Open the relevant user/session.'),st('Read status in sequence','Use sign-in, first activity, active/idle and session end together.'),st('Review module time','Use dwell/visits to understand where work happened.'),st('Review timeline','Use meaningful actions/state changes for investigation.')],policies:['User Activity does not collect passwords, keystrokes, form values or raw mouse coordinates.']},
    resellerDashboard:{purpose:'Monitor reseller pipeline, customers, renewals and financial exposure.',steps:[st('Review attention items','Start with pending ownership, activations, overdue balances and renewals.'),st('Open the source record','Move from KPI to reseller/activation/settlement.'),st('Prioritize exceptions','Act on blocked/overdue/upcoming items.')],policies:RESELLER_POLICY},
    resellers:{purpose:'Maintain reseller master profiles, agreements, territory and commercial terms.',steps:[st('Search existing resellers','Open the master before creating another.'),st('Create/update the reseller','Set territory, dates, currency, terms and commercial model.','[data-rm-action="new-reseller"]'),st('Review commercial terms','These drive what the reseller owes InCheck 360.'),st('Link user access when needed','Assign reseller_user to the correct reseller only.')],policies:RESELLER_POLICY},
    resellerCrm:{purpose:'Manage reseller companies, contacts, leads and deals through a separate channel CRM.',steps:[st('Run Market Check first','Check global engagement status before registration.','#resellerMarketCheckTab'),st('Register only if permitted','Create the reseller CRM record after ownership rules allow it.'),st('Build company/contact context','Keep identifiers accurate.'),st('Move lead to deal','Qualify and progress the reseller opportunity.'),st('On win, request activation','Hand off won business to activation.')],policies:RESELLER_POLICY},
    resellerMarketCheck:{purpose:'Check global company/contact availability without exposing private ownership data.',steps:[st('Choose reseller context','Admin selects the reseller performing the check.','#rmMarketReseller'),st('Enter identifiers','Use company plus domain/email/phone when possible.',['#rmMarketCompany','#rmMarketWebsite','#rmMarketEmail','#rmMarketPhone']),st('Run Market Check','The engine checks InCheck 360 main CRM/client data and reseller-channel data globally.','#rmMarketForm button[type="submit"]'),st('Follow the returned status','Proceed only when the result permits registration/ownership.'),st('Register ownership when available','Protect and trace the engagement.')],policies:['Market Check is status-only: it must not reveal another reseller, internal owner, contact details or CRM notes.','Already Engaged can come from InCheck 360 main CRM, an existing client or another reseller.']},
    resellerActivations:{purpose:'Move won reseller business through internal approval into activation and obligation.',steps:[st('Confirm won opportunity','Verify reseller, customer/deal and ownership.'),st('Create activation','Enter package, locations, users, dates and hardware/config.','[data-rm-action="new-activation"]'),st('Review reseller terms','Admin verifies ownership and commercial model.'),st('Approve/activate','Use internal approval; obligation is derived from configured terms.'),st('Verify settlement/renewal','Confirm downstream records were created.')],policies:[...RESELLER_POLICY,'Reseller obligation values are protected from reseller-side manual lowering.']},
    resellerRequests:{purpose:'Handle reseller operational requests through a controlled queue.',steps:[st('Create the correct request type','Choose ownership/pricing/hardware/billing/support/renewal/etc.','[data-rm-action="new-request"]'),st('Assign/review','Make the internal owner and requested change clear.'),st('Progress the status','Use the real request state.'),st('Update the source record too','Do not only close the request when source data must change.')],policies:RESELLER_POLICY},
    resellerRenewals:{purpose:'Track reseller customer renewal decisions and next obligations.',steps:[st('Review upcoming renewals','Prioritize approaching dates.'),st('Record follow-up','Use contacting/confirmed/not-renewing states.'),st('Confirm scope','Verify locations/package/dates.'),st('Renew or close','Confirmed renewal creates the next controlled obligation.')],policies:RESELLER_POLICY},
    resellerSettlements:{purpose:'Track what resellers owe InCheck 360 and payments against obligations.',steps:[st('Review outstanding/overdue','Start with status/due date.'),st('Open the source','Confirm activation/renewal causing the obligation.'),st('Record verified payment','Use authorized payment action.'),st('Verify balance','Confirm settlement and statement update.')],policies:[...RESELLER_POLICY,'Reseller users must not directly reduce internal amount-due fields.']},
    resellerStatement:{purpose:'Reconcile reseller debits, credits/payments and running balance.',steps:[st('Select reseller','Choose the reseller to reconcile.','#rmStatementReseller'),st('Review debits/credits','Trace obligations and payments to source.'),st('Fix mismatches at source','Do not edit a calculated statement line.')],policies:RESELLER_POLICY},
    resellerReports:{purpose:'Compare reseller pipeline, customers, locations, renewals and balances.',steps:[st('Review comparison','Use commercial and financial signals together.'),st('Identify exceptions','Look for stalled pipeline, overdue balances and renewals.'),st('Open the source record','Act from CRM/settlement/renewal, not report only.')],policies:RESELLER_POLICY}
  };

  function generic(m){return{purpose:`Use ${m.label||'this page'} to complete the work available to your role while keeping the source record current.`,steps:[st('Review context','Check filters, status and attention indicators.'),st('Open or create the required record','Use the visible action available to your role.',['.view.active .btn.primary','.view.active table tbody tr','.view.active [data-action]']),st('Complete required information','Keep data accurate and related records linked.'),st('Follow the valid next action','Do not bypass hidden/disabled workflow controls.'),st('Verify the result','Confirm status and downstream records reflect the action.')],policies:[]};}
  function guide(m=moduleInfo()){const g=C[m.key]||generic(m),pol=typeof g.policies==='function'?g.policies():g.policies||[];return{...g,steps:(g.steps||[]).filter(can),policies:[...pol,...basePolicies]};}
  const seenKey=k=>`monitorcore:workflow-guide:seen:${userKey()}:${k}`;
  const tourKey=k=>`monitorcore:workflow-guide:tour:${userKey()}:${k}`;
  const seen=k=>{try{return localStorage.getItem(seenKey(k))==='1'}catch{return true}};
  const markSeen=k=>{try{localStorage.setItem(seenKey(k),'1')}catch{}};
  const toured=k=>{try{return localStorage.getItem(tourKey(k))==='1'}catch{return false}};
  const markTour=k=>{try{localStorage.setItem(tourKey(k),'1')}catch{}};

  function root(){let x=document.getElementById('workflowGuideRoot');if(!x){x=document.createElement('div');x.id='workflowGuideRoot';x.className='workflow-guide-root';x.hidden=true;document.body.appendChild(x)}return x;}
  function tourRoot(){let x=document.getElementById('workflowGuideWalkthrough');if(!x){x=document.createElement('div');x.id='workflowGuideWalkthrough';x.className='workflow-guide-walkthrough';x.hidden=true;document.body.appendChild(x)}return x;}
  function floating(){if(document.body?.classList.contains('auth-locked'))return;let b=document.getElementById('workflowGuideFloatingBtn');if(!b){b=document.createElement('button');b.id='workflowGuideFloatingBtn';b.type='button';b.className='workflow-guide-floating-btn';b.innerHTML='<span aria-hidden="true">?</span><span>Guide Me</span>';b.onclick=()=>open(true);document.body.appendChild(b)}}
  function headerButton(){if(document.body?.classList.contains('auth-locked'))return;const m=moduleInfo(),v=m.view;if(!v)return;const h=v.querySelector('[data-icds-header-actions]')||v.querySelector('.rm-page-header .rm-actions');if(!h||h.querySelector('[data-workflow-guide-open]'))return;const b=document.createElement('button');b.type='button';b.className='btn ghost workflow-guide-header-btn';b.dataset.workflowGuideOpen='true';b.innerHTML='<span aria-hidden="true">?</span> Guide Me';b.onclick=()=>open(true);h.prepend(b)}
  function nextText(g,m){const x=norm(status(m.view));if(m.key==='proposals'){if(!x||x==='draft')return'Complete scope and terms, then use the Workflow-controlled save/send action.';if(x.includes('pending')&&x.includes('approval'))return'Wait for the required approval; do not bypass the Workflow decision.';if(x==='sent')return'Track customer response; any pricing change must pass Workflow again.';if(x.includes('accept'))return'Continue to the linked agreement.'}if(m.key==='agreements'&&x.includes('signed'))return'Continue to the permitted billing/activation action.';if(m.key==='invoices'){if(x.includes('paid'))return'Verify receipt and statement.';if(x.includes('issued')||x.includes('sent')||x.includes('overdue'))return'Continue payment follow-up and record verified payment through the financial flow.'}if(m.key==='resellerMarketCheck')return'Enter reliable identifiers and run Market Check before registration.';const a=g.steps.find(s=>target(s,m.view));return a?.title||g.steps[0]?.title||'Review this page and follow the next visible ERP action.'}
  function stepHtml(s,i,m){const t=target(s,m.view);return`<li class="workflow-guide-step ${t?'has-target':''}"><div class="workflow-guide-step-number">${i+1}</div><div class="workflow-guide-step-body"><strong>${esc(s.title)}</strong><p>${esc(s.text)}</p>${t?`<button type="button" class="workflow-guide-locate" data-guide-locate="${i}">Show me</button>`:''}</div></li>`}

  function open(manual=false){
    if(document.body?.classList.contains('auth-locked'))return;stopTour(false);const m=moduleInfo();if(!m.key)return;S.module=m.key;const g=guide(m),r=root(),x=status(m.view);r.hidden=false;document.body.classList.add('workflow-guide-open');S.open=true;markSeen(m.key);
    r.innerHTML=`<div class="workflow-guide-backdrop" data-guide-close></div><aside class="workflow-guide-panel" role="dialog" aria-modal="true" aria-labelledby="workflowGuideTitle"><header class="workflow-guide-panel-header"><div><span class="workflow-guide-kicker">Workflow Guide</span><h2 id="workflowGuideTitle">${esc(m.label)}</h2><p>${esc(m.group)} · ${esc(role().replace(/_/g,' ')||'authenticated user')}</p></div><button type="button" class="workflow-guide-close" data-guide-close aria-label="Close guide">×</button></header><div class="workflow-guide-panel-body"><section class="workflow-guide-where"><div><span>Where you are</span><strong>${esc(m.label)}</strong></div><div><span>Current status</span><strong>${esc(x||'Page / list view')}</strong></div></section><section class="workflow-guide-card"><span class="workflow-guide-card-label">What this page is for</span><p>${esc(g.purpose)}</p></section><section class="workflow-guide-card workflow-guide-next"><span class="workflow-guide-card-label">Recommended next action</span><strong>${esc(nextText(g,m))}</strong></section><section class="workflow-guide-section"><div class="workflow-guide-section-head"><div><span class="workflow-guide-card-label">Step by step</span><h3>Do this in order</h3></div><span class="workflow-guide-count">${g.steps.length} steps</span></div><ol class="workflow-guide-steps">${g.steps.map((s,i)=>stepHtml(s,i,m)).join('')}</ol></section><section class="workflow-guide-section workflow-guide-policy-section"><div class="workflow-guide-section-head"><div><span class="workflow-guide-card-label">Rules & policies</span><h3>Controls that apply here</h3></div></div><ul class="workflow-guide-policies">${g.policies.map(p=>`<li><span aria-hidden="true">◆</span><p>${esc(p)}</p></li>`).join('')}</ul></section></div><footer class="workflow-guide-footer"><div class="workflow-guide-footer-status">${toured(m.key)?'✓ Walkthrough completed before':'First time here? Run the guided walkthrough.'}</div><div class="workflow-guide-footer-actions"><button type="button" class="btn ghost" data-guide-close>Close</button><button type="button" class="btn primary" data-guide-start>Start walkthrough</button></div></footer></aside>`;
    r.querySelectorAll('[data-guide-close]').forEach(b=>b.onclick=close);r.querySelector('[data-guide-start]')?.addEventListener('click',startTour);r.querySelectorAll('[data-guide-locate]').forEach(b=>b.onclick=()=>locate(g.steps[Number(b.dataset.guideLocate)],m));
  }
  function close(){const r=document.getElementById('workflowGuideRoot');if(r)r.hidden=true;document.body?.classList.remove('workflow-guide-open');S.open=false}
  function locate(s,m=moduleInfo()){const t=target(s,m.view);if(!t)return;t.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});t.classList.add('workflow-guide-target-flash');setTimeout(()=>t.classList.remove('workflow-guide-target-flash'),1800)}
  function startTour(){const m=moduleInfo(),g=guide(m),steps=g.steps.filter(s=>target(s,m.view));S.tourSteps=steps.length?steps:g.steps.slice(0,1);if(!S.tourSteps.length)return;S.tour=0;close();showTour()}
  function showTour(){const r=tourRoot(),m=moduleInfo(),s=S.tourSteps[S.tour];if(!s)return stopTour(true);document.querySelectorAll('.workflow-guide-walkthrough-target').forEach(x=>x.classList.remove('workflow-guide-walkthrough-target'));const t=target(s,m.view);if(t){t.classList.add('workflow-guide-walkthrough-target');t.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'})}const total=S.tourSteps.length;r.hidden=false;document.body.classList.add('workflow-guide-walkthrough-open');r.innerHTML=`<div class="workflow-guide-walkthrough-shade"></div><section class="workflow-guide-coach" role="dialog" aria-modal="true"><div class="workflow-guide-coach-top"><span>Guide Me · ${esc(m.label)}</span><button type="button" data-tour-end aria-label="End walkthrough">×</button></div><div class="workflow-guide-coach-progress"><span style="width:${Math.max(8,((S.tour+1)/total)*100)}%"></span></div><div class="workflow-guide-coach-count">Step ${S.tour+1} of ${total}</div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><div class="workflow-guide-coach-actions"><button type="button" class="btn ghost" data-tour-prev ${S.tour===0?'disabled':''}>Back</button><button type="button" class="btn primary" data-tour-next>${S.tour===total-1?'Finish':'Next'}</button></div></section>`;r.querySelector('[data-tour-end]').onclick=()=>stopTour(false);r.querySelector('[data-tour-prev]').onclick=()=>{if(S.tour>0){S.tour--;showTour()}};r.querySelector('[data-tour-next]').onclick=()=>{if(S.tour>=total-1)stopTour(true);else{S.tour++;showTour()}}}
  function stopTour(done=false){document.querySelectorAll('.workflow-guide-walkthrough-target').forEach(x=>x.classList.remove('workflow-guide-walkthrough-target'));const r=document.getElementById('workflowGuideWalkthrough');if(r)r.hidden=true;document.body?.classList.remove('workflow-guide-walkthrough-open');if(done&&S.module)markTour(S.module);S.tour=-1;S.tourSteps=[]}
  function firstVisit(m){if(!m.key||seen(m.key)||document.body?.classList.contains('auth-locked'))return;clearTimeout(S.nudge);S.nudge=setTimeout(()=>{if(moduleInfo().key===m.key&&!seen(m.key))open(false)},650)}
  function refresh(){if(document.body?.classList.contains('auth-locked')){close();stopTour(false);document.getElementById('workflowGuideFloatingBtn')?.remove();return}floating();headerButton();const m=moduleInfo();if(!m.key)return;if(S.module!==m.key){S.module=m.key;if(S.open)open(true);firstVisit(m)}}
  function schedule(ms=80){clearTimeout(S.timer);S.timer=setTimeout(refresh,ms)}
  function boot(){if(S.booted)return;S.booted=true;root();tourRoot();document.addEventListener('click',e=>{if(e.target?.closest?.('.view-tab'))schedule(80)});window.addEventListener('hashchange',()=>schedule(50));window.addEventListener('popstate',()=>schedule(50));window.addEventListener('incheck360:ui:ready',()=>schedule(30));window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(S.tour>=0)stopTour(false);else if(S.open)close()}});window.addEventListener('incheck360:workflow-guide:refresh',()=>schedule(0));if(typeof MutationObserver!=='undefined'&&document.body){S.observer=new MutationObserver(rs=>{if(rs.some(r=>r.addedNodes?.length||(r.type==='attributes'&&['class','aria-selected'].includes(r.attributeName))))schedule(120)});S.observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','aria-selected']})}window.Session?.subscribe?.((_u,d={})=>{if(d.reason==='signed_out'){S.module='';close();stopTour(false)}schedule(120)});schedule(50);setTimeout(()=>schedule(0),700);setTimeout(()=>schedule(0),1800)}
  return Object.freeze({open:()=>open(true),close,startWalkthrough:startTour,stopWalkthrough:stopTour,refresh,boot,getGuide:guide,currentModule:moduleInfo});
})();
WorkflowGuide.boot();
window.WorkflowGuide=WorkflowGuide;
